### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by DarkWingMcQuack** [SChernykh/p2pool#1]
Hey i realy like the project and would like to help/contribute.
Is there a short guide how to contribute or a list of TODOs?
I could help refactoring the code in some places.

**Comment by DarkWingMcQuack** [comment]
opening a [gitter](gitter.im) channel or any other chatroom could also help discussing the project

**Comment by SChernykh** [comment]
I will publish instructions for building from source and testing next week. You can contribute by running a p2pool node, testing how it works and makig a bug report if anything breaks. All discussions will be held on #monero-pow IRC channel, I prefer to keep github only for actual bug reports.
