### ISSUE TITLE
monero#p2pool-api-v0.17 fails with boost 1.77

### ISSUE THREAD

**Issue by cirocosta** [SChernykh/p2pool#10]
Hi!

trying to build the fork against the boost 1.77 is currently yielding the following

```
#37 21.49 /src/src/common/i18n.cpp: In function 'std::string i18n_get_language()':
#37 21.49 /src/src/common/i18n.cpp:74:8: error: 'transform' is not a member of 'std'
#37 21.49    74 |   std::transform(language.begin(), language.end(), language.begin(), tolower);
#37 21.49       |        ^~~~~~~~~
```

`mj` recently provided a fix for it though: https://github.com/monero-project/monero/pull/7902

I believe that if we rebase the fork with release-v0.17 we should be good (latest commit there seems to be from 10 days ago, fix is 7 ago)

thanks!

**Comment by SChernykh** [comment]
Rebased

**Comment by cirocosta** [comment]
works great! thank you @SChernykh 👍
