### ISSUE TITLE
serve miners only when fully synced

### ISSUE THREAD

**Issue by tywkah** [SChernykh/p2pool#100]
Hello!
1) Would you please so kind add an option of opening stratum port only upon full sync?
I'm sure it would save electric costs and encrease potentional income (clients can failover while initial p2pool syncing).
2) Is there any idea how to prevent mining air upon a monerod node connection lost? For ex block incoming connections to stratum port if all network connections to other peers are dropped or their traffic pauses ? Is there a way for p2pool to check this out if monerod had lost connections to the worldwide net, so it could temporary block incoming connections to the stratum port until global network connection to be reestablished?
Thanks

**Comment by SChernykh** [comment]
p2pool sync takes a few minutes and the hashrate is not lost while it's syncing. It's just mining on its own independent p2pool "branch", essentially solo-mining. Regarding monerod or p2pool network connection issues, p2pool usually writes detailed errors/warnings in these cases, it's better to set up a script that restarts p2pool and monerod in this case (stratum connections will be automatically reset then).

**Comment by tywkah** [comment]
but readme says to wait!
> Wait until initial p2pool sync is finished, it shouldn't take more than 5-10 minutes, once completed xmrig should be able to connect to the stratum server on port 3333.

And pauses in cmd point it:
```
...
ECHO Wait until the daemon shows fully synced before continuing. This can take some time.
PAUSE
%~dp0\xmrig.exe ...
```
:O

It looks like useless mining (real solo? several tens of minutes for solo sometimes?! why?) before synced, especially that there will be much more "share found" messages in console output ('fake 100k shares') then in real p2pool stats (i mean shares that would be accounted in pplns window if a block would be found). I've already mentioned this earlier, anyway

**Comment by SChernykh** [comment]
That pause is not necessary with recent p2pool versions.

**Comment by EDad-v2** [comment]
Those shares found during sync are indeed confusing when viewing the output of status though. :/
I leave my stratum port closed via firewall until sync is finished to get around that.

**Comment by ar-** [comment]
Just adding to that. When this happens (so always), the status display tells me later:
`Shares found       = 5`
and at the same time:
`Your shares               = 0 blocks (+0 uncles, 0 orphans)`

If my connection time is less than 6 hours, that should not be possible.

**Comment by The0ffle** [comment]
>

**Comment by SChernykh** [comment]
P2Pool v1.8: `Stratum share counters get reset after initial sync to avoid confusion`
