### ISSUE TITLE
submit_block (external blob): daemon returned error: unknown error

### ISSUE THREAD

**Issue by HacksLua** [SChernykh/p2pool#101]
**It's normal?**

Monerod.exe:
monerod.exe --out-peers 32 --in-peers 32 --data-dir monero-storage --rpc-bind-ip 127.0.0.1 --confirm-external-bind --zmq-pub tcp://127.0.0.1:18083 --disable-dns-checkpoints --enable-dns-blocklist
![aaCQqq9FU3s](https://user-images.githubusercontent.com/20579067/150490581-c872dc5b-7dc7-40c5-9111-dd48342063b7.jpg)

P2Pool.exe:
p2pool.exe --host 127.0.0.1 --wallet "WALLET"

![_vfzCPmmKUY](https://user-images.githubusercontent.com/20579067/150490651-8c9dfbc2-6755-423e-832b-61228423157d.jpg)
![kiaGHvKChcc](https://user-images.githubusercontent.com/20579067/150490662-0764a397-fa80-4927-bd71-3e63c558d242.jpg)
![FDzKck2XjOE](https://user-images.githubusercontent.com/20579067/150490667-3a09494b-d9f4-4736-adc6-1d9076bfffb4.jpg)

XMRig.exe:
xmrig.exe -o 192.168.0.119:3333 -u x+300000 --cpu-max-threads-hint 50

I'am just sit and waiting results :)

**Comment by SChernykh** [comment]
It's not a critical error, but it shows that monerod doesn't have the best connectivity to the rest of Monero network. Maybe your connetion is slow or has high ping.

**Comment by HacksLua** [comment]
> It's not a critical error, but it shows that monerod doesn't have the best connectivity to the rest of Monero network. Maybe your connetion is slow or has high ping.

It really is, thanks!
