### ISSUE TITLE
Access `status` command from backgrounded process

### ISSUE THREAD

**Issue by caheredia** [SChernykh/p2pool#102]
I'm running `monderod`, `p2pool`, and `xmrig` as cron jobs on reboot, e.g, 
```
@reboot /home/xmr/mine/wallet/bin/monerod --detach --prune-blockchain --sync-pruned-blocks --zmq-pub tcp://127.0.0.1:18083 --disable-dns-checkpoints --enable-dns-blocklist
@reboot /home/xmr/mine/p2pool/build/p2pool --host 127.0.0.1 --wallet 49ZA3PEiJ2p5bEZANu1XqXPfngEgP2BsN8dzbZFLYfhyMap1TvYN1jDHAwNccnGrTuUKyoEv2Gae5ek6iW5b9ihYHbjanCF
```
However, by doing so I lose the ability to call `status` on p2pool. Is there an easy workaround for this that I'm not privy too?

**Comment by marvin8** [comment]
You could run them in a `tmux` session something like this:

```
@reboot tmux new-session -s p2pool /home/xmr/mine/p2pool/build/p2pool --host 127.0.0.1 --wallet 49ZA3PEiJ2p5bEZANu1XqXPfngEgP2BsN8dzbZFLYfhyMap1TvYN1jDHAwNccnGrTuUKyoEv2Gae5ek6iW5b9ihYHbjanCF

```

Then later you can connect to that tmux session by opening a terminal and typing `tmux a -t p2pool`

I run all sorts of stuff in tmux sessions and think it would be time spent wisely becoming familiar with tmux. One resurce I have found useful is this [TMUX Guide](https://tmuxguide.readthedocs.io/en/latest/index.html)

**Comment by SChernykh** [comment]
p2pool has `--data-api path_to_api_directory` and `--stratum-api` command line parameters for external access to the status.

**Comment by caheredia** [comment]
@SChernykh thanks, seeing the notes in the change log was helpful, https://github.com/SChernykh/p2pool/releases/tag/v1.2
