### ISSUE TITLE
A few errors, newbie needs help!

### ISSUE THREAD

**Issue by obuntuski** [SChernykh/p2pool#103]
Hi, I had everything running once this morning but now I'm getting some errors in p2pool. 

failed to open p2pool.log
couldn't open/create p2pool.cache
failed to save peer list

its also displaying this:
couldn't allocate RandomX dataset using large pages
couldn't allocate RandomX cache using large pages
couldn't allocate RandomX cache using large pages

not sure if its related...

It syncs up fine. I can paste the full page if needed.

**Comment by obuntuski** [comment]
Im running this on ubuntu 21.10, 20.04 doesn't work with my WLAN card for some reason.

**Comment by SChernykh** [comment]
`couldn't allocate ... using large pages` means literally what it says. You need to enable enough huge pages before starting p2pool, it's done like this in Ubuntu:
```
sudo sysctl vm.nr_hugepages=1280
```
You need to increase this number and restart p2pool until it stops complaining.

```
failed to open p2pool.log
couldn't open/create p2pool.cache
failed to save peer list
```
p2pool doesn't have write access to the directory it's running in. Check file permissions for the user you use to run p2pool.

**Comment by obuntuski** [comment]
This has been extremely helpful thank you. This has all been quite a learning experience and I'm lovin' it.
