### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AnFunctionArray** [SChernykh/p2pool#104]
So if I mine for smallest amount on minexmr there is something happening - here I followed all the guides and got found a blockchain at certain moments - had shares etc but not even in p2pool observer.

Been mining for a day on p2pool - compiled everything from source (monerod, p2pool and xmrig for my mac mini - no observable failures).

But yeah I mine 2 mins on minexmr - on the dashboard and like the 0.00001 XMR. Mine here on p2pool - absolutely nothing (not even on p2pool observer).

I'm really crushed and defeated.

**Comment by SChernykh** [comment]
From FAQ on p2pool.io:

> P2Pool doesn't work exactly like regular pools - there's no "pending balance" here. You need to find a pool share first and then wait for P2Pool to find a Monero block. You'll get a payout to your XMR wallet as soon as a block is found and you have shares in PPLNS window. It can take several days to a week to find a share if your hashrate is low. Type "status" command in P2Pool console or visit P2Pool observer to check your progress.

Minexmr can show you the balance, but you won't get a payout there until you reach at least 0.004 XMR which will take longer than to find a share on p2pool, so just keep mining if you don't have any errors. What's your hashrate?

**Comment by AnFunctionArray** [comment]
2400 H/s at top - with the newest gui monero I compiled to test if p2pool would work but it turns out it doesn't however the solo mining options seems faster.

**Comment by SChernykh** [comment]
What do you mean "p2pool doesn't work"? Do you get any errors in log? Don't expect to see "0.000001 XMR" somewhere, this is not how p2pool works. Read more here: https://github.com/SChernykh/p2pool#how-pplns-works-in-p2pool
If you have 2400 h/s, it will take more than 5 days on average to find a share: https://p2pool.observer/calculate-share-time?hashrate=2400&magnitude=1
But when you find a share, you will get a payout at the main p2pool. But it's better to try p2pool-mini with your hashrate.

**Comment by AnFunctionArray** [comment]
I would at least expect some more insight - why can't I see myself on p2pobserver

**Comment by SChernykh** [comment]
You will see yourself on p2pool obsersver after you find at least 1 p2pool share.

**Comment by alter-sachin** [comment]
hey, is this a profitable excercise. I am a young fellow looking to learn and earn.
would be lovely to know the real world status of these activities from experts such as yourself...@
Thank you in anticipation of your reply
