### ISSUE TITLE
Logging does not seem to work when running in background

### ISSUE THREAD

**Issue by snex** [SChernykh/p2pool#122]
Made a quick systemd daemon to have p2pool run on startup as a service, but I noticed that the logging does not seem to work when doing this. Nothing is being written to p2pool.log unless the app is run in the foreground. It would be nice to be able to tail the logs of a background service just to verify everything is working properly. The user running the daemon has access to write to the file and relevant folders so it's not that.

edit: Forgot to mention! I'm running on Ubuntu 20.04, built from source on release tag v1.7.

**Comment by SChernykh** [comment]
Show your full systemd config. Logging is done by simply creating p2pool.log and writing to it, there should be no difference between system service and normal run. It's either wrong permissions or wrong working directory.

**Comment by SChernykh** [comment]
I'm not sure that `WorkingDirectory=~` would work. Try `WorkingDirectory=/home/snex/github/p2pool/build/p2pool` instead.

**Comment by snex** [comment]
Looks like that did it. Strange that this worked for other services. Thanks!

**Comment by martin-braun** [comment]
@SChernykh I removed `StandardOutput` and `StandardError` in the hope it will just log to `journalctl`, but it does not. Why?

**Comment by SChernykh** [comment]
Because p2pool logs to its own log file, not to syslog. It requires special system functions to log there, and it's not even available on all supported platforms.
