### ISSUE TITLE
Too many P2Pool Connections 

### ISSUE THREAD

**Issue by ASTMINERONE** [SChernykh/p2pool#129]
My p2Pool status screen is showing that I have 41 connections to my mini p2pool. I only have 37 rigs in my setup. All are running xmrig 6.16.2. How do i find out what and who the these extra 4 rigs are that are connected to my pool?

**Comment by SChernykh** [comment]
It might be random port scans. P2Pool release v1.7 has some mitigations for this:
> StratumServer: disconnect and ban inactive clients

**Comment by ASTMINERONE** [comment]
Im somewhat new, what does "StratumServer: disconnect and ban inactive clients" mean and what is the linux command to run this action?

**Comment by SChernykh** [comment]
You just need to update P2Pool to v1.7, it was a quote from the list of changes in v1.7

**Comment by ASTMINERONE** [comment]
I updated this morning it’s working great except for this issue.

**Comment by ASTMINERONE** [comment]
Also since I restarted on version 1.7 I have had 12 shares on the mini but no payouts. The observer says I’m getting payouts but nothing showing in my wallet.

**Comment by SChernykh** [comment]
You can run
```
lsof -p $(pidof p2pool) | grep :3333
```
to see which IPs are connected to P2Pool Stratum port (if you use different port number, change 3333 above). As for payouts, make sure your wallet is fully synced. If the observer sees it, the payment happened.

**Comment by ASTMINERONE** [comment]
Ok thank you

**Comment by ASTMINERONE** [comment]
Thank you for that Linux command it cleared things up for me. I’m good to go.
