### ISSUE TITLE
P2Pool v1.8 released...

### ISSUE THREAD

**Issue by RookyOne1** [SChernykh/p2pool#131]
[p2pool-v1.8-windows-x64.zip] https://github.com/SChernykh/p2pool/releases/download/v1.8/p2pool-v1.8-windows-x64.zip 

Both Edge and Chrome browsers refuse to download this file, stating in contains a virus.

**Comment by SChernykh** [comment]
It doesn't have a virus. Pretty much any software containing RandomX mining code will be flagged. Official Monero binaries are no exception.

**Comment by SChernykh** [comment]
Actually, Chrome doesn't say anything about a virus:
![Capture](https://user-images.githubusercontent.com/15806605/155944202-5db2437e-7949-4d1a-b713-bf82e378df7f.PNG)
I think it will go away after more people download the release.

**Comment by RookyOne1** [comment]
Managed to download it this morning without edge blocking the request.  However, window's anti-virus still tried to quarantine it...  Did not have any of these issues updating to v1.4, 1.5, 1.6 or 1.7!!!

Maybe as you said, window's needs a number of downloads before it passes it as safe?

**Comment by SChernykh** [comment]
The `p2pool.exe` file is identical to what was built on GitHub CI workers from commit https://github.com/SChernykh/p2pool/commit/0db57e50470aec8cb043eede7599a7a6a3548e26
Same build procedure was used for previous releases. It doesn't have a virus as long as GitHub servers are safe. Windows Defender gets triggered most likely by RandomX code.

**Comment by SChernykh** [comment]
Chrome doesn't trigger a warning anymore.
