### ISSUE TITLE
exit on error enhancement

### ISSUE THREAD

**Issue by aquino-a** [SChernykh/p2pool#132]
hi

right now if there are any errors p2pool it retries after 1 second.  after a while it stops. if you use it as a service it will always be active and doesnt restart.

It would be good to have that option for it to close. could possibly make a pr

more specifically when monerod isn't ready.

thanks

**Comment by SChernykh** [comment]
It doesn't exit if it can recover. In this case, it just waits until monerod is online. I don't see how restarting could help, it will just start waiting for monerod again.

**Comment by aquino-a** [comment]
yes you are right.
I guess it could be a bug. After so many times of retrying, p2pool would stop retrying and just sit there.

**Comment by aquino-a** [comment]
there was about 3 minutes  of jsonrpcrequest failed. then 'consolecommands started'.. then 10 'not synchronized' messages. Then the messages stopped until it caught a sigterm.

**Comment by SChernykh** [comment]
Can you reproduce it with p2pool v2.1? If not, I'll close this issue soon.
