### ISSUE TITLE
connections @1.8

### ISSUE THREAD

**Issue by tywkah** [SChernykh/p2pool#133]
Hello, looks like the connection limit doesn't  affect real number of them since recent changes... At least, outgoing ones:
![image](https://user-images.githubusercontent.com/93492811/156847230-fa58d566-dcf1-4016-b6b7-545877732fca.png)
Seems like a bug.
I've got some short disconnects from my isp though (~5 min).
`monerod.exe --data-dir \"%~dp0BC\" --log-file nul --rpc-restricted-bind-ip %IP% --rpc-restricted-bind-port xxxxx --no-igd --zmq-pub tcp://127.0.0.1:yyyyy --disable-dns-checkpoints --max-txpool-weight 104857600 --p2p-external-port zzzzz --out-peers 12 --in-peers 10 --limit-rate-down 4096 --limit-rate-up 256\""`

`p2pool.exe --loglevel 0 --host 127.0.0.1 --stratum %IP%:xxx --rpc-port yyy --zmq-port zzz --p2p 0.0.0.0:aaa --out-peers 12 --in-peers 10 --wallet %WLT%\""`

**Comment by SChernykh** [comment]
I can't reproduce it. P2Pool doesn't reduce the number of outgoing connections if it's already somehow above the limit. It can be an unstable connection like you say.

**Comment by tywkah** [comment]
Yeah, that happened only once. But maybe it would be useful to drop old [outgoing] connections off if the total number of them exceeds the user defined limit to prevent leaks and instability. Connections monitoring once an hour or even oftener if it doean't affect p2pool efficiency.

**Comment by SChernykh** [comment]
Old connections drop out naturally when people restart or stop their p2pool nodes, or when their connections go down. I don't see the need to forcefully close them. Also, this (more connections than the limit) is a rare occurrence anyway.

**Comment by tywkah** [comment]
ok, we'll see...
