### ISSUE TITLE
How to tell this is working properly?

### ISSUE THREAD

**Issue by Al-Campuzano** [SChernykh/p2pool#134]
Good UTC!
I'm new to this so pardon my ignorance. 

I started using p2pool a few days ago and everything seemed to be working correctly: I could see my related data populated in [P2Pool.Observer](https://p2pool.observer/), and I even got a few payouts. However, in the last couple of days everything in Pool Observer is set to `0` so I am not sure how to tell if something went wrong. 

I tried restarting everything last night, but still nothing showing in the observer anymore. 

The output from running `status` in the terminal:

```
status
2022-03-08 14:09:42.5463 SideChain status
Main chain height         = 2575141
Main chain hashrate       = 2.851 GH/s
Side chain height         = 1562636
Side chain hashrate       = 135.949 MH/s
PPLNS window              = 2160 blocks (+89 uncles, 0 orphans)
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
2022-03-08 14:09:42.5464 StratumServer status
Hashrate (15m est) = 0 H/s
Hashrate (1h  est) = 0 H/s
Hashrate (24h est) = 0 H/s
Total hashes       = 0
Shares found       = 0
Average effort     = 0.000%
Current effort     = 0.000%
Connections        = 1 (1 incoming)
2022-03-08 14:09:42.5464 P2PServer status
Connections    = 19 (9 incoming)
Peer list size = 340
Uptime         = 11h 50m 40s
2022-03-08 14:09:42.5464 Util no background jobs running
```

Thank you for helping me out. Let me know if you need any more info.

**Comment by SChernykh** [comment]
P2Pool status look good. How many mining rigs do you have and what's your hashrate? I see only 1 connected in Stratum status. If you want to see hashrates in Stratum server, you need to set fixed difficulty in xmrig:
> To set a custom fixed difficulty for your miner (for example, 10000), start XMRig with the following options:
`./xmrig -u x+10000 -o 127.0.0.1:3333`

**Comment by Al-Campuzano** [comment]
I'm _guessing_ i only have one mining rig. How do I double check that and find the hashrate?

**Comment by SChernykh** [comment]
If you run xmrig only on 1 computer, then `Connections        = 1 (1 incoming)` in Stratum status is correct.

**Comment by Al-Campuzano** [comment]
Yeah i am running it only on 1 computer

**Comment by Al-Campuzano** [comment]
After starting XMRig with a fixed difficulty i get this report from P2Pool. Does this look ok? i still don't have any data showing up in the Observer

```
status
2022-03-08 21:04:59.3443 SideChain status
Main chain height         = 2575334
Main chain hashrate       = 2.673 GH/s
Side chain height         = 1564955
Side chain hashrate       = 135.967 MH/s
PPLNS window              = 2160 blocks (+77 uncles, 0 orphans)
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
2022-03-08 21:04:59.3443 StratumServer status
Hashrate (15m est) = 2.193 KH/s
Hashrate (1h  est) = 2.297 KH/s
Hashrate (24h est) = 2.321 KH/s
Total hashes       = 21552155
Shares found       = 0
Average effort     = 0.000%
Current effort     = 1.585%
Connections        = 1 (1 incoming)
2022-03-08 21:04:59.3443 P2PServer status
Connections    = 15 (5 incoming)
Peer list size = 354
Uptime         = 2h 34m 45s
2022-03-08 21:04:59.3443 Util no background jobs running
```

**Comment by Al-Campuzano** [comment]
@SChernykh Is this fine or am i missing something. It's been about 4 days and i still don't see any in the pool observer

```
2022-03-11 14:42:55.7459 SideChain status
Main chain height         = 2577314
Main chain hashrate       = 2.775 GH/s
Side chain height         = 1587687
Side chain hashrate       = 136.615 MH/s
PPLNS window              = 2160 blocks (+74 uncles, 0 orphans)
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
2022-03-11 14:42:55.7459 StratumServer status
Hashrate (15m est) = 2.243 KH/s
Hashrate (1h  est) = 2.149 KH/s
Hashrate (24h est) = 2.402 KH/s
Total hashes       = 597159710
Shares found       = 0
Average effort     = 0.000%
Current effort     = 43.711%
Connections        = 1 (1 incoming)
2022-03-11 14:42:55.7459 P2PServer status
Connections    = 90 (18 incoming)
Peer list size = 462
Uptime         = 2d 20h 12m 41s
2022-03-11 14:42:55.7459 Util no background jobs running
```

**Comment by SChernykh** [comment]
It looks fine, but it will take you 7 days on average to find a share with this hashrate. It's better to switch to p2ool mini.

**Comment by Al-Campuzano** [comment]
Ok great, thank you for confirming 👍
