### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by our198** [SChernykh/p2pool#135]
E:\p2p\p2pool\build>cmake .. -G "Visual Studio 16 2019" -A x64
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.27.29112.0
-- The CXX compiler identification is MSVC 19.27.29112.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (add_subdirectory):
  The source directory

    E:/p2p/p2pool/external/src/RandomX

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "E:/p2p/p2pool/build/CMakeFiles/CMakeOutput.log".

**Comment by our198** [comment]
The system is: Windows - 10.0.17134 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.7.0+b89cb5fde
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2022/3/9 星期三 18:52:56。
节点 1 上的项目“E:\p2p\p2pool\build\CMakeFiles\3.18.4\CompilerIdC\CompilerIdC.vcxproj”(默认目标)。
PrepareForBuild:
  正在创建目录“Debug\”。
  正在创建目录“Debug\CompilerIdC.tlog\”。
InitializeBuildStatus:
  正在创建“Debug\CompilerIdC.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> E:\p2p\p2pool\build\CMakeFiles\3.18.4\CompilerIdC\.\CompilerIdC.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  正在删除文件“Debug\CompilerIdC.tlog\unsuccessfulbuild”。
  正在对“Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate”执行 Touch 任务。
已完成生成项目“E:\p2p\p2pool\build\CMakeFiles\3.18.4\CompilerIdC\CompilerIdC.vcxproj”(默认目标)的操作。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:02.20


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "E:/p2p/p2pool/build/CMakeFiles/3.18.4/CompilerIdC/CompilerIdC.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.7.0+b89cb5fde
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2022/3/9 星期三 18:52:59。
节点 1 上的项目“E:\p2p\p2pool\build\CMakeFiles\3.18.4\CompilerIdCXX\CompilerIdCXX.vcxproj”(默认目标)。
PrepareForBuild:
  正在创建目录“Debug\”。
  正在创建目录“Debug\CompilerIdCXX.tlog\”。
InitializeBuildStatus:
  正在创建“Debug\CompilerIdCXX.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> E:\p2p\p2pool\build\CMakeFiles\3.18.4\CompilerIdCXX\.\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  正在删除文件“Debug\CompilerIdCXX.tlog\unsuccessfulbuild”。
  正在对“Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
已完成生成项目“E:\p2p\p2pool\build\CMakeFiles\3.18.4\CompilerIdCXX\CompilerIdCXX.vcxproj”(默认目标)的操作。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:01.49


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "E:/p2p/p2pool/build/CMakeFiles/3.18.4/CompilerIdCXX/CompilerIdCXX.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: E:/p2p/p2pool/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_de173.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.7.0+b89cb5fde

版权所有(C) Microsoft Corporation。保留所有权利。



  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29112 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  CMakeCCompilerABI.c

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_de173.dir\Debug\\" /Fd"cmTC_de173.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "C:\msys64\mingw64\share\cmake-3.18\Modules\CMakeCCompilerABI.c"

  cmTC_de173.vcxproj -> E:\p2p\p2pool\build\CMakeFiles\CMakeTmp\Debug\cmTC_de173.exe




Detecting CXX compiler ABI info compiled with the following output:
Change Dir: E:/p2p/p2pool/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_09971.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.7.0+b89cb5fde

版权所有(C) Microsoft Corporation。保留所有权利。



  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29112 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  CMakeCXXCompilerABI.cpp

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_09971.dir\Debug\\" /Fd"cmTC_09971.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue "C:\msys64\mingw64\share\cmake-3.18\Modules\CMakeCXXCompilerABI.cpp"

  cmTC_09971.vcxproj -> E:\p2p\p2pool\build\CMakeFiles\CMakeTmp\Debug\cmTC_09971.exe

**Comment by SChernykh** [comment]
You didn't clone the whole source code. Start again with
```
git clone --recursive https://github.com/SChernykh/p2pool
```

**Comment by our198** [comment]
The download is complete, the compilation is still the same error

**Comment by SChernykh** [comment]
Don't download from github web page, do `git clone --recursive https://github.com/SChernykh/p2pool` as I said before.

**Comment by our198** [comment]
1 core 2G memory run？

**Comment by our198** [comment]
E:\>git clone --recursive https://github.com/SChernykh/p2pool
Cloning into 'p2pool'...
remote: Enumerating objects: 4429, done.
remote: Counting objects: 100% (911/911), done.
remote: Compressing objects: 100% (344/344), done.
remote: Total 4429 (delta 667), reused 647 (delta 562), pack-reused 3518
Receiving objects: 100% (4429/4429), 29.72 MiB | 475.00 KiB/s, done.
Resolving deltas: 100% (2281/2281), done.
Submodule 'external/src/RandomX' (https://github.com/SChernykh/RandomX) registered for path 'external/src/RandomX'
Submodule 'external/src/cppzmq' (https://github.com/SChernykh/cppzmq) registered for path 'external/src/cppzmq'
Submodule 'external/src/libsodium' (https://github.com/SChernykh/libsodium) registered for path 'external/src/libsodium'
Submodule 'external/src/libuv' (https://github.com/SChernykh/libuv) registered for path 'external/src/libuv'
Submodule 'external/src/libzmq' (https://github.com/SChernykh/libzmq) registered for path 'external/src/libzmq'
Submodule 'external/src/rapidjson' (https://github.com/SChernykh/rapidjson) registered for path 'external/src/rapidjson'
Submodule 'external/src/robin-hood-hashing' (https://github.com/SChernykh/robin-hood-hashing) registered for path 'external/src/robin-hood-hashing'
Submodule 'tests/googletest' (https://github.com/google/googletest) registered for path 'tests/googletest'
Cloning into 'E:/p2pool/external/src/RandomX'...
fatal: unable to access 'https://github.com/SChernykh/RandomX/': Failed to connect to github.com port 443 after 21074 ms: Timed out
fatal: clone of 'https://github.com/SChernykh/RandomX' into submodule path 'E:/p2pool/external/src/RandomX' failed
Failed to clone 'external/src/RandomX'. Retry scheduled
Cloning into 'E:/p2pool/external/src/cppzmq'...
remote: Enumerating objects: 2002, done.
remote: Counting objects: 100% (268/268), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 2002 (delta 124), reused 191 (delta 106), pack-reused 1734
Receiving objects: 100% (2002/2002), 654.79 KiB | 515.00 KiB/s, done.
Resolving deltas: 100% (1115/1115), done.
Cloning into 'E:/p2pool/external/src/libsodium'...
fatal: unable to access 'https://github.com/SChernykh/libsodium/': OpenSSL SSL_read: Connection was reset, errno 10054
fatal: clone of 'https://github.com/SChernykh/libsodium' into submodule path 'E:/p2pool/external/src/libsodium' failed
Failed to clone 'external/src/libsodium'. Retry scheduled
Cloning into 'E:/p2pool/external/src/libuv'...
fatal: unable to access 'https://github.com/SChernykh/libuv/': Failed to connect to github.com port 443 after 21053 ms: Timed out
fatal: clone of 'https://github.com/SChernykh/libuv' into submodule path 'E:/p2pool/external/src/libuv' failed
Failed to clone 'external/src/libuv'. Retry scheduled
Cloning into 'E:/p2pool/external/src/libzmq'...
fatal: unable to access 'https://github.com/SChernykh/libzmq/': OpenSSL SSL_read: Connection was reset, errno 10054
fatal: clone of 'https://github.com/SChernykh/libzmq' into submodule path 'E:/p2pool/external/src/libzmq' failed
Failed to clone 'external/src/libzmq'. Retry scheduled
Cloning into 'E:/p2pool/external/src/rapidjson'...
fatal: unable to access 'https://github.com/SChernykh/rapidjson/': Failed to connect to github.com port 443 after 21067 ms: Timed out
fatal: clone of 'https://github.com/SChernykh/rapidjson' into submodule path 'E:/p2pool/external/src/rapidjson' failed
Failed to clone 'external/src/rapidjson'. Retry scheduled
Cloning into 'E:/p2pool/external/src/robin-hood-hashing'...
fatal: unable to access 'https://github.com/SChernykh/robin-hood-hashing/': Failed to connect to github.com port 443 after 21029 ms: Timed out
fatal: clone of 'https://github.com/SChernykh/robin-hood-hashing' into submodule path 'E:/p2pool/external/src/robin-hood-hashing' failed
Failed to clone 'external/src/robin-hood-hashing'. Retry scheduled
Cloning into 'E:/p2pool/tests/googletest'...
fatal: unable to access 'https://github.com/google/googletest/': Failed to connect to github.com port 443 after 21074 ms: Timed out
fatal: clone of 'https://github.com/google/googletest' into submodule path 'E:/p2pool/tests/googletest' failed
Failed to clone 'tests/googletest'. Retry scheduled
Cloning into 'E:/p2pool/external/src/RandomX'...
fatal: unable to access 'https://github.com/SChernykh/RandomX/': Failed to connect to github.com port 443 after 26648 ms: Timed out
fatal: clone of 'https://github.com/SChernykh/RandomX' into submodule path 'E:/p2pool/external/src/RandomX' failed
Failed to clone 'external/src/RandomX' a second time, aborting

**Comment by SChernykh** [comment]
> Failed to connect to github.com port 443 after 21074 ms: Timed out

You have some problems with your connection.
