### ISSUE TITLE
How to turn off donations in Docker-Compose P2Pool?

### ISSUE THREAD

**Issue by Sabering1** [SChernykh/p2pool#136]
So i' am using docker-compose p2pool with xmrig, monerod, and p2pool and its all working fine and i build the docker file perfectly but how do i turn off the donations in xmrig that is bundled with this docker file thingy?

**Comment by SChernykh** [comment]
This is not a p2pool-related issue.

**Comment by hayden-cardwell** [comment]
Still a Github noob so let me know if it's bad practice to comment on a closed issue, but I did want to give it a go just in case anyone else searches this up. 

If you're using the docker instructions included within this repository and not going through SethForPrivacy's separate guide, you _should_ be able to also modify the section within the .env file labeled XMRIG_EXTRA_OPTIONS to include '--donate-level=0', making the whole line look like the following:
```
XMRIG_EXTRA_OPTIONS="--donate-level=0"
```
That being said, I can't in good faith give you the above information without making a comment about how XMRig is super valuable to the community, so consider not using the above configuration and supporting the devs.
