### ISSUE TITLE
RandomX_Hasher couldn't allocate RandomX VM (macOS)

### ISSUE THREAD

**Issue by wwinter86** [SChernykh/p2pool#14]
Hi I get an RandomX_Hasher couldn't allocate RandomX VM error on Mac. 

<img width="682" alt="William Cody Winter 2021-09-08 at 10 39 49" src="https://user-images.githubusercontent.com/1666150/132486171-3e67624b-2add-434e-8197-7be382a1fd71.png">

**Comment by SChernykh** [comment]
Fixed in https://github.com/SChernykh/p2pool/commit/c8a2a256e742519a80f319db13fc478804a78f97
`not enough PoW` warning shouldn't happen though, but maybe it was because of this bug.

**Comment by wwinter86** [comment]
I have made sure I am using the newest build too

**Comment by SChernykh** [comment]
Update again and build, the fix was made after your post.

**Comment by wwinter86** [comment]
I get a little bit of a different error now: 
<img width="682" alt="William Cody Winter 2021-09-08 at 11 17 54" src="https://user-images.githubusercontent.com/1666150/132492337-e1055024-c456-4c59-af88-f70000edd87c.png">

**Comment by SChernykh** [comment]
`not enough PoW` and then a crash shouldn't happen, your build is definitely broken in some way. Block at height 69394 has enough PoW, I've just checked. Can you build p2pool tests and run them? Go to `p2pool/tests` folder, then build and run them:
```
        mkdir build
        cd build
        cmake ..
        make
        ./p2pool_tests
```

**Comment by wwinter86** [comment]
I get this: 

<img width="682" alt="William Cody Winter 2021-09-08 at 11 33 08" src="https://user-images.githubusercontent.com/1666150/132494342-2f07d11a-3b2c-4251-a221-fda174324a2f.png">

**Comment by SChernykh** [comment]
Either RandomX or difficulty check is broken in your builds. I've updated pool_block test, can you git pull, rebuild and test again?

**Comment by wwinter86** [comment]
Now:
```
2021-09-08 10:39:40.4980 SideChain add_external_block: height = 69518, id = fd41d614817c6cd2d90f2c8356153d364d75e65e3abf92e596003803f91b4aa7, mainchain height = 2444856
2021-09-08 10:39:40.5197 SideChain add_external_block: not enough PoW for height = 69518, mainchain height 2444856
2021-09-08 10:39:40.5198 P2PServer peer 168.119.137.28:37889 banned for 600 seconds
2021-09-08 10:39:41.5633 SideChain add_external_block: height = 69519, id = a1784018f75add76b184e0970bfcc9e603dc0c86f488e928afa205ee80fe0e28, mainchain height = 2444856
zsh: segmentation fault  ./p2pool --host 127.0.0.1 --rpc-port 18081 --zmq-port 18083 --wallet    --p2p
```

**Comment by wwinter86** [comment]
I am on an M1 Mac btw

**Comment by wwinter86** [comment]
Currently getting:
<img width="682" alt="William Cody Winter 2021-09-08 at 11 44 37" src="https://user-images.githubusercontent.com/1666150/132495964-69c64efd-395b-4809-bbb6-63b3653538b0.png">

**Comment by SChernykh** [comment]
No, I mean run tests again with my latest code.

**Comment by wwinter86** [comment]
<img width="682" alt="William Cody Winter 2021-09-08 at 11 48 14" src="https://user-images.githubusercontent.com/1666150/132496389-1766b30a-daeb-4cd2-80aa-3e36350b7912.png">

**Comment by SChernykh** [comment]
RandomX is currently broken on M1, I'll make a fix later today.

**Comment by wwinter86** [comment]
> RandomX is currently broken on M1, I'll make a fix later today.

Thank you

**Comment by SChernykh** [comment]
Can you try again with the latest code? To make sure everything is updated:
- delete the whole p2pool folder
- build p2pool from scratch again

It should work now, I fixed a bug with RandomX code caching.

**Comment by wwinter86** [comment]
I get this while building now: 
```
Undefined symbols for architecture arm64:
  "flushInstructionCache(void const*, void const*)", referenced from:
      void randomx::JitCompilerA64::generateSuperscalarHash<8ul>(randomx::SuperscalarProgram (&) [8ul], std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >&) in librandomx.a(jit_compiler_a64.cpp.o)
      randomx::JitCompilerA64::JitCompilerA64() in librandomx.a(jit_compiler_a64.cpp.o)
      randomx::JitCompilerA64::JitCompilerA64() in librandomx.a(jit_compiler_a64.cpp.o)
      randomx::JitCompilerA64::generateProgram(randomx::Program&, randomx::ProgramConfiguration&) in librandomx.a(jit_compiler_a64.cpp.o)
      randomx::JitCompilerA64::generateProgramLight(randomx::Program&, randomx::ProgramConfiguration&, unsigned int) in librandomx.a(jit_compiler_a64.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [p2pool] Error 1
make[1]: *** [CMakeFiles/p2pool.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by SChernykh** [comment]
Oh, I forgot to update one file. Please try again with the latest code (delete p2pool folder first).

**Comment by SChernykh** [comment]
It should be working fine on M1 Mac now: https://i.imgur.com/lPVKVwv.png
