### ISSUE TITLE
Error in p2pserver and monerod quit

### ISSUE THREAD

**Issue by DATA-GaMi** [SChernykh/p2pool#145]
This has happened in the past two days, am I being attacked?
![p2pserver](https://user-images.githubusercontent.com/48061253/162600388-bd57b513-32c4-48c0-b010-1d55ffb2262e.png)

**Comment by SChernykh** [comment]
You should check for warnings and errors in monerod log. Being just 2 Monero blocks behind is not that bad, it happens sometimes. Adding `--disable-dns-checkpoints` to monerod command line helps.
