### ISSUE TITLE
Share found but no payout?

### ISSUE THREAD

**Issue by nrbrook** [SChernykh/p2pool#147]
I have read a few issues on here, but still don't understand. I have a low hash rate (3500H/s) but in p2pool console I saw 
```
2022-04-18 19:50:19.9463 StratumServer SHARE FOUND: mainchain height 2604849, diff 100000, client 127.0.0.1:57887 user x, effort 100.002%
2022-04-18 19:50:19.9464 P2Pool submit_sidechain_block: template id = 2, nonce = 85808, extra_nonce = 0
2022-04-18 19:50:19.9464 SideChain add_block: height = 1, id = 3148c699cf06a4fca40bb0da395e422d4ff08c3ed077ff7f35e970af3d057cbf, mainchain height = 2604849, verified = 1
2022-04-18 19:50:19.9464 SideChain new chain tip: next height = 2, next difficulty = 100000, main chain height = 2604849
2022-04-18 19:50:19.9468 BlockTemplate base  reward = 0.643594482622 XMR, 108 transactions, fees = 0.008593240000 XMR, weight = 190034
2022-04-18 19:50:19.9469 BlockTemplate final reward = 0.652187722622 XMR, weight = 190160, outputs = 1, 108 of 108 transactions included
2022-04-18 19:50:19.9470 StratumServer sent new job to 1/1 clients
```
several hours after starting. I can also see several more of these. Yet status shows 
```
2022-04-19 03:48:44.1575 SideChain status
Main chain height         = 2605075
Main chain hashrate       = 3.164 GH/s
Side chain ID             = mini
Side chain height         = 1369781
Side chain hashrate       = 16.598 MH/s
PPLNS window              = 2160 blocks (+21 uncles, 0 orphans)
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
2022-04-19 03:48:44.1575 StratumServer status
Hashrate (15m est) = 0 H/s
Hashrate (1h  est) = 2.497 KH/s
Hashrate (24h est) = 3.481 KH/s
Total hashes       = 100352007
Shares found       = 0
Average effort     = 0.000%
Current effort     = 60.461%
Connections        = 0 (0 incoming)
2022-04-19 03:48:44.1575 P2PServer status
Connections    = 10 (0 incoming)
Peer list size = 220
Uptime         = 8h 0m 24s
```
Why does it show shares found = 0 when it also has share found in console output? I'm using p2pool 1.9

**Comment by SChernykh** [comment]
This share was found before p2pool was fully synced, this is why it has `diff 100000` and was discarded when it synced. Real p2pool shares have much higher difficulty.

**Comment by nrbrook** [comment]
A few questions then:
1. Why is it giving XMRig jobs before it is fully synced?
2. Or, why is it reporting share found before it is fully synced? Surely these could just be ignored?
3. I can't find the word "sync" anywhere in the console output. How does it report when it is fully synced?
4. The logs could be improved to avoid confusion I've seen elsewhere here – "Block found" with it's ascii drawing is much more prominent than "share found" in the logs, although to most users "share found" is a more important event.
4.1. Block found log could be changed from `BLOCK FOUND: main chain block at height 2604592 was mined by this p2pool` to `BLOCK FOUND: main chain block at height 2604592 was mined by this p2pool (not you)` or `(by you)`
4.2. ASCII could be added to "share found" and/or removed from "block found"
4.3. "Share found" could include the expected payout?

**Comment by SChernykh** [comment]
1-2: p2pool node can mine independently from other nodes before it's fully synced, so there's a small chance you will find a block and get the full block reward to yourself while still syncing.
3: search for `new chain tip` message in the log
4: p2pool prints the payout amount after each BLOCK FOUND message if your wallet has a non-zero payout.

**Comment by nrbrook** [comment]
1-2. Ok, but I think if it didn't print the share found log or if the message was different it would avoid confusion.
3. Again if this included "fully synced" then this might avoid confusion
4. What does the log look like? I see e.g. "final reward = 0.643286275943" but given I've not received a payout it isn't clear that I shouldn't receive a payout from the logs.

I think if you come into this with a full understanding of how it all works and what the messages mean they are probably fine, but for new users it can be confusing as demonstrated in the issues on here. Simply changing some of the log messages and readme might help to prevent duplicate issues like this one. Thanks for making this tool!

**Comment by tywkah** [comment]
> 3. Again if this included "fully synced" then this might avoid confusion
@nrbrook You can add this string into the 'SideChain::update_chain_tip()' section right before the 's->reset_share_counters();' string:
`LOGINFO(0, log::Yellow() << "P2POOL'S BEEN SYNCED");`

![image](https://user-images.githubusercontent.com/93492811/168496774-d008d392-1ef1-4dab-a5ba-560f8de4aeac.png)

It would be found in the log regardless the '--loglevel' cmd parameter:

![image](https://user-images.githubusercontent.com/93492811/168496957-a146414b-48d5-45c6-8072-f90636968e50.png)

If you can't build it from sources you can use ''--loglevel 2' instead and search 'new chain tip:' instead as SChernykh replied above. 

This solution can be easily used in your own scripts, so I think it would be a good idea to add it to the project for "loglevel 0" as well. @SChernykh ?

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool/commit/72d70eba161c3d41ce6f67e2df2bc2ad057d4497

**Comment by tywkah** [comment]
> [72d70eb](https://github.com/SChernykh/p2pool/commit/72d70eba161c3d41ce6f67e2df2bc2ad057d4497)

@SChernykh It's so strange but it doesn't work anymore! I thought that I had mistaken and desided to clone repo from scratch without changing anything in the code (removed only one ASCII 'block found' message ). And it didn't work, the message doesn't appear in the log/console. I even tried my own strings and order but nothing happened...
<details>
<summary>log</summary>

```
NOTICE  2022-05-16 02:46:12.0499 Log started
NOTICE  2022-05-16 02:47:54.9656 SideChain add_external_block: block 40fb5fbdb91585d0612998400690750fc5b3b5ad4063647b8bfa0cc457989c60 has enough PoW for Monero height 2624375, submitting it
NOTICE  2022-05-16 02:47:54.9676 P2Pool submit_block: height = 2624411, external blob (5328 bytes)
NOTICE  2022-05-16 02:49:33.4940 SideChain add_external_block: block 20e15c34706f9b378a693e6ff0c774908dbfa102ba2e1f141a7c48dd613b752f has enough PoW for Monero height 2624350, submitting it
NOTICE  2022-05-16 02:49:33.4941 P2Pool submit_block: height = 2624412, external blob (4027 bytes)
NOTICE  2022-05-16 02:50:03.2182 SideChain add_external_block: block 9b7b32169db3b711c96c6b54455b8d770fb89f0d8461969601340a95dad0e985 has enough PoW for Monero height 2624309, submitting it
NOTICE  2022-05-16 02:50:03.2182 P2Pool submit_block: height = 2624413, external blob (3759 bytes)
NOTICE  2022-05-16 02:50:06.0123 SideChain add_external_block: block cebfea3f81784a4e8ef390672c76bbbbea0f65480a2d237b8086f45f55c93149 has enough PoW for Monero height 2624304, submitting it
NOTICE  2022-05-16 02:50:06.0125 P2Pool submit_block: height = 2624413, external blob (3625 bytes)
NOTICE  2022-05-16 02:50:16.8911 SideChain add_external_block: block 74c480f2ca439f4e1c1f6e4564f976573f0394663c9a5d530a6b9963d8b50309 has enough PoW for Monero height 2624284, submitting it
NOTICE  2022-05-16 02:50:16.8912 P2Pool submit_block: height = 2624413, external blob (5228 bytes)
NOTICE  2022-05-16 02:50:39.3692 SideChain add_external_block: block 295c202c877e60cc468ff2f7365658be4875b3bdaf8a60ac677e1fc00252888c has enough PoW for Monero height 2624262, submitting it
NOTICE  2022-05-16 02:50:39.3693 P2Pool submit_block: height = 2624413, external blob (4730 bytes)
NOTICE  2022-05-16 02:50:40.1298 SideChain add_external_block: block eae60e831cb0800dfee57579cbaf441bdd7495bd6bd1abc5ebc422da0957c794 has enough PoW for Monero height 2624260, submitting it
NOTICE  2022-05-16 02:50:40.1299 P2Pool submit_block: height = 2624413, external blob (4218 bytes)
NOTICE  2022-05-16 02:51:35.3358 SideChain add_external_block: block 2dd69056a0cff8d31445bcacf2fe8be1173b7279dbad9b8593b09f3b8999aafa has enough PoW for Monero height 2624189, submitting it
NOTICE  2022-05-16 02:51:35.3359 P2Pool submit_block: height = 2624413, external blob (5246 bytes)
NOTICE  2022-05-16 02:52:13.0521 SideChain add_external_block: block f3fa3649d97d631fb00fab380cf1205771893c88caa7e73923968fe7efcc2c1c has enough PoW for Monero height 2624127, submitting it
NOTICE  2022-05-16 02:52:13.0521 P2Pool submit_block: height = 2624413, external blob (3065 bytes)
NOTICE  2022-05-16 02:52:17.7160 SideChain add_external_block: block 85e6cd8efe39b01ed0d532b52c605008c20a15c262e7ef246da388d150a7014d has enough PoW for Monero height 2624118, submitting it
NOTICE  2022-05-16 02:52:17.7160 P2Pool submit_block: height = 2624413, external blob (3384 bytes)
NOTICE  2022-05-16 02:52:21.5957 SideChain add_external_block: block e86b0f88c898ab81438decfd270e07244c8bcf462ae5b7b498d6755445c7b275 has enough PoW for Monero height 2624107, submitting it
NOTICE  2022-05-16 02:52:21.5958 P2Pool submit_block: height = 2624413, external blob (3169 bytes)
NOTICE  2022-05-16 02:52:46.4937 SideChain add_external_block: block c19525d420b8e62a21a8c389bc13ea22fe23a4d12ea749626f5fc5612fd2c30a has enough PoW for Monero height 2624070, submitting it
NOTICE  2022-05-16 02:52:46.4938 P2Pool submit_block: height = 2624415, external blob (4339 bytes)
NOTICE  2022-05-16 02:53:10.4900 SideChain add_external_block: block cffccc70056ceb59e2b7bd109a89b21b35b4297713be98b2ac6a8eefcfdd7a8b has enough PoW for Monero height 2624044, submitting it
NOTICE  2022-05-16 02:53:10.4902 P2Pool submit_block: height = 2624415, external blob (8238 bytes)
NOTICE  2022-05-16 05:01:20.8573 SideChain add_external_block: block 0f6820e50c3622e61fbabffb8b467eed1e177cbd56c2416753637ff9c2d5ca29 has enough PoW for Monero network, submitting it
NOTICE  2022-05-16 05:01:20.8614 P2Pool submit_block: height = 2624476, external blob (4009 bytes)
NOTICE  2022-05-16 05:01:24.0521 P2Pool BLOCK FOUND: main chain block at height 2624476 was mined by this p2pool
-----------------------------------------------------------------------------------------------
NOTICE  2022-05-16 05:01:25.4266 P2Pool submit_block: BLOCK ACCEPTED at height 2624476 and difficulty = 324529650944
NOTICE  2022-05-16 05:02:43.5904 SideChain add_external_block: block 4353fb7354c4ea627163ba0a0369b10c0f6caf0a7774dde40813509ca6f36a41 has enough PoW for Monero network, submitting it
NOTICE  2022-05-16 05:02:43.5904 P2Pool submit_block: height = 2624478, external blob (4010 bytes)

```
</details>
