### ISSUE TITLE
p2pool banning localhost

### ISSUE THREAD

**Issue by theaog** [SChernykh/p2pool#148]
`2022-04-28 14:18:11.2377 StratumServer 127.0.0.1 is banned (330 seconds left)`

Could we add a filter to skip banning connections from localhost?

**Comment by theaog** [comment]
By looking at the code I realized a miner has to connect in a 10s window, if it fails to connect p2pool bans it.

For posterity if you're running on slow connections try to use compression and authenticate your miners in the 10s grace period.

**Comment by SChernykh** [comment]
Fixed in https://github.com/SChernykh/p2pool/commit/8f27d940e30e248712385d20aaf2d9746b1bc56a
