### ISSUE TITLE
Number of included transactions in BlockTemplate console log rows seem to be off by one

### ISSUE THREAD

**Issue by orenomfi** [SChernykh/p2pool#149]
I'm not sure if this is a bug or is this just something I don't understand, but it seems that the number of included transactions are off by one in the P2Pool console when I compare to the XMRig console output.

![image](https://user-images.githubusercontent.com/83827131/166142570-5ffbe89c-9b89-449c-8574-e907189c1d9d.png)

Is this normal behavior?

**Comment by SChernykh** [comment]
XMRig shows all transactions, including coinbase (miners reward). P2Pool counts only regular transactions in that log line.
