### ISSUE TITLE
Payout issue

### ISSUE THREAD

**Issue by HotSwapp** [SChernykh/p2pool#15]
I have been running p2pool for a few days now, mining with 20-25khs and i realized I used the pool wallet for this line here. "/p2pool --host 127.0.0.1 --rpc-port 18081 --zmq-port 18083 --wallet YOUR_WALLET_ADDRESS --stratum 0.0.0.0:3333 --p2p 0.0.0.0:37889 --addpeers 65.21.227.114:37889" 

My question is how do you allow other people to mine on your node? I was hoping to this up for my friends and me. I originally put it in the pool wallet but all the funds just went there regardless of XMRIG's wallet.

Anything I should look into?

Thanks!

**Comment by SChernykh** [comment]
Each p2pool node mines to only one wallet that you set in p2pool command line. Your friends need to run their own p2pool nodes, but you all can still use the same Monero node.
