### ISSUE TITLE
Source code archive with submodules

### ISSUE THREAD

**Issue by BigmenPixel0** [SChernykh/p2pool#151]
Can you please post releases with an archive that will already contain all the necessary submodules?

**Comment by SChernykh** [comment]
Source code tarball is included by Github automatically and it can't include submodules: https://github.community/t/create-release-that-contains-submodule/1329

You can however run
```
git clone --recursive https://github.com/SChernykh/p2pool
cd p2pool
git checkout v2.0
git submodule sync
git submodule update --init --force --recursive
```
to get the exact state of the repository at the time of a specific release (replace `v2.0` with the desired release tag name).
