### ISSUE TITLE
stats error @workers 

### ISSUE THREAD

**Issue by tywkah** [SChernykh/p2pool#152]
Hello.
There should be 'KH/s', shouldn't it?
![image](https://user-images.githubusercontent.com/93492811/168446564-88421dd0-c212-4779-905a-bd5e03cafb7e.png)
So there must be whether '22.7 KH/s' (if we count it from the displayed WORKER uptime) or '9KH/s' but certainly not 'MH/s' i think. :]
p.s. A share was found 3 hrs ago. I've compiled from sources:
https://github.com/SChernykh/p2pool/commit/edd782ac235f543f79327fbe69b225389fbcb320
Sorry if it has been fixed already, i'm not a real coder to notice/understand

**Comment by SChernykh** [comment]
It shouldn't show anything there without autodiff, fixed in https://github.com/SChernykh/p2pool/commit/37b6457054f83133e9ecb15f739c7876d515d98f

**Comment by tywkah** [comment]
> It shouldn't show anything there without autodiff, fixed in [37b6457](https://github.com/SChernykh/p2pool/commit/37b6457054f83133e9ecb15f739c7876d515d98f)

Thanks, but could you please change the 'workers' output to only show diff/hashrate if a user ran p2pool without the '--no-autodiff' parameter (strings 471-472, 479-480 https://github.com/SChernykh/p2pool/blob/master/src/stratum_server.cpp#L471 ) ? Otherwise, the output is redundant.
