### ISSUE TITLE
HR stats cannot be reset fully right after sync's completed

### ISSUE THREAD

**Issue by tywkah** [SChernykh/p2pool#154]
![image](https://user-images.githubusercontent.com/93492811/168493841-55c34aec-56e8-4a5e-aada-96d248b7b618.png)
![image](https://user-images.githubusercontent.com/93492811/168498842-5a83ea23-c207-4d45-983d-e343f6b60711.png)

Here are 2 examples of the latest branch. The 2nd one has a new [msg 'P2POOL'S BEEN SYNCED'](https://github.com/SChernykh/p2pool/issues/147#issuecomment-1127075222) and was got by dropping client connections by FW after some shares had been found and stats had been updated (I'll explain why later).
I tried to look into the problem and found that if I add `m_cumulativeHashes = 0;` to the 'void StratumServer::reset_share_counters()' section, the HR stats will indeed be reset fully:
![image](https://user-images.githubusercontent.com/93492811/168499675-d2c680e4-2bac-4e2d-bf37-e9cc52413b94.png)
![image](https://user-images.githubusercontent.com/93492811/168499772-0a8ff7ea-5b6b-4204-98f3-501d277b556d.png)

BUT there may sometimes be another situation that interferes with a normal reset! Look at this screen:
![image](https://user-images.githubusercontent.com/93492811/168500149-7e1d042e-24ca-45ba-b230-d2005a5cd8c2.png)
We can see some "intra-" shares, the new "p2pool sync" message (that must reset all share stats) and... a share that had been found right before the sync message, which was added to the stats later when the real diff had already been too high because of the main chain sync! And another share was also found right after the sync and it even didn't have a client name and ip:port... I think there's a need in extra "low diff check" or something like this...
Total hashes can NOT be reset as I suggested above (compare the hashes sum before and after the sync). And I can't even suppose what to do with the encreased total share counter value!

p.s. I've just got another example (I haven't interfered with my serv now by writin 'status' and so on):
![image](https://user-images.githubusercontent.com/93492811/168502427-804af8c3-a202-4090-b69d-b7318295a8db.png)
Triple number of shares received in one second with the sync message!

**Comment by SChernykh** [comment]
This is 15 minute / 1 hour / 24 hour hashrate estimates, it shouldn't be reset.

**Comment by SChernykh** [comment]
Stale shares are a rare situation. When P2Pool is synchronized, it immediately sends new jobs to miners, so it can only happen if they find a share within 50-100 ms of the network latency. Even then, these shares are just added to the old sidechain with old difficulty, each of them has a chance to mine a Monero block, so it must be processed fully. I don't see it as a bug.

**Comment by tywkah** [comment]
But those stale shares increment a share and total hashes counter that must be reset in normal situation (you added this functional recently)

**Comment by SChernykh** [comment]
> And I wouldn't say it's a rare situation (especially at an old pc like intel atom/nm10 with 4 gb born on 2012...)!

It's a rare situation for such computer to even find a share, let alone find it at the exact time p2pool gets synchronized and resets counters. Anyway, https://github.com/SChernykh/p2pool/commit/8f1f81749d164683e63063679596012bf816ff3c makes sense to do because other hash counters get reset there too.

**Comment by tywkah** [comment]
> It's a rare situation for such computer to even find a share, let alone find it at the exact time p2pool gets synchronized

This pc's not for mining:) It can barely serve monerod+p2pool. Now it takes about 7 min to sync after start with cache after short downtime and even more w/out cache. So it lags during the syns process, ecpecially right after start and before the end of syncing. And I have to cut off miners during the sync using fw+script so that they cant interfere the stats (meanwhile they switch to another pool for that short time of sync).

> [8f1f817](https://github.com/SChernykh/p2pool/commit/8f1f81749d164683e63063679596012bf816ff3c)
thanks!

**Comment by tywkah** [comment]
![image](https://user-images.githubusercontent.com/93492811/168619483-f4185c0f-e3e2-4b0b-aa9a-e4e8f693e718.png)
There're 34 secs between the last by one share '430' and the sync msg (meaning all stats to be reset), but it was counted in the total hashes value with the latest 'Ryzen' hashes too... And of course that one stale 'Ryzen's share incremented total number of found shares in stats. Or it can be just wrong calculation (maybe connected with 'effort' value).
