### ISSUE TITLE
Solo mine setup?

### ISSUE THREAD

**Issue by Jahzwolf** [SChernykh/p2pool#156]
How do other miners connect?  How will the pool know who they are without a wallet address.  As I see the set up I am putting my wallet address in starting up the pool and xmrig it is documented will ignore any address.  So does this mean this configuration is solo just my wallet gets paid if I find a block?

Side note at 85% this download is now crawling like a snail.  Trying to prune the db to resize it.  Hope it helps.  If other nodes are this slow idk 🤷‍♀️ how anyone wins a block

**Comment by SChernykh** [comment]
1 p2pool node = 1 wallet address. If you want to mine to several wallet addresses, run a p2pool node for each of them.

**Comment by Jahzwolf** [comment]
Thank you for your response.  Okay 👌 makes sense.  Nice to see code work well out of the box 📦.  Most code on GIT is old broken and unsupported

**Comment by Jahzwolf** [comment]
Just a note of thanks after a long time learning and frustration this is the first successful solo mine rig I have gotten working because of your excellent support thank Goodness
