### ISSUE TITLE
Allow DNS resolution of `--host` flag

### ISSUE THREAD

**Issue by sethsimmons** [SChernykh/p2pool#16]
In order to simplify setups, it would be *very* nice if we could specify the host via DNS.

Not only does this simplify using your own remote node, it also greatly simplifies any Docker setup as you can simply connect `p2pool` and `monerod` via container name no matter what IP address it gets.

As an example, if `--host` allowed DNS resolution, the following compose file would be all you need to spin up `monerod` and `p2pool` with almost no other configuration:

https://github.com/sethsimmons/p2pool-docker/blob/main/examples/docker-compose.yml

Thanks in advance!

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool/commit/ee7a1e54f7b79257f0e28537992fe5f4cbf8b0d4

**Comment by WeebDataHoarder** [comment]
Testing

**Comment by WeebDataHoarder** [comment]
Confirmed working within and outside a container

**Comment by sethsimmons** [comment]
Will test once my image rebuilds tomorrow via CI.

**Comment by sethsimmons** [comment]
Rebuilt and testing now:

https://github.com/sethsimmons/p2pool-docker/actions/runs/1214725554

**Comment by sethsimmons** [comment]
Tested and works perfectly.

Thanks so much for the quick turnaround!
