### ISSUE TITLE
Executable stack with v2.0

### ISSUE THREAD

**Issue by kpcyrd** [SChernykh/p2pool#160]
The binary distributed by Arch Linux has an executable stack:
```
% checksec --file=/usr/bin/p2pool
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      Canary found      NX disabled   PIE enabled     No RPATH   No RUNPATH   No Symbols	  Yes	6	21		/usr/bin/p2pool
```
The binary distributed in this repo also has an executable stack (and missing a few other harding options too):
```
% checksec --file=p2pool
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Partial RELRO   No canary found   NX disabled   No PIE          No RPATH   No RUNPATH   No Symbols	  No	0	0p2pool
```
`NX disabled` means the stack is executable. I'm not sure what's causing this though.

**Comment by SChernykh** [comment]
I guess it's because the project includes RandomX which has assembly source files. https://github.com/SChernykh/p2pool/commit/97818dd440d63c00f58bd9dc5799b4f623399fd1 should hopefully fix it.

**Comment by SChernykh** [comment]
Fixed in https://github.com/SChernykh/p2pool/commit/bfa8334aeb50da012734b13d4887faba0567d860

**Comment by kpcyrd** [comment]
Cool, thanks!
