### ISSUE TITLE
two machines

### ISSUE THREAD

**Issue by Proulx-S** [SChernykh/p2pool#163]
Hello,
I am trying to mine one linux machine (A) and run monerod and p2pool on another linux machine (B) within the same network. I have seen some questions and comments about that, but I am still confused about were to inputs IPs and Ports.

My best guess is to run the following:
on machine B
`./monerod --zmq-pub tcp://127.0.0.1:18083 --disable-dns-checkpoints --enable-dns-blocklist`
`./p2pool --host 127.0.0.1 --wallet YOUR_WALLET_ADDRESS`
and on machine A
`./xmrig -o 192.168.1.BB:3333`
where 192.168.1.BB is the LAN of machine B.

I thought the xmrig on machine A would reach out to p2pool's stratum server on machine B. Seems like B is listening, as p2pool log says "StratumServer listening on 0.0.0.0:3333". But xmrig initiates, i.e. it runs until
```
* COMMANDS ...
* OPENCL ...
* CUDA ...
```
but then nothing on machine A...

And p2pool on machine B says:
```
StratumServer status
...
Connections = 0 (0 incoming)
```
and
```
P2PServer status
Connections = 10 (o incoming)
...
```

I must be doing something wrong but feel too confused to continue trying everything I find online :-P
Anyone can help?

Thanks in advance!

**Comment by SChernykh** [comment]
`--zmq-pub tcp://127.0.0.1:18083` you need to change it to `--zmq-pub tcp://0.0.0.0:18083` (and open port 18083 in the firewall) so p2pool on the second machine could connect to it.

**Comment by SChernykh** [comment]
Oh, I didn't read properly. So you run both monerod and p2pool on machine B, then your command lines are correct. Double check that port 3333 is open in firewall on machine B.

**Comment by Proulx-S** [comment]
I had my firewall turned off and it was not it

But thanks a lot for the quick confirmation of my commands @SChernykh !

To start fresh, I removed all port forwarding I might have set wrong and rebooted everything, and even reinstalled machine A since I noticed I had some general connectivity issues with it. Don't know what did it but it now works! Thanks!
