### ISSUE TITLE
AutoDiff

### ISSUE THREAD

**Issue by jameswillhoite** [SChernykh/p2pool#165]
Just installed the v2.1 pool and like the AutoDiff feature. Was hoping for this when I first found p2pool. Only issue I have is it starts out at the max diff then slowly comes down. Wouldn't it be better to start out low and increase the diff? I'm running the mini chain, so some of my machines have a diff of around 10000. I have one machine that is at diff of 70000 so I tried to specify a custom diff of 10000 in hopes that it would increase that machine as shares are submitted, but it did not.

**Comment by bladedoyle** [comment]
Note that XMRvsBEAST Bonus Hash Rate Raffle requires a "high" difficulty or it will reject the job and count it as a failure.
Maybe there could be for p2pool to take an initial autodiff value as an option?

**Comment by jameswillhoite** [comment]
That or if we supply a starting diff go from there. I can specify say 70k and the pool can start from that point and adjust up or down.

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool/commit/b267c19a45e4dfc9eb396dd2308f92ceff04b55d should be sufficient for all practical purposes.
