### ISSUE TITLE
Does the minimum payout in readme make sense?

### ISSUE THREAD

**Issue by OlMi1** [SChernykh/p2pool#170]
For instance, my last payment was 0.000267888522 XMR and thereby below the minimum written there, even when applying the maths to the block (2640684). I didn't just want to push a pull request which may contain wrong info, so I am asking first whether the minimum payout makes sense since there does not seem to be one and P2Pool pays all miners once a block is found, no matter their balances.

**Comment by SChernykh** [comment]
Minimum payout is shown as approximate in readme. 0.000267888522 XMR rounds up to 0.0003 XMR. It's the amount p2pool can pay for a single share, there's no "balance" on p2pool.
