### ISSUE TITLE
Hashrate continues to update in mining stats despite no internet connection

### ISSUE THREAD

**Issue by devhyper** [SChernykh/p2pool#171]
Whenever p2pool is disconnected from the internet, the (--local-api) hashrate continues to update, despite there being no cpu activity or network connection.

**Comment by SChernykh** [comment]
I can't reproduce it. In my tests, p2pool keeps mining and mining stats doesn't get updated when there's no Internet. As soon as there is Internet connection again, p2pool recovers successfully, keeps mining and starts updating mining stats.
