### ISSUE TITLE
API to get current share size

### ISSUE THREAD

**Issue by Titaniumtown** [SChernykh/p2pool#177]
I can't seem to find any way for me to get the current share size that p2pool requires. Could this be added?

**Comment by Titaniumtown** [comment]
Never mind, I believe I can use: `/api/shares_in_window`

**Comment by Titaniumtown** [comment]
Nevermind actually, it seems to not work: <https://p2pool.io/mini/api/shares_in_window/1>

**Comment by SChernykh** [comment]
> the current share size that p2pool requires

What exactly do you mean by that? There's no `/api/shares_in_window`

**Comment by Titaniumtown** [comment]
it says there should be on: https://p2pool.observer/api

I think `https://p2pool.observer/api` is seperate from the api provided by p2pool nodes. very confusing.
