### ISSUE TITLE
Shares found stays 0 even when I'm getting payouts

### ISSUE THREAD

**Issue by stmax82** [SChernykh/p2pool#178]
p2pool's `StratumServer status` always displays `Shares found = 0` even though I'm regularly finding shares and getting payouts.

Right now `Your shares position` shows 1 share and I already received 4 payouts during the last 24 hours, yet `Shares found` is 0.

I'm mining within p2pool (not xmrig), version 2.1.

Am I misinterpreting the displayed status values, or is there something wrong?

```
status
2022-06-29 19:16:42.3340 SideChain status
Main chain height         = 2656597
Main chain hashrate       = 2.952 GH/s
Side chain ID             = mini
Side chain height         = 1971047
Side chain hashrate       = 16.412 MH/s
Your hashrate (pool-side) = 7.441 KH/s
PPLNS window              = 2160 blocks (+42 uncles, 0 orphans)
Your shares               = 1 blocks (+0 uncles, 0 orphans)
Your shares position      = [...................1..........]
Block reward share        = 0.045% (0.000272481107 XMR)
2022-06-29 19:16:42.3342 StratumServer status
Hashrate (15m est) = 0 H/s
Hashrate (1h  est) = 0 H/s
Hashrate (24h est) = 0 H/s
Total hashes       = 1250050
Shares found       = 0
Average effort     = 0.000%
Current effort     = 0.762%
Connections        = 0 (0 incoming)
2022-06-29 19:16:42.3342 P2PServer status
Connections    = 10 (0 incoming)
Peer list size = 324
Uptime         = 1d 23h 29m 31s
2022-06-29 19:16:42.3342 Miner status
Threads  = 12
Hashrate = 2.942 KH/s
```

**Comment by SChernykh** [comment]
Shares found is in `StratumServer` section, it counts shares found by connected miners (xmrig).

**Comment by SChernykh** [comment]
Fixed in https://github.com/SChernykh/p2pool/commit/a1d1420ec315a02abe4c27ec02662fcc9baedb86

**Comment by stmax82** [comment]
@SChernykh thanks for the fix. I assumed that p2pool's miner would also talk to the stratum server.
