### ISSUE TITLE
Adding background run option  for headless servers

### ISSUE THREAD

**Issue by ZwaZo22** [SChernykh/p2pool#18]
Hello, 

I propose to add the option like the "--detach" in monerod to run p2pool in background. This is useful for the headless machines to avoid dependency on the ssh session.

Actually, I am using "screen" function to run p2pool in background.

Best regards,

Jef

**Comment by trasherdk** [comment]
I'm running anything monero in screen sessions :laughing: 
```sh
$ screen -ls
There are screens on:
        15945.monero-lws-testnet        (Detached)
        4323.feewallet-stagenet (Detached)
        4220.poolwallet-stagenet        (Detached)
        15777.monerod-stagenet  (Detached)
        17154.monero-lws-stagenet       (Detached)
        15877.monerod-testnet   (Detached)
        4651.pool-stagenet      (Detached)
```

**Comment by github12101** [comment]
> Hello,
> 
> I propose to add the option like the "--detach" in monerod to run p2pool in background. This is useful for the headless machines to avoid dependency on the ssh session.
> 
> Actually, I am using "screen" function to run p2pool in background.
> 
> Best regards,
> 
> Jef

screen is totally adequate. I don't believe there is a need to spend time builting headless interface, when screen solves everything.

**Comment by ZwaZo22** [comment]
no problem. I close the point.

Best regards,
