### ISSUE TITLE
Only open stratum server when p2pool is finished synchronizing 

### ISSUE THREAD

**Issue by Titaniumtown** [SChernykh/p2pool#185]
I've run into a reoccurring issue where if I restart my p2pool node and miners were previously connected, they would connect before the p2pool node was fully synchronized. This causes fake shares to be generated and report as submitted (idk how, it doesn't show up in p2pool observer). These "fake shares" continue to be created even after p2pool reports as synchronized, the only solution is to make sure all miners are off, then turning on p2pool, waiting for everything to synchronize, then starting all the miners. Ideally the stratum server shouldn't even be open until this synchronization was completed.

**Comment by SChernykh** [comment]
These are not fake shares, they're real shares but on a separate p2pool chain. P2Pool starts mining its own sidechain before it's synchronized with other nodes, and each of these shares is real and can potentially mine Monero block.

**Comment by Titaniumtown** [comment]
They rapidly start appearing, seconds within eachother.... Usually it takes me an hour to get a share.

**Comment by SChernykh** [comment]
Because new sidechain starts with difficulty 100000, but it quickly adjusts. You can just ignore all these shares, but you should know that they're real and have a chance to mine Monero block.

**Comment by Titaniumtown** [comment]
Oh ok. Well thanks for the good explanation! I guess my worries have been solved lol.

**Comment by SChernykh** [comment]
> These "fake shares" continue to be created even after p2pool reports as synchronized

Continue for how long? If only for a few seconds then it's just network latency.

**Comment by Titaniumtown** [comment]
It was a few seconds, I stopped it before it could continue. I can test in the morning if you wish.
