### ISSUE TITLE
cpu load

### ISSUE THREAD

**Issue by moneroguides** [SChernykh/p2pool#188]
Recently updated to 2.2. 

Over time, this version seem to be much more demanding on the cpu, utilising 100% of one core consistently.

No special flags are used except --stratum-api and --data-api

**Comment by SChernykh** [comment]
This is fixed in https://github.com/SChernykh/p2pool/commit/a7da7f932cd231886294dafa503502071b194cbe 
v2.2.1 release will come out tomorrow.

**Comment by moneroguides** [comment]
:) nice

**Comment by sama11y** [comment]
89HjYShqqcV3Z7NMZrzods8Bmqm13S3n3jQBNvodNRLs97wYoNFJ11T9RByoYPRnhD9egKF5NeHJMUC8fDN7S35o6sMT58G
