### ISSUE TITLE
README.md : information consistency

### ISSUE THREAD

**Issue by ZwaZo22** [SChernykh/p2pool#19]
in the "How to test" section of the file, it is stated : 

> Check that ports **18080** (Monero p2p port) and 37889 (p2pool p2p port) are open in your firewall to ensure better connectivity

later in the code example :

> Run ./monerod --zmq-pub tcp://127.0.0.1:**18083** don't forget --zmq-pub parameter in the command line

I propose to align the port numbers on the same value.

Best regards,

**Comment by SChernykh** [comment]
These are different ports (18080 = Monero p2p, 18083 = ZMQ-pub port) and they don't need to be open if you run everything on the same machine.

**Comment by ZwaZo22** [comment]
Ok. Thanks for the information and sorry for the noise !

Best regards
