### ISSUE TITLE
P2Pool fatal error: couldn't download block headers for heights

### ISSUE THREAD

**Issue by CompKingCanada** [SChernykh/p2pool#194]
My Blockchain is on an SMB share.  Using v2.2 this works fine.  Ever since 2.2.1 was released p2pool is giving the above error on any resume of the process with pre-existing p2pool cache.

If I purge the cache, it runs fine after re-creating.

Running on a Windows PC

**Comment by SChernykh** [comment]
p2pool cache has nothing to do with this error, as well as changes in v2.2.1. This error happens even before p2pool tries to access the cache. Please add `--loglevel 4` to the command line and provide the full p2pool log from start until you get this error. My guess is your blockchain SMB connection is not stable, it's not a recommended setup for monerod.

**Comment by SChernykh** [comment]
> <+selsta> sech1: from what I remember having the blockchain on SMB share is not supported

Nothing I can do here, you have to run blockchain locally.
