### ISSUE TITLE
nix run doesn't work out of the box

### ISSUE THREAD

**Issue by MarusDod** [SChernykh/p2pool#196]
adding the curl library on buildInputs seemed to fix it for me. 

also changing the command to
`nix run git+https://github.com/SChernykh/p2pool?ref=master&submodules=1`

**Comment by SChernykh** [comment]
Added the fixes you mentioned: https://github.com/SChernykh/p2pool/commit/85abbdd69932fcff5886da4f06776aacd595c5f1
