### ISSUE TITLE
Add webhook for specific events

### ISSUE THREAD

**Issue by Titaniumtown** [SChernykh/p2pool#197]
It would be cool if a feature to push to webhooks when shares or blocks are discovered, this would be cool to monitor a p2pool node's status on another platform such as discord

**Comment by SChernykh** [comment]
There's also `--data-api path/to/folder` command line parameter that enables saving some p2pool status into json files in specified folder.

**Comment by jameswillhoite** [comment]
This is something I've worked on, I've got it working for Linux Computers, but haven't had a chance to test and modify for windows computers. You can take a look at https://github.com/jameswillhoite/p2pool.git on branch "share_found". I have hooks which you can run on share found, and on block found. I want to eventually get it merged into p2pool master, but just don't have the time to modify for windows computers right now.
