### ISSUE TITLE
Feature Request: IP Whitelist

### ISSUE THREAD

**Issue by gnif** [SChernykh/p2pool#201]
Currently if there is a communications error or a miner submits an invalid PoW the p2pool service bans the host for 5 minutes. It would be useful to be able to provide a whitelist of IPs that are never banned for miners that are a little bit unstable (recycled hardware) or communication faults.

**Comment by SChernykh** [comment]
You are talking about stratum server bans, right?

**Comment by SChernykh** [comment]
With the current code, only 127.0.0.1 is whitelisted, so you can run xmrig-proxy and p2pool on the same host and connect your miners to the proxy. Stratum server will only see 127.0.0.1 and will not ban it.

**Comment by gnif** [comment]
> You are talking about stratum server bans, right?

Yes

> With the current code, only 127.0.0.1 is whitelisted, so you can run xmrig-proxy and p2pool on the same host and connect your miners to the proxy. Stratum server will only see 127.0.0.1 and will not ban it.

Yes, this is a workaround but adding an extra application to work around such a basic limitation seems like using a sledgehammer to put in a nail.

**Comment by SChernykh** [comment]
I will rewrite the stratum server's ban logic in the next version. It shouldn't ban after the first invalid share, it's the ratio of invalid to valid and the frequency of invalid shares that should trigger a ban.

**Comment by Giando** [comment]
Due to the lack of this feature, many valid shares continue to be discarded, always for the 5 minute blacklisting even of friendly IPs that cannot be whitelisted.

<img width="435" height="372" alt="Image" src="https://github.com/user-attachments/assets/b782e5bd-ab92-43b0-9b60-88a793223834" />

**Comment by SChernykh** [comment]
That mining rig is really unstable, you should reduce overclocks and/or fix overheating. It does submit too many invalid shares, so it gets banned rightfully.

**Comment by Giando** [comment]
Yes, it's a cloud server (so it already does a lot) but all those rejected shares are caused by the 5 minute ban... :'(

**Comment by SChernykh** [comment]
You could add `--stratum-ban-time 1` to P2Pool's command line to reduce the ban to 1 second, but you really should fix that machine.
