### ISSUE TITLE
GLIBC_2.33

### ISSUE THREAD

**Issue by Masterbob79** [SChernykh/p2pool#204]
hello I am using bullseye on a rock64. I am getting this error after upgrade. any idea how to fix it?

./p2pool: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./p2pool)
./p2pool: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./p2pool)
./p2pool: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./p2pool)

**Comment by SChernykh** [comment]
It's probably because I used Ubuntu 22 to compile p2pool v2.3 for aarch64. You can use the previous release for now, or you can compile it yourself - it's not hard.

**Comment by Masterbob79** [comment]
thank you. I will work on it this weekend

**Comment by SChernykh** [comment]
This should be fixed in https://github.com/SChernykh/p2pool/releases/tag/v2.4

**Comment by Masterbob79** [comment]
thank you, but i compiled it. your right it was easy
