### ISSUE TITLE
[BUG] cant compile p2pool in termux

### ISSUE THREAD

**Issue by fislysandi** [SChernykh/p2pool#207]
basically i wanna mine some moneronies on my phone. since my phone is pretty much doing nothing piling dust so i thought to mine some XMR

i copy pasted the command 
everything works untill make -j$(nproc) and it fails 

Phone:Xiaomi redmi note 9
Android: 11
MIUI:12.5.5

screenshots
![Screenshot_2022-10-06-19-32-30-517_com termux](https://user-images.githubusercontent.com/45166203/194368850-667be863-2ba8-4d28-8024-3869dc46b370.jpg)
![Screenshot_2022-10-06-19-31-37-254_com termux](https://user-images.githubusercontent.com/45166203/194368862-28e7d15e-1b84-492a-9e46-e56cd04becda.jpg)
![Screenshot_2022-10-06-19-31-44-006_com termux](https://user-images.githubusercontent.com/45166203/194368882-9c691276-fc5e-4452-86ec-cedf595358c8.jpg)
![Screenshot_2022-10-06-19-31-52-656_com termux](https://user-images.githubusercontent.com/45166203/194368918-559829eb-243e-46e6-a549-434c23c702d8.jpg)
![Screenshot_2022-10-06-19-31-58-362_com termux](https://user-images.githubusercontent.com/45166203/194368944-417ce1fe-dd35-4444-ba25-70b928c399f5.jpg)
![Screenshot_2022-10-06-19-32-13-493_com termux](https://user-images.githubusercontent.com/45166203/194368997-e6e3a036-5e74-4b2b-b643-de32f2dd490f.jpg)
![Screenshot_2022-10-06-19-32-18-186_com termux](https://user-images.githubusercontent.com/45166203/194369032-ecb7268f-7459-4594-841b-c8448d2215a9.jpg)
![Screenshot_2022-10-06-19-32-07-403_com termux](https://user-images.githubusercontent.com/45166203/194368972-149b6973-813c-4368-b416-ab9f247df444.jpg)ng

**Comment by SChernykh** [comment]
It compiles and works fine in my Termux. It's some issue with your compiler and/or cmake because cmake shouldn't give errors. What do `gcc --version`, `clang --version` and `cmake --version` commands say?

Also note that Termux is not maintained in Google Play store, you have to install it from F-Droid for it to work properly.

**Comment by fislysandi** [comment]
i downloaded termux from fdroid forgot to mention.

**Comment by fislysandi** [comment]
![Screenshot_2022-10-06-21-26-39-667_com termux](https://user-images.githubusercontent.com/45166203/194390810-f1b884c5-f6e5-4000-9d5d-224f63e03e92.jpg)

**Comment by fislysandi** [comment]
i made a syncthing thing that when i screenshot i have specific folder where it automatically syncs my screenshots to a pc. usefull.

**Comment by fislysandi** [comment]
full path to my cloned repo /com.termux/files/home/storage/shared/monero_mine/p2pool/build

maybe its related to file permissions?

ill try to build it inside of the termux home dir

**Comment by fislysandi** [comment]
ok it seems like its related to file locations. i got 5 % further in the compilation process

![Screenshot_2022-10-06-21-53-14-198_com termux](https://user-images.githubusercontent.com/45166203/194396418-7a6183f7-eec4-49cb-8a7e-23ab315e0ba6.jpg)
![Screenshot_2022-10-06-21-53-22-522_com termux](https://user-images.githubusercontent.com/45166203/194396464-496f35be-128c-4c89-a8ad-bd48c1f082d1.jpg)
![Screenshot_2022-10-06-21-53-29-694_com termux](https://user-images.githubusercontent.com/45166203/194396500-afe17229-bb4e-45ca-8537-845d99de8c76.jpg)
![Screenshot_2022-10-06-21-53-34-594_com termux](https://user-images.githubusercontent.com/45166203/194396523-d9d7005f-48ee-4c37-9952-377de06e8564.jpg)

try to compile p2p outside of termux filesystem  and on your phone see if you can reproduce the issue

**Comment by fislysandi** [comment]
oh. well what do i do now where can grab already compiled binaries then?

**Comment by fislysandi** [comment]
well if thats so ill try to do the same with a factory settings temrux then then ill try again.

**Comment by fislysandi** [comment]
NNNOPE still doesnt work. even after factory resettting termux settings its still stuck at 69% of compilation.

**Comment by fislysandi** [comment]
untill this is fixed ill run p2pool in proot then and probably take a hash-rate performance decrease. since its not your priority and this will probably will never be fixed.

**Comment by SChernykh** [comment]
@fislysandi https://github.com/SChernykh/p2pool/commit/b9a9be27953c40262dec6f188c9ec38c2b7b9985 should fix this error.
