### ISSUE TITLE
Memory usage is way higher than expected with --no-randomx

### ISSUE THREAD

**Issue by icsterm** [SChernykh/p2pool#208]
I run p2pool on a 256MB RAM VPS and the statement that this thing uses less than 100MB is not true:

root        1027  1.9 14.3 **199828** 32912 pts/1    Sl+  15:38   0:46 ./p2pool --host 10.7.0.2 --zmq-port 18084 --rpc-port 18081 --wallet xxx - --loglevel 1 --no-randomx --no-cache --light-mode

root        1092  6.6 37.1 **411428** 85044 pts/2    Sl+  15:39   2:31 ./p2pool --host 10.7.0.2 --zmq-port 18084 --rpc-port 18081 --wallet xxx --loglevel 1 --no-randomx --no-cache --light-mode --mini

The first process is without any workers, the second is with 2 workers, the usage is 200MB+ bare minimum (400MB with 2 workers).
Any workarounds to make it use less than 100MB?
I run my own monerod node (18.0) and p2pool is latest version precompiled from github releases page (2.4), the VPS is running Debian 10 with kernel 5.10.

**Comment by SChernykh** [comment]
Try to compile the latest code, I submitted a few changelists that reduce memory usage. It's currently using 70 MB for main and 150 MB for mini on my server. Mini takes more because each block is larger there (more miner payouts per block).

**Comment by icsterm** [comment]
I will consider this as solved, since this was just an observation, I can handle the mem usage until the next prebuilt goes live.
