### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by dota-immortals** [SChernykh/p2pool#21]
I keep seeing this error after a block is found, is this something to be concerned about?
```
P2Pool submit_block: daemon returned error: 'unknown error', template id = 0, nonce = 0, extra_nonce = 0
status
```

**Comment by SChernykh** [comment]
This happens when your p2pool node tries to submit Monero block found by some other node. It's done to speed up block propagation, but it's not always possible and Monero node can give errors. I've changed it to a warning in the latest code.
