### ISSUE TITLE
How to make decentralized p2pool a top 1 mining pool? An open letter and proposal

### ISSUE THREAD

**Issue by minexmr2** [SChernykh/p2pool#211]
Hi Monero community!

This is an open letter to all the participants want to make Monero ecosystem strong and pleasant.

I am open source developer known for many years at bitcointalk.org as florida.haunted.
First time I remember I was discussing there is in year 2011.
Mainly I was arguing about Bitcoin disadvantages, and searching for a currency much more perfect.

I found that currency. Monero.
Fungible, untraceable, tiny fees, adaptive block size, tail emission, ASIC-resistant, decentralized p2pool mining.

I have decided to dedicate my small developing efforts to Monero community.
Particularly, I thought on p2pool and its practical application problems a lot.

Indeed, p2pool is fully implemented and working in production for more than ONE year.
But its total hashrate is still under 199MH/s most of the time.

And we all remember the history with epic MineXMR.com pool and its departure few months ago.
MineXMR.com was an old-school centralized pool that was occupying nearly 51% of total Monero network hashrate.
There were a lot of discussions on reddit how danger was that situation for Monero network security.

So, MineXMR.com has departed. And, it is important, MineXMR.com did recommend for all the miners to migrate to decentralized p2pool.
I thought at least half of MineXMR.com hashrate should be switched to p2pool, thus increasing its hashrate up to some 500MH/s.

But almost nothing happens! Look at miningpoolstats.stream/monero every single day.
What figure do you observe?

* Top 3 pools are CENTRALIZED and occupying some 70% of total network hashrate.
* Decentralized p2pool (with mini) is occupying just 7% of total network hashrate.
* Most time nanopool.org is top 1. We all have questions to nanopool.org, right?

The community have to accept the truth:
to build, update and maintain their OWN p2pool instance is NOT an ease task for MOST Monero miners.
And it is nearly impossible to deploy their own p2pool instance for all the newbies.
Then, what is a typical enter step for a newbie? Yes, to join 1 of top 3 centralized mining pools!

Looking at that sad figure, I have implemented, deployed and maintain brand new MineXMR2.com pool.

MineXMR2.com is not related to the departed MineXMR.com pool in any way. And I am completely separated person from MineXMR.com owner.
I called the pool MineXMR2.com, because I was inspired of old-school fashion of MineXMR.com pool for a long time,
and digit "2" also hints to decentralized p2pool inside MineXMR2.com pool.

Below there are features and benefits of MineXMR2.com pool I could formulate in a nutshell.

* MineXMR2.com is the first 100% OPEN SOURCE Monero mining pool using decentralized p2pool as a hashrate-liquidity provider.
All the hashrate of your miners is being redirected completely to an "embedded" p2pool instance.
Thus, if MineXMR2.com occupies 51% of network hashrate, it means actually, decentralized p2pool does occupy 51% of network hashrate.

* MineXMR2.com remains an old-school Monero pool: no registration (even email), no spying cookies, no personal data collection.
Once you find few shares, your XMR address is registered in internal database (lmdb) and is getting paid automatically.

* MineXMR2.com has its own billing system. You don't need to find a share on p2pool or a block on the network to get paid by MineXMR2.com.
The pool is recording your shares separately, thus even a miner with small hashrate
can see how his pending balance is being updated each time the whole decentralized p2pool with its typical 150MH/s hashrate finds a new block.
That happens few times per hour, statistically.

* Payment threshold is as low as 0.01XMR. In worst case scenario, you can't lose more than 0.01XMR with MineXMR2.com pool.
And of course you can email to support minexmr2@tutanota.com to get paid manually.

* MineXMR2.com completely eliminates "dust" payments (~0.0003XMR) from p2pool that typically occur for miners with small hashrate.
You always receive 0.01XMR chunks. Unlike paid with "dust" from p2pool, when you spend your mined XMR,
you obtain typical tiny Monero transaction fees (~0.00005XMR), not huge transaction fees form "dust" payments.

Exciting? There is one question: how to prove MineXMR2.com is actually running OPEN SOURCE code it claims?
There are some approaches:

1. You can monitor stratum protocol output from MineXMR2.com and compare it with output from your local p2pool instance.
2. When MineXMR2.com hashrate reaches some 15-30MH/s or more, you can plot correlation charts of MineXMR2.com hashrate against official p2pool hashrate.
3. With your aid, I can implement deterministic build practices for source code from reproducible-builds.org.

No one of that approaches is perfect, but combining them, we can reach a good level of proof MineXMR2.com is indeed running open source.
And remember, no other centralized pool offers such a possibility to his users.

Hereby I ask the community to support MineXMR2.com pool. I may create a CCS proposal,
or simply, if MineXMR2.com hashrate reaches some 100MH/s or more, it will be an "auto-proposal" for me.

I plan to implement many useful features for miners:

* Graphical hashrate charts per miner's XMR address.
* Graphical hashrate chart for the whole MineXMR2.com pool, p2pool and network.
* E-mail notifications on whether particular miner rig is online or offline.
* Any feature of your desire; feel free to create GitHub/GitLab issue:
https://github.com/minexmr2/minexmr2/issues
https://gitlab.com/minexmr/minexmr2/-/issues

Sincerely yours,
florida.haunted@gmail.com.
https://bitcointalk.org/index.php?topic=5416452.new#new

**Comment by SChernykh** [comment]
This is a bug tracker, it's an offtopic here.
