### ISSUE TITLE
Could I run monero docker without any node?

### ISSUE THREAD

**Issue by cmdntd** [SChernykh/p2pool#212]
I see instruction at https://hub.docker.com/r/sethsimmons/p2pool
I'd like to run with:
```
docker run -d --name="p2pool" -p 3333:3333 -p 37889:37889 -v p2pool-data:/home/p2pool -v /dev/hugepages:/dev/hugepages:rw sethsimmons/p2pool:latest --host 5.9.120.18 --rpc-port 18089 --wallet my_wallet_id --stratum 0.0.0.0:3333 --p2p 0.0.0.0:37889 --addpeers 65.21.227.114:37889,node.sethforprivacy.com:37889
```

A node of monero needs much storage. Could I run docker above without any node? (with the same like above)
How long I could see the first payout in my wallet?

**Comment by SChernykh** [comment]
You must have a node somewhere to connect to it. You can try nodes from https://xmrvsbeast.com/p2pool/monero_nodes.html - replace `--host 5.9.120.18 --rpc-port 18089` with `--host IP --rpc-port A --zmq-port B` where IP, A, B are taken from that page. If you don't have much hashrate, also add `--mini` to the command line to mine on P2Pool mini. Then you'll get payouts in the first week of mining.

**Comment by cmdntd** [comment]
Thank you.

I have enough CPU/GPU server. But I do not have enough storage. I read instruction for own node with 175GB or 75GB. So I want to try to use node from https://xmrvsbeast.com/p2pool/monero_nodes.html for saving storage.

Could you compare payout when using xmrvsbeast/own node, and full/mini hashrate please?

**Comment by SChernykh** [comment]
Payout depends only on your hashrate, but you'll get more frequent payouts on mini if you have small hashrate. Also, this is a bug tracker, not a support channel. Ask such questions on IRC #p2pool-log (#p2pool-mini for P2Pool mini) on https://libera.chat/
