### ISSUE TITLE
Add mouse scroll support

### ISSUE THREAD

**Issue by icsterm** [SChernykh/p2pool#216]
Looks like the mouse scroll is not implemented at all. This works fine with xmrig and monerod, but not in p2pool.
Can we have this improvement in further builds?

**Comment by SChernykh** [comment]
Mouse scroll? P2Pool is a simple console application, it doesn't mess with things like this.

**Comment by icsterm** [comment]
Well, scrolling with the physical scroll button works in monerod and xmrig, just p2pool has this way of display out.
Any chance to make it happen in a further build?

**Comment by SChernykh** [comment]
I don't understand what you're talking about. Mouse scroll works fine for me in all 3 of these programs.

**Comment by icsterm** [comment]
For me, using the mouse scroll wheel does nothing, i have to click the scroll bar and move it see the previous output logs.
<img width="1057" alt="p2pool" src="https://user-images.githubusercontent.com/8934957/200177491-52390935-c1a7-4d21-bbaf-a5d0fc4a64e7.PNG">
I run the app from a bat file:

p2pool.exe --host 127.0.0.1 --zmq-port 18084 --rpc-port 18081 --wallet xxx --stratum 0.0.0.0:31337 --loglevel 1 --no-randomx --no-cache --light-mode --mini
pause

Its weird, the same problem when ssh-ing into a Debian box, scroll wheel doesn't work there as well, so it's not shell related.

**Comment by SChernykh** [comment]
> Mouse scroll? P2Pool is a simple console application, it doesn't mess with things like this.

I was wrong, it does. Fixed in https://github.com/SChernykh/p2pool/commit/1fa6a7c11aac5cade2c18308ace395ac62157ad4
