### ISSUE TITLE
Automatic PPLNS window length

### ISSUE THREAD

**Issue by duggavo** [SChernykh/p2pool#221]
P2Pool usually finds many Monero blocks in its PPLNS window. This means that one share often gets paid out many times with small transactions. This greatly increases chain bloat.
Implementing an automatic PPLNS window so that in average 1 or 2 blocks are found per window would both reduce the Monero blockchain growth and increase the profit for P2Pool miners.

**Comment by SChernykh** [comment]
This is a good proposal, but it will require a hardfork on P2Pool side so it can't be implemented quickly. I will also look into how to solve the issue I mentioned on IRC:

>  Monero blockchain state is not a part of p2pool sidechain data, so not a part of consensus. Different peers can see different Monero difficulty to calculate PPLNS window size and it can lead to p2pool sidechain splits
