### ISSUE TITLE
p2pool sends job to stratum miner when not synced

### ISSUE THREAD

**Issue by duggavo** [SChernykh/p2pool#231]
P2pool sends mining job to the stratum miner(s) when syncing.
This can cause a waste of electricity and also slow down syncing if the miner is running on the same device of the p2pool node.

**Comment by SChernykh** [comment]
This is the intended behavior. P2Pool is a decentralized network and it doesn't know if what it's syncing will be valid in the end, so it starts building its own blockchain right away. Everything that you're mining while syncing does count and it's the same as solo mining until you sync with other peers.
