### ISSUE TITLE
Using multiple remote nodes

### ISSUE THREAD

**Issue by OlMi1** [SChernykh/p2pool#232]
I found this list with compatible remote nodes: https://xmrvsbeast.com/p2pool/monero_nodes.html. However, I would like to add a backup node in case the one I use goes offline. Is that possible? I'm starting P2Pool using `./p2pool --mini --host p2pmd.xmrvsbeast.com --rpc-port 18081 --zmq-port 18084 --wallet <Address>`
Thanks!

**Comment by SChernykh** [comment]
It's not supported yet.

**Comment by SChernykh** [comment]
The support is now added in https://github.com/SChernykh/p2pool/commit/b5fa34e1a195b7dad0075370bb12c1be480a6c6b and will be available in P2Pool v3.5
