### ISSUE TITLE
Is it possible to direct the leased power of the RandomX (XMR), as example to MRR, to p2pool ?

### ISSUE THREAD

**Issue by Paul1804** [SChernykh/p2pool#234]
Is it possible to direct the leased power of the RandomX (XMR), as example to MRR, to p2pool ? Will it work?

**Comment by SChernykh** [comment]
It worked last time I checked.

**Comment by Paul1804** [comment]
I will check in the near future ...

**Comment by Paul1804** [comment]
I want to calculate the yield of mining on p2pool Tell me where to get statistics on the average time of the block p2pool? For the last 10 days, 30 days .... Tell me what is the size of the reward for the block Monero?

**Comment by Paul1804** [comment]
I want to count at what price/MH/day  it is profitable to rent power.

**Comment by SChernykh** [comment]
Your profitability depends only on:
- your hashrate
- network hashrate
- block reward
- Monero price
- how you spend on your hashrate

Time to find a block doesn't matter, for any pool. It all averages out after long enough time. There are many Monero calculators you can find in Google.

Also, this is not an actual P2Pool issue, rather an offtopic here.

**Comment by Paul1804** [comment]
Thank you so much for the answers.)
