### ISSUE TITLE
Disable log colors

### ISSUE THREAD

**Issue by OlMi1** [SChernykh/p2pool#235]
The log is colored with no option known to me to turn it off. Due to the lack of an API / data saving system developers wanting to work with P2Pool need to decode the console. However the color data makes this incredibly difficult, as lines look like this:
`[0;36m2023-02-15 15:22:58.3739[0m [0;90mConsoleCommands [0mevent loop started[0m`
It is really hard to work with this. Is there any way to turn it off?

I am mostly interested in reading the reward amount and times as well as hashrates. Basically everything that's printed when a P2Pool block is found and whats printed when entering "status".

**Comment by SChernykh** [comment]
Did you read https://github.com/SChernykh/p2pool/blob/master/docs/COMMAND_LINE.MD ?

**Comment by OlMi1** [comment]
> Did you read https://github.com/SChernykh/p2pool/blob/master/docs/COMMAND_LINE.MD

I did not know this existed and kept searching in the issues... sorry for opening the issue, should have looked through the repo. Thanks for your help!

**Comment by OlMi1** [comment]
One more question though, does this data include data about the last reward? Doesn't seem to, however I am unsure if I could calculate this just based on the `pool/blocks` file.

**Comment by SChernykh** [comment]
`p2pool.log` has everything in it - limited to the log level you set, of course.

**Comment by OlMi1** [comment]
Would be great to have it in the local stats though. Thanks a lot for the help! The payout notifications are propably included in log level one, right?

**Comment by SChernykh** [comment]
Payout messages are log level 0.

**Comment by OlMi1** [comment]
Thanks a lot! Googling it didn't yield a clear result.
