### ISSUE TITLE
Compatible with a nicehash?

### ISSUE THREAD

**Issue by Paul1804** [SChernykh/p2pool#236]
Compatible with a nicehash? I want to direct power to the p2pool....

**Comment by SChernykh** [comment]
It should be compatible. You need to make your stratum IP:port to be available from outside, check your firewall settings.

**Comment by Paul1804** [comment]
How can I put the difficulty on the p2pool? They (NiceHash)  recommend meaning >= 262144.00

**Comment by SChernykh** [comment]
It's on the main page:
```
To set a custom fixed difficulty for your miner (for example, 10000), instead start XMRig with the following options:
xmrig.exe -u x+10000 -o 127.0.0.1:3333
```
But even with default settings, p2pool will give tasks with difficulty 4,000,000 at first, and then auto-adjust difficulty to 30 seconds per share.

**Comment by Paul1804** [comment]
Do you think it is possible to do without it in the case of a NiceHash?

**Comment by Paul1804** [comment]
I check my p2pool through NiceHash instruments 

![image](https://user-images.githubusercontent.com/40546987/220171969-ffb3dd03-5fb1-4c23-a6a6-5b6d6d00f68d.png)

**Comment by Paul1804** [comment]
......please comment on

**Comment by SChernykh** [comment]
It used to work, maybe they changed something. The screenshot doesn't show what was the error.

**Comment by SChernykh** [comment]
It works for me:
![Untitled](https://user-images.githubusercontent.com/15806605/220177498-60c12d3f-9685-4235-bc8e-836161e9afbe.png)

What command line do you use for your p2pool instance?

**Comment by Paul1804** [comment]
this command....

./p2pool  --loglevel 1 --no-randomx  --in-peers 10 --no-autodiff --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888

**Comment by SChernykh** [comment]
`--no-autodiff` is not compatible with Nicehash or MRR. They don't understand 8-byte difficulty format, but XMRig does, this is why XMRig works. Autodiff limits the difficulty to 4,000,000 and uses only 4-byte format. Difficulty above that requires better precision (8 bytes), and default p2pool difficulty with `--no-autodiff` is way higher than 4,000,000.

**Comment by Paul1804** [comment]
I'll try this..
`./p2pool  --loglevel 1 --no-randomx  --in-peers 10 --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888`
... and it's better

![image](https://user-images.githubusercontent.com/40546987/220289997-5f6363ee-4445-45b0-8bbf-ba64855a2437.png)

**Comment by SChernykh** [comment]
Difficulty 100000 means your p2pool node is not synchronized. First make sure it's working correctly, then test on Nicehash.

**Comment by Paul1804** [comment]
is it synhronized ?

![image](https://user-images.githubusercontent.com/40546987/220296120-099bc414-5385-47eb-9ce8-fd51c088db05.png)

**Comment by SChernykh** [comment]
It's not synchronized. Check for warnings and errors in p2pool.log. Also, "background jobs running" should usually be empty. If you check status a few times and you see something there every time, it's not working correctly.

**Comment by Paul1804** [comment]
is start ok ?

![image](https://user-images.githubusercontent.com/40546987/220306604-6d85f5d2-167c-4048-bdbf-ae30343da69a.png)

**Comment by Paul1804** [comment]
I do `--loglevel 4` and I see.. What you say about it ?
![image](https://user-images.githubusercontent.com/40546987/220311530-5f5aec50-d427-4297-9f4a-c96584af2b0a.png)
![image](https://user-images.githubusercontent.com/40546987/220311883-033aaf06-b416-4a2a-adc4-7d55cd58a548.png)

**Comment by SChernykh** [comment]
These warnings can be ignored. What's the ping to your node (10.0.0.2)? You use `--no-randomx`, so p2pool has to ask node to calculate RandomX hashes each time, and it adds ping time to each `add_external_block`. If you want faster sync, remove `--no-randomx`.

**Comment by Paul1804** [comment]
10.0.0.2 it is the monerod on old computer (i686, 32 bit). His config file is..
```
zmq-pub=tcp://0.0.0.0:18083
rpc-bind-ip=0.0.0.0
rpc-restricted-bind-ip=0.0.0.0
confirm-external-bind=1
log-level=0
disable-dns-checkpoints=1 
enable-dns-blocklist=1
prune-blockchain=1
sync-pruned-blocks=1
block-sync-size=15
```
I use this command line...
`./p2pool  --loglevel 1 --light-mode  --in-peers 10 --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888`


Now, all is -oK
![image](https://user-images.githubusercontent.com/40546987/220337597-4cf81e0a-4659-4b01-9433-7fdc348339b0.png)
....and this...
![image](https://user-images.githubusercontent.com/40546987/220337883-79456936-92c2-4b37-a029-876c631b8a1a.png)
