### ISSUE TITLE
Why is the address for taking Monero on NiceHash (nicex.com) considered invalid on p2pool?

### ISSUE THREAD

**Issue by Paul1804** [SChernykh/p2pool#240]
Why is the address for taking Monero on NiceHash (nicex.com) considered invalid on p2pool?
And how can I fixed it ?
This address 8Aev2Us3tsb3xALQXW6fy2d92UHz9X3ZRAwg845pornp7f7GE6fFmx5FkiCoWxwknzYbTkyoPHdTsfq3G6p2SerCUYa1bZQ

**Comment by SChernykh** [comment]
Read the README: https://github.com/SChernykh/p2pool#general-considerations

**Comment by Paul1804** [comment]
I understand. They used Subaddresses and integrated addresses ?

**Comment by SChernykh** [comment]
If you want to send Monero to Nicehash (???), you can send it from your miner wallet that starts with 4...
They use subaddresses (one per user) to know who sent them XMR. Mining only allows (for technical reasons) standard addresses that start with 4...

**Comment by Paul1804** [comment]
I want to rent miners from them.

**Comment by Paul1804** [comment]
I want to try to buy power from them and return there, and buy again.

**Comment by Paul1804** [comment]
I understand. For p2pool I'll  must use another wallet ?
