### ISSUE TITLE
No shares since updated to 3.1 from 2.6! I had ~20 shares per day! More users having the same issue!

### ISSUE THREAD

**Issue by FeatureSpitter** [SChernykh/p2pool#241]
Read more here: https://www.reddit.com/r/MoneroMining/comments/10ram4w/no_shares_in_24_hours_since_updating_p2pool_to_v3/

**Comment by SChernykh** [comment]
Did you read my comment there?

> If you believe it's something with v3.0, please switch back, set log level to 4 and watch for any warnings/errors, also keep track that you have the same sidechain height as what p2pool observer shows, and that you have connected peers in status. I need to hunt down all remaining bugs until v3.1 release.
But 99% chance that it was just bad luck. There are hundreds of miners on p2pool and statistically a few of them are having bad luck right when a new version is released, and then posts like this appear.

**Comment by SChernykh** [comment]
I can't help if you just say "nothing works" without providing full logs. What does `status` command say for you?

**Comment by SChernykh** [comment]
Also, more than 80% of miners already updated and I don't see similar issues reported.

**Comment by SChernykh** [comment]
It turned out `--mini` was lost in the command line during the update: https://www.reddit.com/r/MoneroMining/comments/11pc6gu/comment/jbxupyq/?utm_source=reddit&utm_medium=web2x&context=3
