### ISSUE TITLE
add Gentoo for build instructions in README

### ISSUE THREAD

**Issue by BreadTom** [SChernykh/p2pool#242]
Similar to these:

### Gentoo

Enable the [GURU](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_End_Users) repository, then emerge net-p2p/p2pool:

`sudo emerge —ask net-p2p/p2pool`

**Comment by SChernykh** [comment]
It's already at https://wiki.gentoo.org/wiki/Monero#P2Pool which is the first link on "gentoo p2pool" Google search. Not sure if it's really needed in the README because it looks like a standard way to install software for Gentoo.

**Comment by BreadTom** [comment]
Ok, thank you for the response.
