### ISSUE TITLE
Strange behavior with p2pool.observer

### ISSUE THREAD

**Issue by footcow** [SChernykh/p2pool#244]
Hi,

I use p2pool since many months without any trouble and I follow things with p2pool.observer web site everyday with a page open inside my browser. But since this week I get this message from the site: 

`No shares have been reported to the P2Pool network in the past for this miner.`

The URL is still the same, I have tried just to copy / paste again my wallet in the form, but I still have this result instead of the usual tracking of miner statistics.

Any idea about this situation ?

Thanks for you help per advance.
Hervé

**Comment by SChernykh** [comment]
Did you update to p2pool v3.0 or v3.1, or are you still running an older version?
https://github.com/SChernykh/p2pool#p2pool-hardfork-on-march-18-2023

**Comment by footcow** [comment]
Yes I'm using those release since they were published:
- p2pool-v3.1-macos-x64
- monero-mac-x64-v0.18.2.0

And during the last year I get good result on this interface as I said, so why now it says that no shares have been done ever ?

**Comment by SChernykh** [comment]
P2Pool observer is not run by me, it's a 3rd-party project. DataHoarder is rewriting it now, so it might be missing some data. You should run `status` command in P2Pool and post the result here, I'll check if it's fine.

**Comment by footcow** [comment]
```
2023-03-24 06:32:37.6626 SideChain status
Monero node               = 127.0.0.1:18081:ZMQ:18083
Main chain height         = 2848774
Main chain hashrate       = 2.377 GH/s
Side chain ID             = default
Side chain height         = 4714391
Side chain hashrate       = 202.129 MH/s
PPLNS window              = 309 blocks (+14 uncles, 0 orphans)
PPLNS window duration     = 0h 52m 52s
Your wallet address       = MY_WALLET
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
2023-03-24 06:32:37.6627 StratumServer status
Hashrate (15m est) = 8.586 KH/s
Hashrate (1h  est) = 9.438 KH/s
Hashrate (24h est) = 9.160 KH/s
Total hashes       = 9747694950
Shares found       = 3
Average effort     = 25.634%
Current effort     = 349.400%
Connections        = 7 (7 incoming)
2023-03-24 06:32:37.6627 P2PServer status
Connections    = 10 (0 incoming)
Peer list size = 289
Uptime         = 12d 16h 20m 44s
2023-03-24 06:32:37.6627 Util no background jobs running

```

**Comment by SChernykh** [comment]
I don't see any issue here. You've found 3 shares so far in this run, you're just unlucky at this moment - effort 349.4%. But you're mining on the correct updated chain and your're connected to other peers. 350% effort happens sometimes, it's not impossible. You should switch to p2pool-minin with only 9 kh/s, if you want to get shares and payouts more often.

**Comment by footcow** [comment]
OK moved to --mini param ... for the moment I have the same message on https://mini.p2pool.observer for the moment.

Thanks for your help, will see.
