### ISSUE TITLE
Hashrate losses between Nicehash and p2pool. What settings should be applied to the p2pool ?

### ISSUE THREAD

**Issue by Paul1804** [SChernykh/p2pool#245]
I have about 5% on the NiceHash statistic. 
What settings should be applied to the p2pool to reduce losses between the nicehash and p2pool?
My command line for p2pool...
`./p2pool  --loglevel 1 --light-mode  --in-peers 10 --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888`

**Comment by SChernykh** [comment]
> I have about 5% on the NiceHash statistic.

Can you show the screenshot? Because I don't understand what "5%" you're talking about. Please also show the output of `status` command in P2Pool.

**Comment by Paul1804** [comment]
![image](https://user-images.githubusercontent.com/40546987/227764110-15fc2652-e43b-4650-9cf3-64b19d61e8d2.png)


![image](https://user-images.githubusercontent.com/40546987/227764064-f59899e7-550f-43b7-b703-fe0c8a42b736.png)

**Comment by SChernykh** [comment]
This is delta between "Speed at pool" and "Speed paying". I don't know how exactly it's calculated, but it can be because of luck factor (peers found 5% less shares than expected at this hashrate and difficulty). You also have 1 rejected shares, you should check P2Pool logs for warnings and errors to find this share and why it was rejected. Search P2Pool logs for `INVALID SHARE`.

**Comment by Paul1804** [comment]
INVALID SHARE -pattern not found in p2pool.log file . But I understood everything. Thank's.

**Comment by SChernykh** [comment]
Ahh, I forgot [this commit](https://github.com/SChernykh/p2pool/commit/02a0cb174ac9484f7342c604c0532a563b8f68ad) is not released yet. Then you can also grep your logs for any WARNING or ERROR lines and see if anything sticks out.

**Comment by Paul1804** [comment]
I find somethings. What about  this ?
`WARNING 2023-03-22 05:21:18.1813 P2Pool invalid transaction: tx id = eb361c42e50a19224154df85a5560cc596378d376575efdc964845250238eaa2, size = 0, weight = 0, fee = 160.400 um
WARNING 2023-03-22 05:21:18.1814 P2Pool invalid transaction: tx id = 362964a7bd698374ea0f3e45d367786ccf52fd187a488aa19590a4926b7100a4, size = 0, weight = 0, fee = 160.400 um
WARNING 2023-03-22 05:21:18.1814 P2Pool invalid transaction: tx id = 354265abc9308215a766c686e5cd71418947bbca5ac84e50ec51df25087a9856, size = 0, weight = 0, fee = 158.600 um`

...and this...
`ERROR   2023-03-23 10:56:53.1648 StratumServer failed to get IP address of the client connection, error ENOTCONN
ERROR   2023-03-25 21:08:09.1852 P2Pool submit_block: daemon returned error: 'Block not accepted', template id = 22546, nonce = 3305177219, extra_nonce = 1391076012, id = e7dfa1f3cba2195b1f5d1da66136529d2d9871dd1ef55eea33e1ffd35e87e7ed
`

**Comment by SChernykh** [comment]
> invalid transaction

This transaction is just ignored by P2Pool, it shouldn't affect hashrate

> StratumServer failed to get IP address of the client connection

One of your NiceHash miners tried to connect to P2Pool, but failed to connect.

> daemon returned error: 'Block not accepted'

This is normal, it happens all the time when other miners in P2Pool find their blocks and your node can't submit it because it doesn't have some of their transactions in its own mempool.

**Comment by Paul1804** [comment]
I want to try to miningrigrentals.com take the power for rent.  Will the NiceHash settings for p2pool suit?
`./p2pool  --loglevel 1 --light-mode  --in-peers 10 --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888`

**Comment by SChernykh** [comment]
You can set user name to `x+4000000` in MRR configuration (user name is where the wallet address usually goes). This will fix the difficutly to 4000000. Or you can just run MRR rig as is, because P2Pool has autodiff that starts from 4000000 and then adjusts.

**Comment by Paul1804** [comment]
I will rent power there. I have p2pool + monerod . I don’t need to do anything because a p2pool with autodiff. This is true ?

**Comment by SChernykh** [comment]
> I don’t need to do anything because a p2pool with autodiff.

Yes.

**Comment by Paul1804** [comment]
Thank you!

**Comment by xmrvsbeast** [comment]
> I have about 5% on the NiceHash statistic. What settings should be applied to the p2pool to reduce losses between the nicehash and p2pool? My command line for p2pool... `./p2pool --loglevel 1 --light-mode --in-peers 10 --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888`

you will not be able to get any better than -5% delta on NH, they penalize you for sending new work to their miners too often, since p2pool has 10s blocks it sends out new work very often

**Comment by xmrvsbeast** [comment]
> I will rent power there. I have p2pool + monerod . I don’t need to do anything because a p2pool with autodiff. This is true ?

The high hash rigs on MRR are just reselling Nicehash, you can tell which ones by using the "live" filter.  NH resellers are not mining until you rent the rig, then it starts.  Regular rigs have active hashrate historically.

To rent the NH reseller rigs you will most likely need to send it through xmrig-proxy for it to work.  The normal rigs should work straight to p2pool.

**Comment by SChernykh** [comment]
> To rent the NH reseller rigs you will most likely need to send it through xmrig-proxy for it to work.

@xmrvsbeast why is that? Is P2Pool's stratum incompatible?

**Comment by Paul1804** [comment]
> > I have about 5% on the NiceHash statistic. What settings should be applied to the p2pool to reduce losses between the nicehash and p2pool? My command line for p2pool... `./p2pool --loglevel 1 --light-mode --in-peers 10 --host 10.0.0.2 --wallet 47YmJAymcRB69jLsaexS2hFGJe4QKzBLuX47Gj3fKuSa999sJ4bb5f5XEV7yAHJKbs1toqAYHhGUp2CAmf7QsQnAM9FT3Rf --stratum 0.0.0.0:3334 --p2p 0.0.0.0:37888`
> 
> you will not be able to get any better than -5% delta on NH, they penalize you for sending new work to their miners too often, since p2pool has 10s blocks it sends out new work very often

You are right. This is true. How to overcome this? This is solved as that?

**Comment by Paul1804** [comment]
> 
I compared MRR vs NiceHash. The Nicehash is cheaper. Is it only visibility?

> > I will rent power there. I have p2pool + monerod . I don’t need to do anything because a p2pool with autodiff. This is true ?
> 
> The high hash rigs on MRR are just reselling Nicehash, you can tell which ones by using the "live" filter. NH resellers are not mining until you rent the rig, then it starts. Regular rigs have active hashrate historically.
> 
> To rent the NH reseller rigs you will most likely need to send it through xmrig-proxy for it to work. The normal rigs should work straight to p2pool.

**Comment by xmrvsbeast** [comment]
> > To rent the NH reseller rigs you will most likely need to send it through xmrig-proxy for it to work.
> 
> @xmrvsbeast why is that? Is P2Pool's stratum incompatible?

I think so, you have to use xmrig-proxy in simplemode for it to work, nicehash mode does not work on MRR or nicehash itself.

**Comment by xmrvsbeast** [comment]
> You are right. This is true. How to overcome this? This is solved as that? tryed use xmrig-proxy for NH ?

I do not think there is a way to overcome it.  NH is expecting jobs for randomx ~1-2min intervals but p2pool is sending jobs at ~10s.  They see it as a malfunction pool and assume you are lowering the efficiency of their miners since you are paying per valid share hashed.

**Comment by xmrvsbeast** [comment]
> Interesting. But all major pools increased job frequency, so does NH punish them too?

Good questions, I have not tried NH -> reg. pool so I am not sure.  I would guess so, but I do not know what NH considers too fast.  Maybe they are OK with 30s but not 10s, or they are using some algo.

**Comment by Paul1804** [comment]
> > Interesting. But all major pools increased job frequency, so does NH punish them too?
> 
> Good questions, I have not tried NH -> reg. pool so I am not sure. I would guess so, but I do not know what NH considers too fast. Maybe they are OK with 30s but not 10s, or they are using some algo.

I do this in order of experiment. But how to do this in the settings p2pool?

**Comment by SChernykh** [comment]
Job update frequency? It's not a setting, it's defined by P2Pool network consensus (10 seconds block time).

**Comment by Paul1804** [comment]
It's clear
