### ISSUE TITLE
API change - `stats` -> `stratum`

### ISSUE THREAD

**Issue by hinto-janai** [SChernykh/p2pool#247]
[`2e6041d`](https://github.com/SChernykh/p2pool/commit/2e6041dcf5d5fc54182634dc31d68445a3225dd6#diff-4a082cd983adf68c4a2d7297cc57897a3ef9b4c3a1fe7f342957d8196ccc24d7R1312)

This will turn `local/stats` into `local/stratum`?

**Comment by SChernykh** [comment]
Yes, because `stats` was rather generic name. I'm adding more stuff to api now, there will be more changes (but hopefully no more renaming).

**Comment by hinto-janai** [comment]
If other renames are needed, might as well do them all now. Is there an ETA for next release?

**Comment by SChernykh** [comment]
All changes will be done before v3.2 release, which is in the end of the month as usual.

**Comment by SChernykh** [comment]
@hinto-janai This is now released
