### ISSUE TITLE
docker-compose file's statistics web UI seems to be looking for a file that doesn't exist

### ISSUE THREAD

**Issue by Void-0000** [SChernykh/p2pool#252]
All it ever shows is:
`[Errno 2] No such file or directory: '/data/local/stats' (Maybe you need to wait a few minutes for p2pool to start and sync for the first time?)`
But it's been running for awhile now so I don't think that's the problem. Looking into `/var/lib/docker/volumes/p2pool-mini/_data/` (the directory of the volume the statistics container seems to have mounted as "/data/") shows that /data/local/ only contains two files: "p2p" and "stratum", no "stats".

Is this a bug or do I have something set up wrong?

**Comment by SChernykh** [comment]
I submitted a fix here: https://github.com/SChernykh/p2pool/commit/80352f6b303e210c902d38487dceb2dda7fce4ed

**Comment by Void-0000** [comment]
Thanks, looks like it works now!

**Comment by hubgitbb** [comment]
i have the same problem too
[Errno 2] No such file or directory: '/data/local/stats' (Maybe you need to wait a few minutes for p2pool to start and sync for the first time?) 
seems that the fix doesent work for me.
