### ISSUE TITLE
cant connect with windows monero gui to wallet

### ISSUE THREAD

**Issue by hubgitbb** [SChernykh/p2pool#254]
Hi, 
i have build the p2pool with Docker Compose https://github.com/SChernykh/p2pool/tree/master/docker-compose.
Now im trying to connect with the windows monero-gui-v0.18.2.2 to the p2pool-monero container, which i think is also the monero wallet, but the monero gui doesent connect. is it possible to connect with that GUI or do i need another GUI?

**Comment by SChernykh** [comment]
What exactly are you trying to connect to? GUI wallet to Monero node running inside the container?

**Comment by SChernykh** [comment]
You need to add port 18081 for Monero: https://github.com/SChernykh/p2pool/blob/master/docker-compose/docker-compose.yml#L87

**Comment by hubgitbb** [comment]
my docker file section for monero looks like this

`monero:
    image: monero:latest
    build:
      context: monero
      args:
        - MONERO_GIT_TAG=latest
    container_name: p2pool-monero
    networks:
      - p2pool
    ports:
      - 18080:18080/tcp
      - 18081:18081/tcp

    volumes:
      - monero:/home/monero/.bitmonero:rw
      - /dev/null:/home/monero/.bitmonero/bitmonero.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    restart: unless-stopped
    command: >-
      --zmq-pub tcp://0.0.0.0:18083
      --disable-dns-checkpoints
      --enable-dns-blocklist
      --out-peers 32
      --in-peers 16
      --add-priority-node=nodes.hashvault.pro:18080
      --add-priority-node=node.supportxmr.com:18080
      --non-interactive
      --p2p-bind-ip=0.0.0.0
      --p2p-bind-port=18080
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=18081
      --restricted-rpc
      --confirm-external-bind
      --log-level=0
      --prune-blockchain
      --fast-block-sync=0
`

**Comment by hubgitbb** [comment]
i mean yes, i have added - 18081:18081/tcp to the docker compose file

**Comment by SChernykh** [comment]
Then you should be able to connect to it, you just need to set the correct IP address in GUI config. Also, this issue is not directly related to p2pool.

**Comment by hubgitbb** [comment]
i have changed the volume settings and tried to read the logs but the bitmonero.log file remains empty
`
- /mnt/sdb1/monero/.bitmonero:/home/monero/.bitmonero:rw
- /mnt/sdb1/monero/.bitmonero/bitmonero.log:/home/monero/.bitmonero/bitmonero.log:rw
`

**Comment by hubgitbb** [comment]
now it works. i think it was a problem mit the version monero-gui-v0.17.3.1.
the version monero-gui-v0.18.2.2   works for me
