### ISSUE TITLE
Newest build does not work as systemd service anymore

### ISSUE THREAD

**Issue by lexo-mfleuti** [SChernykh/p2pool#255]
I just built the p2pool binary from the latest sources and now when I start it through systemctl as a service it does not start anymore. Error:
```
NOTICE  2023-04-19 16:47:57.4643 ConsoleCommands listening on 127.0.0.1:54374
NOTICE  2023-04-19 16:47:57.4646 ConsoleCommands uv_guess_handle returned 17
ERROR   2023-04-19 16:47:57.4646 ConsoleCommands tty or named pipe is not available
NOTICE  2023-04-19 16:47:57.4647 ConsoleCommands event loop started
ERROR   2023-04-19 16:47:57.4647 ConsoleCommands TCP wasn't shutdown properly
```
I can start p2pool on the TTY console normally. I was trying to find a parameter to tell p2pool to not use the TTY and could not find any. Also I tried to configure the service to use a socket like this:

p2pool.service

```
[Unit]
Description=P2Pool Full Node
After=network.target p2pool.socket
Requires=monerod.service
BindsTo=p2pool.socket

[Service]
StandardInput=socket
Sockets=p2pool.socket

WorkingDirectory=/opt/p2pool/build/
Type=simple
Restart=always
ExecStartPre=sysctl vm.nr_hugepages=3072
ExecStart=/opt/p2pool/build/p2pool --loglevel 4 --host 127.0.0.1 --wallet ABCD
```

[Install]
WantedBy=multi-user.target

p2pool.socket

```
[Unit]
Description=P2Pool Socket

[Socket]
ListenStream=/tmp/p2pool.stdin
NoDelay=true

[Install]
WantedBy=sockets.target
```

**Comment by SChernykh** [comment]
`uv_guess_handle returned 17` is `UV_FILE` - you probably created `/tmp/p2pool.stdin` not as a FIFO, but as a regular file.

**Comment by lexo-mfleuti** [comment]
> `uv_guess_handle returned 17` is `UV_FILE` - you probably created `/tmp/p2pool.stdin` not as a FIFO, but as a regular file.

Thank you very much @SChernykh for your very quick reply. It's actually a FIFO file. As a test I recreated it in /opt/p2pool.fifo and changed the service to auto-create the file if it does not exist:

p2pool.service
```
[Unit]
Description=P2Pool Full Node
After=network.target p2pool.socket
Requires=monerod.service
BindsTo=p2pool.socket

[Service]
WorkingDirectory=/opt/p2pool/build/
Type=simple
Restart=always
ExecStartPre=/bin/bash -c '[[ -p /opt/p2pool.fifo ]] || mkfifo /opt/p2pool.fifo; exit 0'
ExecStartPre=sysctl vm.nr_hugepages=3072
ExecStart=/opt/p2pool/build/p2pool --loglevel 4 --host 127.0.0.1 --wallet ABCD

[Install]
WantedBy=multi-user.target
```

Still, same error :(
```
NOTICE  2023-04-19 17:30:06.7174 ConsoleCommands listening on 127.0.0.1:54623
NOTICE  2023-04-19 17:30:06.7177 ConsoleCommands uv_guess_handle returned 17
ERROR   2023-04-19 17:30:06.7177 ConsoleCommands tty or named pipe is not available
NOTICE  2023-04-19 17:30:06.7177 ConsoleCommands event loop started
ERROR   2023-04-19 17:30:06.7177 ConsoleCommands TCP wasn't shutdown properly
```

**Comment by SChernykh** [comment]
Well, https://github.com/SChernykh/p2pool/issues/237 has `ListenFIFO` instead of `ListenStream` in your config.

**Comment by lexo-mfleuti** [comment]
Thank you. Sorry for the confusion. I did set it to `ListenFIFO` and that did not work and then I checked some configs and thus tried `ListenStream` instead. I am getting the very same error when setting `ListenFIFO`:
```
NOTICE  2023-04-19 17:59:01.9627 ConsoleCommands listening on 127.0.0.1:57904
NOTICE  2023-04-19 17:59:01.9630 ConsoleCommands uv_guess_handle returned 17
ERROR   2023-04-19 17:59:01.9630 ConsoleCommands tty or named pipe is not available
NOTICE  2023-04-19 17:59:01.9630 ConsoleCommands event loop started
ERROR   2023-04-19 17:59:01.9631 ConsoleCommands TCP wasn't shutdown properly
```

It would also be OK for me, if there was a parameter to make P2Pool work like it was before (2 days ago). Currently it just only works on console and I cannot run it in the background as a service.

**Comment by SChernykh** [comment]
What was the latest commit that works with your current config?

**Comment by lexo-mfleuti** [comment]
This one: https://github.com/SChernykh/p2pool/tree/80352f6b303e210c902d38487dceb2dda7fce4ed
I skipped the one from 17.04.2023 and updated today again. Ever since it's not working anymore.

**Comment by SChernykh** [comment]
Can you try to build from that commit again to confirm it's not something with your system?

**Comment by lexo-mfleuti** [comment]
With this commit it works: https://github.com/SChernykh/p2pool/tree/ce192670a3620fdad376c5a24cb9ec8df7b33ca1
With this it starts to break: https://github.com/SChernykh/p2pool/tree/196b27f3b21bcf8096ecee1e3b7d089ded1fa30f

**Comment by SChernykh** [comment]
Can you try the latest commit? I don't know why it broke, the functionality in ce192670a3620fdad376c5a24cb9ec8df7b33ca1 shouldn't interfere.

**Comment by lexo-mfleuti** [comment]
OK, with this latest commit it works again: 7a83fd2f30762df502331b2c99bcf69a9662fa43

With the socket function enabled, I am getting now millions of log entries like this though:
```
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands List of commands
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands help                            display list of commands
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands status                          display p2pool status
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands loglevel            <level>     set log level
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands addpeers            <peeraddr>  add peer
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands droppeers                       disconnect all peers
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands peers                           show all peers
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands workers                         show all connected workers
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands bans                            show all banned IPs
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands outpeers            <N>         set maximum number of outgoing connections
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands inpeers             <N>         set maximum number of incoming connections
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands start_mining        <threads>   start mining
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands stop_mining                     stop mining
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands exit                            terminate p2pool
WARNING 2023-04-19 19:16:06.1996 ConsoleCommands Unknown command 2023-04-19 19:16:06.1947 ConsoleCommands Unknown command 2023-04-19 19:16:06.1927 ConsoleCommands stop_mining                     stop mining
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands List of commands
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands help                            display list of commands
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands status                          display p2pool status
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands loglevel            <level>     set log level
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands addpeers            <peeraddr>  add peer
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands droppeers                       disconnect all peers
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands peers                           show all peers
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands workers                         show all connected workers
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands bans                            show all banned IPs
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands outpeers            <N>         set maximum number of outgoing connections
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands inpeers             <N>         set maximum number of incoming connections
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands start_mining        <threads>   start mining
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands stop_mining                     stop mining
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands exit                            terminate p2pool
WARNING 2023-04-19 19:16:06.1996 ConsoleCommands Unknown command 2023-04-19 19:16:06.1948 ConsoleCommands Unknown command 2023-04-19 19:16:06.1927 ConsoleCommands exit                            terminate p2pool
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands List of commands
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands help                            display list of commands
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands status                          display p2pool status
NOTICE  2023-04-19 19:16:06.1996 ConsoleCommands loglevel            <level>     set log level
```

**Comment by SChernykh** [comment]
> I cannot make FIFO work. But, it's not that important to me. Would be nice though.

Something is still broken, because `uv_guess_handle` returns `UV_NAMED_PIPE` early at startup, but then it changes to `UV_FILE`. So it's almost like something inside p2pool changes stdin handle from the original pipe to something else in the latest code.

**Comment by SChernykh** [comment]
I cannot reproduce `uv_guess_handle returned 17` on an Ubuntu 20.04 VM with the latest code. `ListenStream` works for me.

**Comment by SChernykh** [comment]
Yes, this FIFO issue happens even with the older code. But `ListenStream` works correctly.

**Comment by SChernykh** [comment]
Judging by the log, it gets into infinite loop where each line in p2pool console output gets interpreted as a command.

**Comment by SnAFKe** [comment]
> Yes, this FIFO issue happens even with the older code. But `ListenStream` works correctly.

Maybe because of this? https://github.com/SChernykh/p2pool/pull/238

How ListenStream make to work? i not understand, when i do `echo "status" > /tmp/p2pool.stdin` return me 

`/tmp/p2pool.stdin : No such device or address`

**Comment by SChernykh** [comment]
Yes, I have the same issue. It must be ListenFIFO to work correctly, but something else is missing in service or socket configs. @twlee79 can you help?

**Comment by twlee79** [comment]
I've built from source from commit 5f18eed and it seems to run fine as a service on my system, using a named pipe on Arch Linux, with the console control by writing to the named pipe (e.g. `echo status` to get status written to log).

The above issues appear to be related to the console being flooded by something writing to the pipe, or perhaps using an existing file as the pipe. The file should not already exist - the socket in charge of creating and destroying it. I have not tested other configuration options for running as a service with the current build.

My configuration (removing some lines that should be non-essential) is: 
`p2pool.socket`
```
# FIFO socket for controlling p2pool daemon
[Unit]
Description=Command FIFO for p2pool daemon

[Socket]
ListenFIFO=/run/p2pool/p2pool.control
DirectoryMode=0755
SocketMode=0666
SocketUser=p2pool
SocketGroup=p2pool
RemoveOnStop=true
```

`p2pool.service`
```
[Unit]
Description=p2pool daemon
After=network-online.target systemd-modules-load.service monerod.service
Wants=network-online.target systemd-modules-load.service monerod.service
Requires=p2pool.socket

[Service]
Type=exec
Sockets=p2pool.socket
StandardInput=socket
StandardOutput=journal
StandardError=journal

ExecStop=/usr/local/bin/p2pool_stop.sh
TimeoutStopSec=60

# Run as p2pool:p2pool
User=p2pool
Group=p2pool

WorkingDirectory=/var/lib/p2pool

[Install]
WantedBy=multi-user.target
```

`/usr/local/bin/p2pool.sh` simply invokes the `p2pool` executable with my chosen command-line options. 

`p2pool_stop.sh` writes `exit` to the named pipe then waits for the process to terminate:
```

#!/bin/bash
#
# Script to exit p2pool
# Used by p2pool.service

# Issue exit command and then wait for process exit, or script timeout
echo "exit" > /run/p2pool/p2pool.control
while kill -0 "${MAINPID}" 2> /dev/null; do
  sleep 1s
done
```

**Comment by SnAFKe** [comment]
Can you share your p2pool.sh?

Not sure why complicate so much for to many configurations and bash script to run a simple service.

Anyways for me in the end always stuck with the same error with millions of log entries in log file not change anything.

**Comment by twlee79** [comment]
The bash script has my wallet ID and RPC login credentials, so my logic of starting this using a script is to keep these parameters separate from the service config. There is no reason why you can't put these in the service config in that's what you prefer.  Here it is:
`2023-01-31_1617_p2pool.sh`
```
/usr/local/bin/p2pool/p2pool --wallet <redacted>  --host <redacted> --rpc-port <redacted> --rpc-login <redacted> --zmq-<redacted> --stratum <redacted>
```
As I said, it invokes the p2pool executable, nothing more.

The reason for using a bash script to stop the service is also clear from above; it issues `exit` to the console to stop `p2pool`, as per normal usage when operating from the CLI.

**Comment by twlee79** [comment]
The flooding issue you in your comment


. Something must be writing
You should be able to test the named pipe config using a simple set up such

> You need remove Type=simple but lead to another error if you have enable logs will flood you unlimited and create in about 6gb per minute.
> 
> Can you check [SChernykh](https://github.com/SChernykh) this when log is enable? give me this error
> 
> ```
> WARNING 2023-04-18 21:15:47.6701 ConsoleCommands Unknown command 2023-04-18 21:15:47.6700
> WARNING 2023-04-18 21:15:47.6701 ConsoleCommands Unknown command 2023-04-18 21:15:47.6701
> WARNING 2023-04-18 21:15:47.6701 ConsoleCommands Unknown command 2023-04-18 21:15:44.9665 Log started
> WARNING 2023-04-18 21:15:47.6701 ConsoleCommands Unknown command 2023-04-18 21:15:44.9692 P2Pool v3.2 (built with GCC/10.2.1 on Apr 12 2023)
> WARNING 2023-04-18 21:15:47.6701 ConsoleCommands Unknown command 2023-04-18 21:15:44.9703 SideChain network type  = mainnet
> WARNING 2023-04-18 21:15:47.6701 ConsoleCommands Unknown command 2023-04-18 21:15:44.9705 SideChain using default config
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:44.9707 SideChain pool name     = default
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:44.9707 SideChain block time    = 10 seconds
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:44.9707 SideChain min diff      = 100000
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:44.9707 SideChain PPLNS window  = 2160 blocks
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:44.9707 SideChain uncle penalty = 20%
> ......
> ......
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:45.1936 ConsoleCommands uv_guess_handle returned 7
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:45.1936 ConsoleCommands processing stdin as UV_NAMED_PIPE
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command 2023-04-18 21:15:45.1937 ConsoleCommands event loop started
> WARNING 2023-04-18 21:15:47.6702 ConsoleCommands Unknown command ---------------------------------------------------------------------------------------------------------------
> WARNING 2023-04-18 21:15:47.6703 ConsoleCommands Unknown command median_weight           = 300000
> ```

This flooding is because your log output is somehow being directed to your named pipe. Are you sure you aren't directing the stdout to the named pipe in you configuration? Otherwise, there must be some bug someone doing this under certain circumstances. It definitely isn't occurring in my system.

**Comment by SnAFKe** [comment]
> ```
> #!/bin/bash
> /usr/local/bin/p2pool/p2pool --wallet <redacted>  --host <redacted> --rpc-port <redacted> --rpc-login <redacted> --zmq-port <redacted> --stratum <redacted>
> ```

I guess, I already knew that you didn't have the logs enabled, that's why you didn't notice that **important error**

**Comment by twlee79** [comment]
What do you mean by "didn't have logs enabled"? Logs are enabled by default. The default loglevel is 3. My service configuration has these redirected to systemd journal. The `p2pool.log` file is also produced in the working directory and I can issue commands to the console via the named pipe such as: `echo -e "status\nworkers" > /var/run/p2pool/p2pool.control; sleep 1; tail /var/lib/p2pool/p2pool.log -n 40`

**Comment by twlee79** [comment]
To add, I believe the systemd default for `StandardOutput` and `StandardError` is `inherit`, which inherits the file descriptor in `StandardInput`, so it is essential that `StandardOutput` and `StandardOutput` are change in the service config (e.g. 
`StandardOutput=journal` and `StandardError=journal` as per my config).

**Comment by SChernykh** [comment]
> The above configurations posted by other users do not have a setting for StandardOutput and StandardError in the service config, presumably defaulting to inherit and causing the infinite loop where all output is redirected to the named pipe and interpreted as new console commands.

Yes, this is exactly what happened when I tested it, I didn't set StandardOutput and StandardError in service config. That explains it.

**Comment by SChernykh** [comment]
> p2pool_stop.sh writes exit to the named pipe then waits for the process to terminate:

@twlee79 This shouldn't be necessary, p2pool handles SIGKILL, SIGINT, SIGTERM and SIGBREAK signals and exits gracefully, so you only need to set a timeout.

**Comment by SnAFKe** [comment]
I don't like journal that is why i discard this option. I only enable this time for pure testing and worked.

Now use my previous config (not twlee79) and only enable StandardError=journal because i'm special now is working, not script and put directly p2pool commands in ExecStart that is. As explain SChernykh not need script for stop services p2pool do the job.

I'm not sure if correct way to assign StandardError for avoid infinite loop in the log but i least i'm fine with it, if you can find a fix for that would be nice though.

**Comment by SChernykh** [comment]
So you didn't add `StandardOutput=journal` and it still worked, with only `StandardError=journal`?

**Comment by twlee79** [comment]
> @twlee79 This shouldn't be necessary, p2pool handles SIGKILL, SIGINT, SIGTERM and SIGBREAK signals and exits gracefully, so you only need to set a timeout.

@SChernykh I assumed this was probably the case (that it would exit properly anyway) but I based the configuration on standard template for controlling a console service by a named pipe, which exits the program via a console command.

@SnAFKe You don't have to use the  journal, there are plenty of other systemd options you could use, but I would advise making sure you don't use the same named pipe as `StandardInput` for either `StandardOutput` or `StandardError` because that to me is an obvious systemd configuration error that could easily break something in the future (such a systemd configuration is by itself creating a loop).

**Comment by SnAFKe** [comment]
> So you didn't add `StandardOutput=journal` and it still worked, with only `StandardError=journal`? With `ListenFIFO` in config?

Yes, i only need to add StandardError=journal

> @SnAFKe You don't have to use the journal, there are plenty of other systemd options you could use, but I would advise not using the same named pipe as `StandardInput` for `StandardOutput` or `StandardError` (whether explicitly or implicitly by not specifying an option) because that to me is an obvious systemd configuration error that could easily break something in the future (such a systemd configuration is by itself creating a loop).

I'm not Systemd user so i don't have much knowledge, are you saying i only need to use one of them or what is the best config to use systemd service in p2pool without using journal?

**Comment by SChernykh** [comment]
@lexo-mfleuti @SnAFKe @twlee79 I've submitted https://github.com/SChernykh/p2pool/commit/44d2005ab1b1dd290d7d81d1bf7a8680ddf9a832 because the issue wasn't there. Latest code should still work with the proper service config.

**Comment by lexo-mfleuti** [comment]
@SChernykh Thank you very much! It works now with the latest commit. Also when I enable the FIFO socket there's no more millions of entries in the log if I redirect all output to Journal - which is not what I want. 

Despite the service starting up OK and seem to work normally with FIFO socket enabled, the command `echo "status" > /tmp/p2pool.stdin` does not work. It just stalls and does nothing. I will disable that again but it would be nice if it worked. Executing the status command once in a while would give some valuable information.

My current configs:

### p2pool.service

```
[Unit]
Description=P2Pool Full Node
After=network.target p2pool.socket
Requires=monerod.service
BindsTo=p2pool.socket

[Service]
StandardInput=socket
Sockets=p2pool.socket
WorkingDirectory=/opt/p2pool/build/
Type=simple
Restart=always
ExecStartPre=/bin/bash -c '[[ -p /tmp/p2pool.stdin ]] && rm /tmp/p2pool.stdin; mkfifo /tmp/p2pool.stdin; exit 0'                ### recreate the FIFO file on every start
ExecStartPre=sysctl vm.nr_hugepages=3072
ExecStart=/opt/p2pool/build/p2pool --loglevel 4 --host 127.0.0.1 --wallet ABC
TimeoutStopSec=60
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
```

### p2pool.socket

```
[Unit]
Description=P2Pool Socket

[Socket]
ListenFIFO=/tmp/p2pool.stdin
NoDelay=true  ### I also tried without this parameter, same issue
RemoveOnStop=true

[Install]
WantedBy=sockets.target
```

**Comment by twlee79** [comment]
> I'm not Systemd user so i don't have much knowledge, are you saying i only need to use one of them or what is the best config to use systemd service in p2pool without using journal?

Based on this [systemd manual page](https://man7.org/linux/man-pages/man5/systemd.exec.5.html), if you leave `StandardOutput` as blank, it will default to `inherit` which duplicates the file descriptor used for `StandardInput`. When using `ListenFIFO` this will loop anything written to `StandardOutput` back to `StandardInput`, which isn't desirable. There are other options including writing to a file, see the link provided.

If you leave `StandardError` as blank, it generally defaults to `inherit` which duplicates the file descriptor for `StandardOutput`, potentially causing the same issues with looping back as noted above. (I presume this means that setting only `StandardOutput` will work correctly, but I haven't tested this; I prefer the explicit configuration of `StandardError` myself).

Presumably a configuration with only `StandardError=journal` will work if the console messages causing the (worst of?) looping are being written to `StandardError` and not `StandardOutput`, but potentially issues could arise if anything written to `StandardOutput` is looped back to `StandardInput`.

@lexo-mfleuti If the FIFO socket is working correctly, you should be able to issue commands by `echo`. You don't need to create the socket with `mkfifo`, as the socket handles this itself. I would delete this line:
```
ExecStartPre=/bin/bash -c '[[ -p /tmp/p2pool.stdin ]] && rm /tmp/p2pool.stdin; mkfifo /tmp/p2pool.stdin; exit 0
```
This might be deleting your original named socket created by `p2pool.socket` and creating a new FIFO; as the socket starts before the service.

Otherwise, the obvious thinks to check for are:
1) Errors in your systemd journal for `p2pool.socket` or `p2pool.service`.
2) Is stdin detected as `UV_NAMED_PIPE`? This is what my p2pool log shows when starting:
```
NOTICE  2023-04-20 04:13:12.3343 P2Pool v3.2 (built with GCC/11.2.1 on Mar 31 2023)
...
NOTICE  2023-04-20 04:13:12.6442 ConsoleCommands uv_guess_handle returned 7
NOTICE  2023-04-20 04:13:12.6443 ConsoleCommands processing stdin as UV_NAMED_PIPE
NOTICE  2023-04-20 04:13:12.6444 ConsoleCommands event loop started
...
```

**Comment by SChernykh** [comment]
>  the command echo "status" > /tmp/p2pool.stdin does not work

Try `status` (without quotes).

**Comment by lexo-mfleuti** [comment]
@SChernykh @twlee79 Thanks a lot you guys. It's amazing, the moment you do it right, it works ;)
With the latest build and the following config it all works fine now:

### p2pool.service

```
[Unit]
Description=P2Pool Full Node
After=network.target p2pool.socket
Requires=monerod.service
BindsTo=p2pool.socket

[Service]
StandardInput=socket
Sockets=p2pool.socket
WorkingDirectory=/opt/p2pool/build/
Type=simple
Restart=always
ExecStartPre=sysctl vm.nr_hugepages=3072
ExecStart=/opt/p2pool/build/p2pool --loglevel 4 --host 127.0.0.1 --wallet ABCD
TimeoutStopSec=60
StandardOutput=file:/opt/p2pool/build/stdout.log
StandardError=file:/opt/p2pool/build/error.log

[Install]
WantedBy=multi-user.target
```

### p2pool.socket

```
[Unit]
Description=P2Pool Socket

[Socket]
ListenFIFO=/tmp/p2pool.stdin
#NoDelay=true
RemoveOnStop=true

[Install]
WantedBy=sockets.target

```

You were right @twlee79 , I did not need to create the FIFO file beforehand. It handles all by itself.
By sending StandardOutput and StandardError to dedicated files and include those into the logrotate, for me, this is the perfect solution. 

Happy mining people! ;)
