### ISSUE TITLE
Better status

### ISSUE THREAD

**Issue by SnAFKe** [SChernykh/p2pool#257]
Would be nice if p2pool status display in log file.

I propose shown interval times something like in 5min 15min 30min 60min etc. to avoid flood in log file, as extra if you can create in command line the interval you want.

This would be very helpful for those who use the program in background mode.

**Comment by SChernykh** [comment]
You can get everything from status in json api if you add `--data-api path/to/api/directory --local-api` to the command line. From there, you can do whatever you want with the json data - grab it by a script, show on your own custom dashboard etc.
