### ISSUE TITLE
Monerod getting OOM killed even with the block_tor.txt

### ISSUE THREAD

**Issue by Vbrawl** [SChernykh/p2pool#259]
I was running monerod and I noticed that it got killed, I didn't kill it so I searched about it.

I found that there was an issue before about this, and it's some kind of vulnerability, I did what it said (downloading and including the block_tor.txt file) but that seems to be outdated since monerod got killed again.

If you need any other info don't hesitate to inform me.

**Comment by SChernykh** [comment]
Not a p2pool issue, post it in http://github.com/monero-project/monero
