### ISSUE TITLE
Update from RPC v3.5 to RPC v3.8 

### ISSUE THREAD

**Issue by pradoh97** [SChernykh/p2pool#26]
Hi everyone,

I'm getting this message _**P2Pool monerod RPC v3.5 is incompatible, update to RPC >= v3.8**_ when runing `./p2pool --host 127.0.0.1 --wallet [here I input my main address]`  and right after the p2pool process stops.

I also noticed that when the p2pool process reports that RPC message, monerod reports back `monerod[actual PID of the program]: 2021-09-14 18:20:59.395        E Invalid ZMQ/Sub message` `monerod[actual PID of the program]: 2021-09-14 18:20:59.397        E Invalid ZMQ/Sub message` (yeah, twice).

I'm following the readme steps (build p2pool and monero with all its utilities).

Any clue on how I can do such an update? 

Some information regarding my setup:
 - The node is synched and I can see my balance with monero-cli-wallet
 - I run the node with (I can use the node for transactions without a problem): `monerod --rpc-bind-ip 0.0.0.0 --rpc-bind-port 18081 --confirm-external-bind --zmq-pub tcp://127.0.0.1:18083 --data-dir [the proper uri for my datadir] --non-interactive` 
 - From the output of `monerod --version` it says I'm running on `Monero 'Oxygen Orion' (v0.17.2.3-04bfd948a)`
 - The OS is `Ubuntu Server 20.04.2 LTS (Focal Fossa)` and Linux Kernel is `5.4.0-84-generic`

Here is what I've tried so far:
Using an RCP call to check if there are monerod updates `curl http://127.0.0.1:18081/update -d '{"command":"check"}' -H 'Content-Type: application/json'` it returns:
```
{
  "auto_uri": "",
  "hash": "",
  "path": "",
  "status": "OK",
  "untrusted": false,
  "update": false,
  "user_uri": "",
  "version": ""
}
```

Also tried forcing the download of a newer version with `curl http://127.0.0.1:18081/update -d '{"command":"download"}' -H 'Content-Type: application/json'` but I get the exact same output as before, I understand if a new version is available it should be shown as a value in the key "version" (from [the monero docs about daemon rpc calls](https://web.getmonero.org/resources/developer-guides/daemon-rpc.html#update))

Maybe this is way too noob but did not know where to ask.

**Comment by SChernykh** [comment]
You should recompile monerod from my branch

**Comment by pradoh97** [comment]
> 
> 
> You should recompile monerod from my branch

Wow, that was quick. Ok, I'm going to recompile it, just in case: I got the daemon from this repo https://github.com/SChernykh/monero and followed the steps in the p2pool readme to compile it.

**Comment by SChernykh** [comment]
> > You should recompile monerod from my branch
> 
> Wow, that was quick. Ok, I'm going to recompile it, just in case: I got the daemon from this repo https://github.com/SChernykh/monero and followed the steps in the p2pool readme to compile it.

I changhed RPC version in the latest code there, this is why p2pool started to complain.

**Comment by pradoh97** [comment]
That was it... strange but it solved that problem. Thanks <3

**Comment by haussjonas** [comment]
How can I resolve this issue when using the nix flake?

**Comment by SChernykh** [comment]
Use `monerod` binary from the official p2pool release, or compile `release-v0.17` branch of https://github.com/monero-project/monero/ yourself.
