### ISSUE TITLE
no wallet files on docker

### ISSUE THREAD

**Issue by hubgitbb** [SChernykh/p2pool#260]
Hi
I cannot find the wallet and key files. The p2pool and all the files where created with the default docker-compose file.
I have the wallet name and password but no files.
The pool and wallet container are running but is that possible without wallet?

**Comment by SChernykh** [comment]
P2Pool docker container doesn't create a wallet for you, it only asks for a wallet address you already have.

**Comment by hubgitbb** [comment]
ok but it has created a monero container and then i created a wallet in that container. and now i cant find the wallet and key file

**Comment by SChernykh** [comment]
It's not a P2Pool issue though. Closing it.

P.S. You can open the wallet from inside the container, write down your seed phrase and restore it outside of the container.

**Comment by hubgitbb** [comment]
i have made the p2pool from scratch again with the same result. is there something wrong with the default docker compose file?

**Comment by SChernykh** [comment]
There is nothing wrong. It doesn't create a wallet, you must create a wallet yourself, and not in the docker container. Once you have a wallet, you just configure docker container to use your wallet address.
