### ISSUE TITLE
Issues with mining on local node running on windows 11

### ISSUE THREAD

**Issue by Dinamitrii** [SChernykh/p2pool#261]
Hello, i have working synchronized running node on Windows 11 machine and i downloaded a p2pool binaries to set up a pool,but the actual issue is that is the stratum server does NOT actually counting shares mined by xmrig latest version (every version of the running software is the latest release) so where is the problem?!Everything is with default settings like zmq-pub  on 18083 port except that the pool is run WITHOUT --mini option! Is that the root of the problem??Thank you in advance putting up Screenshots of node,pool and xmrig running.
![2023-04-29](https://user-images.githubusercontent.com/62879274/235272356-0bd2f490-01c3-4182-8b53-e36c607fa2fd.png)
![2023-04-29 (1)](https://user-images.githubusercontent.com/62879274/235272360-dc69ad08-74b6-4a24-bb80-abbdfdac0417.png)
![2023-04-29 (2)](https://user-images.githubusercontent.com/62879274/235272362-1696d319-bfdc-42e6-a19a-9cd47a2d4c40.png)

**Comment by SChernykh** [comment]
>  stratum server does NOT actually counting shares mined by xmrig

Because shares in p2pool status are NOT shares reported by xmrig. This was asked and answered million times on redddit and IRC.
