### ISSUE TITLE
[Request] Support arm64 macOS

### ISSUE THREAD

**Issue by hinto-janai** [SChernykh/p2pool#266]
Requesting an "official" P2Pool release build for `macos-arm64`.

x64 binaries seem to actually work on arm64 macOS but there's probably(?) translation overhead involved, not ideal.

I'll also be releasing `macos-arm64` for Gupax.

https://github.com/hinto-janai/gupax/issues/36
https://github.com/hinto-janai/gupax/issues/26

**Comment by SChernykh** [comment]
Github Actions doesn't have Apple M1 runners yet, so I can't compile it and run the test suite to guarantee that it would work. I don't have M1 hardware. I could try to cross-compile it, but there would be no way to test it and check if it works at all.

**Comment by SChernykh** [comment]
I've added cross-compiled binaries for Apple arm64 to Github Actions for P2Pool. They will be in v3.4 release, but they will be untested.

**Comment by hinto-janai** [comment]
Thanks. I synced v3.4 on M1, things seemed to work fine.

Is the email in your commits reachable?

**Comment by SChernykh** [comment]
> Is the email in your commits reachable?

Yes
