### ISSUE TITLE
`--light-mode` question

### ISSUE THREAD

**Issue by hinto-janai** [SChernykh/p2pool#267]
Just making sure: for non-mining P2Pools, is using `--light-mode` to use just the cache for verification but not have the whole dataset in memory ideal?

https://github.com/SChernykh/p2pool/blob/143960937e4994fc6df6ccd9f02801758b2141b5/src/pow_hash.cpp#L48-L75

i.e, `--light-mode` skips the first block for dataset allocation, but the cache always gets allocated, which is all we need for hash verification?

**Comment by SChernykh** [comment]
Yes, this is exactly what it does. `--light-mode` disables dataset allocation, but RandomX hashes can still be checked.
