### ISSUE TITLE
[question] is there a way to see how each of my rig performancing in term of payout? 

### ISSUE THREAD

**Issue by johnsmithodom** [SChernykh/p2pool#268]
While my gaming pc is mining most of the time, and  my laptop also mining when is being charge overnight. Since both of they set with one payout wallet, how can we check the payout for each rig as they are connect to the same p2pool. 

Thank you

**Comment by SChernykh** [comment]
P2Pool doesn't track this directly, but you can scan p2pool.log for SHARE_FOUND lines and they will show which rig found which share (assuming you set different names for your rigs in XMRig's command line)

**Comment by johnsmithodom** [comment]
> P2Pool doesn't track this directly, but you can scan p2pool.log for SHARE_FOUND lines and they will show which rig found which share (assuming you set different names for your rigs in XMRig's command line)

Can we have that feature implemented ?

**Comment by SChernykh** [comment]
No, P2Pool is not designed for this and this feature was deliberately not implemented. It's intended as a "single user" software. All you can do, apart from checking and counting SHARE_FOUND lines in log for each rig, is to run `workers` command in console - it will show your connected rigs and their hashrate.

If you want to have separate payouts for different rigs, you have to run separate P2Pool instances with different wallet addresses.

**Comment by johnsmithodom** [comment]
> No, P2Pool is not designed for this and this feature was deliberately not implemented. It's intended as a "single user" software. All you can do, apart from checking and counting SHARE_FOUND lines in log for each rig, is to run `workers` command in console - it will show your connected rigs and their hashrate.
> 
> If you want to have separate payouts for different rigs, you have to run separate P2Pool instances with different wallet addresses.

Currently, I only have 2 rigs working with the same address,  would like to add one more,  how can we know the payout after we found the individual hashrate of each rig where 3 of them assigned with a same address?

**Comment by SChernykh** [comment]
If you have to split the payout with someone, it's better that each of you runs their own p2pool instance, then you will be free from this headache. You can still connect all your p2pool instances to the same Monero node - you only need to run Monero node on one of the rigs.

**Comment by johnsmithodom** [comment]
> If you have to split the payout with someone, it's better that each of you runs their own p2pool instance, then you will be free from this headache. You can still connect all your p2pool instances to the same Monero node - you only need to run Monero node on one of the rigs.

No, I don't have to split the payout to anyone. but I would like to keep track our my each rig earning, so I would be in informed position to make decisions.  

Most people have more than one computers/devices, the "single user" software should also have this feature, please.  While xmr use CPUs and with the old pc we have, we would like to know after we should fix it,  it is worth to run some program with it when it is not being use for other stuff.

**Comment by SChernykh** [comment]
>  scan p2pool.log for SHARE_FOUND lines

This will give exactly how many hashes each rig contributed to the actual p2pool sidechain, so it's the best approximation of what each rig contributed to your payouts. Not each share results in a payout, so this number will not be precise, but tracking which share paid out is resource-intensive.

**Comment by johnsmithodom** [comment]
although not sure how it works under the hook,  when we already have the total payout and with "scan p2plool.log" for SHARE_FOUND, Can you please give an example how to approximate? 

Would this be more practical if we first check every 24 hours for each rig?  OR 
we can just have a method to approximate for each payout, ( in this base, we know the total payout, then approximate (assuming we also already have each rig SHARE_FOUND sum up)

**Comment by SChernykh** [comment]
Just run `grep 'SHARE FOUND' p2pool.log` on Linux or `findstr /C:"SHARE FOUND" p2pool.log` on Windows, and you will get a list of shares. Each line will have difficulty of the found share and rig name. You'll need to write some scripts to automate it.
