### ISSUE TITLE
Provide source archive with submodules

### ISSUE THREAD

**Issue by benthetechguy** [SChernykh/p2pool#270]
GitHub's source archives don't include submodules. This can cause some confusion for people who just download it and try to build, running into errors about missing libraries. It's also a problem for package maintainers; for example, Debian packages are supposed to be able to be built from a tarball without access to the internet (and tarballs should ideally come from upstream instead of the maintainer making their own from a git checkout with submodules). Adding to each release your own source archive would solve these problems, and also allow the source to be included in your signed checksum file.

**Comment by SChernykh** [comment]
Yes, good idea. I'll add it in the next release.

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool/releases/tag/v3.6
