### ISSUE TITLE
v3.6 fails to start on CentOS

### ISSUE THREAD

**Issue by 8lazo8** [SChernykh/p2pool#272]
After upgrading to version 3.6 from 3.5 p2pool fails to start.

 ./p2pool --version
2023-08-31 15:22:55.8017 Log started
P2Pool v3.6 (built with GCC/12.2.1 on Aug 31 2023)
2023-08-31 15:22:55.8039 Log stopped

Here is the log from messages:

Aug 31 17:17:18 centos-7 systemd: p2pool.service holdoff time over, scheduling restart.
Aug 31 17:17:18 centos-7 systemd: Stopped P2Pool.
Aug 31 17:17:18 centos-7 systemd: Started P2Pool.
Aug 31 17:17:18 centos-7 kernel: p2pool[15364]: segfault at 38 ip 00000000005d625b sp 00007ffffe0bc6d0 error 4 in p2pool[401000+1de000]
Aug 31 17:17:18 centos-7 abrt-hook-ccpp: Process 15364 (p2pool) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Aug 31 17:17:18 centos-7 systemd: p2pool.service: main process exited, code=dumped, status=11/SEGV
Aug 31 17:17:18 centos-7 systemd: Unit p2pool.service entered failed state.
Aug 31 17:17:18 centos-7 systemd: p2pool.service failed.
Aug 31 17:17:18 centos-7 abrt-server: Generating core_backtrace
Aug 31 17:17:18 centos-7 abrt-server: Error: No segments found in coredump './coredump'
Aug 31 17:17:18 centos-7 systemd: p2pool.service holdoff time over, scheduling restart.
Aug 31 17:17:18 centos-7 systemd: Stopped P2Pool.
Aug 31 17:17:18 centos-7 systemd: Started P2Pool.
Aug 31 17:17:18 centos-7 kernel: p2pool[15389]: segfault at 38 ip 00000000005d625b sp 00007fff5600cdc0 error 4 in p2pool[401000+1de000]
Aug 31 17:17:18 centos-7 abrt-hook-ccpp: Process 15389 (p2pool) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Aug 31 17:17:18 centos-7 systemd: p2pool.service: main process exited, code=dumped, status=11/SEGV
Aug 31 17:17:18 centos-7 systemd: Unit p2pool.service entered failed state.
Aug 31 17:17:18 centos-7 systemd: p2pool.service failed.
Aug 31 17:17:18 centos-7 systemd: p2pool.service holdoff time over, scheduling restart.
Aug 31 17:17:18 centos-7 systemd: Stopped P2Pool.
Aug 31 17:17:18 centos-7 systemd: Started P2Pool.
Aug 31 17:17:18 centos-7 kernel: p2pool[15401]: segfault at 38 ip 00000000005d625b sp 00007fffe82bbb70 error 4 in p2pool[401000+1de000]
Aug 31 17:17:18 centos-7 abrt-hook-ccpp: Process 15401 (p2pool) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Aug 31 17:17:18 centos-7 systemd: p2pool.service: main process exited, code=dumped, status=11/SEGV
Aug 31 17:17:18 centos-7 systemd: Unit p2pool.service entered failed state.
Aug 31 17:17:18 centos-7 systemd: p2pool.service failed.
Aug 31 17:17:18 centos-7 systemd: p2pool.service holdoff time over, scheduling restart.
Aug 31 17:17:18 centos-7 systemd: Stopped P2Pool.
Aug 31 17:17:18 centos-7 systemd: start request repeated too quickly for p2pool.service
Aug 31 17:17:18 centos-7 systemd: Failed to start P2Pool.
Aug 31 17:17:18 centos-7 systemd: Unit p2pool.service entered failed state.
Aug 31 17:17:18 centos-7 systemd: p2pool.service failed.

Rolling back to v3.5 p2pool is working fine.

**Comment by SChernykh** [comment]
This should be fixed in the latest master branch. You can compile it, or wait until the next release.

**Comment by 8lazo8** [comment]
> This should be fixed in the latest master branch. You can compile it, or wait until the next release.

Thanks, I will wait for the binary.

**Comment by SChernykh** [comment]
Fixed in https://github.com/SChernykh/p2pool/releases/tag/v3.6.1
