### ISSUE TITLE
Web UI still flagging p2pool is not updated but it is

### ISSUE THREAD

**Issue by edge7** [SChernykh/p2pool#276]
![Screenshot_2023-09-10-14-48-44-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/SChernykh/p2pool/assets/5433786/e2281763-c17f-4ba6-9486-6c6fd11054cf)
Hi.

I have updated but still get the above. It's not a big deal but wondering if can be fixed.
Thanks

**Comment by SChernykh** [comment]
P2Pool Observer is a 3rd-party site, you shouldn't report it here.
