### ISSUE TITLE
 How to support SSL?

### ISSUE THREAD

**Issue by bzhubs** [SChernykh/p2pool#282]
Hello, how to support SSL?

**Comment by SChernykh** [comment]
P2Pool doesn't support SSL. If you want to use SSL, you have to run xmrig-proxy with SSL enabled and connect your miners to it:
```
miners -> xmrig-proxy with SSL -> p2pool
```

**Comment by bzhubs** [comment]
It seems impossible, it always happens like this
127.0.0.1:3333 read error: "end of file"

Is there anything wrong with this configuration?

config.json
{
    "access-log-file": "/data/logs/xmrig-proxy.log",
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "0.0.0.0",
        "port": 4555,
        "access-token": "123",
        "restricted": true
    },
    "background": true,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 443,
            "tls": true
        },
        {
            "host": "::",
            "port": 443,
            "tls": true
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 100000,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": "/data/logs/ssl.log",
    "mode": "simple",
    "pools": [
        {
            "algo": "rx/0",
            "coin": "Monero",
            "url": "127.0.0.1:3333",
            "user": "my address",
            "pass": "x",
            "rig-id": "id1",
            "keepalive": true,
            "enabled": true,
            "tls": true,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": "/data/xmrig-proxy/cert.pem",
        "cert_key": "/data/xmrig-proxy/cert_key.pem",
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": "XMRig/6.18.2 (Linux x86_64) libuv/1.42 gcc/9.3.0",
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by SChernykh** [comment]
> Is there anything wrong with this configuration?

Yes, disable tls in `pools` section because you're connecting to p2pool which doesn't have tls.

**Comment by bzhubs** [comment]
My current configuration doesn't work. Can you help me change the configuration?

**Comment by bzhubs** [comment]
I want is miner-ssl ---> xmrig-proxy-ssl ---> p2pool-nossl

**Comment by SChernykh** [comment]
I already told you to set `"tls": false,` in `pools` section.

**Comment by bzhubs** [comment]
I tried this, but it still returns 127.0.0.1:3333 read error: "end of file"

**Comment by bzhubs** [comment]
It seems to be a network problem, I'll look into it again

**Comment by SChernykh** [comment]
If you're running P2Pool on the same machine, xmrig-proxy should connect to port 3333 without issues. Check what's in p2pool.log (set log level to 5 in p2pool and look for "StratumServer" warnings and errors).

**Comment by bzhubs** [comment]
Okay, let me check again and try.

**Comment by bzhubs** [comment]
I solved it according to your method, but I still can’t find it after working with 200K computing power for half an hour. 
What is the reason for this? 
https://p2pool.observer/

**Comment by SChernykh** [comment]
Even if you have 200 kh/s, you need 1.5 hours on average to find a single share on main p2pool: https://p2pool.observer/calculate-share-time?hashrate=200&magnitude=1000
If you're unlucky, it can be even 5 hours until you find a share. If you want to see your wallet on the observer faster, it's better to swtich to p2pool-mini (add `--mini` to p2pool command line).

**Comment by bzhubs** [comment]
Will --mini affect income? It’s been 3 hours and still no data

**Comment by SChernykh** [comment]
If you added --mini, you need to check mini.p2pool.observer

**Comment by bzhubs** [comment]
ok,But I don't know if it will affect the income

**Comment by SChernykh** [comment]
Income only depends on your hashrate, if you set up everything correctly. Mini p2pool finds fewer blocks, but it pays more in each block. On average, it will be the same.

**Comment by bzhubs** [comment]
Thank you, I have seen the data. I would like to ask again whether the income of p2pool is higher than that of traditional mining pools?

**Comment by SChernykh** [comment]
Yes, p2pool earns a bit more than regular pools because it has 0 fees, and it also has more efficient block template update algorithm: https://www.reddit.com/r/Monero/comments/11nu4aj/monero_transaction_confirmations_are_now_60/

> P2Pool, the decentralized mining protocol, already had implemented rapid block template updates before the centralized mining pools changed their configuration. P2Pool used to have a fee revenue advantage of about 0.004 XMR per block compared to other miners. Now that most other mining pools have changed, P2Pool's fee revenue advantage has shrunk to about 0.002 XMR per block.

**Comment by bzhubs** [comment]
I just learned about mining XMR, thank you very much.

**Comment by bzhubs** [comment]
The mining pools are all normal. Checking the mining pool logs shows that the computing power is 200K, but at https://p2pool.observer/ it is found to be 0. It was normal before, but suddenly it disappeared. Is this a normal phenomenon? Thank you!

**Comment by SChernykh** [comment]
If you're mining at p2pool-mini, you need to check your wallet address at https://mini.p2pool.observer/
Both p2pool observers only show your estimated hashrate, based on recently submitted shares.

**Comment by bzhubs** [comment]
I did not use --mini, so I checked the pool at https://p2pool.observer/. It was normal before, but after an interval of one hour, I found that it became 0.

**Comment by SChernykh** [comment]
What became 0? If you found shares before, they will be visible in the "Most recent shares" lists when you enter your wallet address. Your hashrate can be shown as 0 if you don't have shares in current PPLNS window which has shares from the last ~1.5 hours right now.

**Comment by bzhubs** [comment]
![a](https://github.com/SChernykh/p2pool/assets/28048361/f1fc5f7c-358a-4a68-89df-21fb9a7d8b12)

**Comment by bzhubs** [comment]
The Estimated Hashrate has become 0, but everything is normal in the mining pool and the computing power is still 200K

**Comment by SChernykh** [comment]
I wrote already

> Your hashrate can be shown as 0 if you don't have shares in current PPLNS window which has shares from the last ~1.5 hours right now.

**Comment by bzhubs** [comment]
Hello, does p2pool have an interface to view node status and other information? How to check?

**Comment by SChernykh** [comment]
You can type `status` command in p2pool window (and in monerod window). If you want a GUI interface, then I recommend https://github.com/hinto-janai/gupax
This is not an issue tracker, not a support channel. If you have more questions, it's better to ask them on IRC or reddit:
> P2Pool is a decentralized community, there is no dedicated support. You can reach and get help from other miners on:
IRC channels: #monero-pools and #p2pool-log (#p2pool-mini for P2Pool mini) on [Libera.Chat](https://libera.chat/)
Reddit: [r/MoneroMining](https://reddit.com/r/MoneroMining/)
