### ISSUE TITLE
monrod.exe errors

### ISSUE THREAD

**Issue by iratekalypso** [SChernykh/p2pool#29]
![image](https://user-images.githubusercontent.com/64004674/134067934-c3b22165-40cc-48b1-957f-85602a9e9fe6.png)
I am running into two errors when issuing the command: `monerod.exe --zmq-pub tcp://127.0.0.1:18083`

> 2021-09-20 19:54:20.936 F Error starting server: Failed to bind IPv4 (set to required)
2021-09-20 19:54:20.948 E Exception in main! Failed to initialize p2p server.

Any suggestions on fixing this?

**Comment by SChernykh** [comment]
Monero failed to bind port 18080 (Monero p2p port). Maybe you're already running another monerod on this machine?

**Comment by QuickBASIC** [comment]
If you're still seeing this error, open an elevated command prompt (Run as Administrator) and run `netstat -ab` to see a list of programs that currently have pots bound.
