### ISSUE TITLE
Various P2Pool questions

### ISSUE THREAD

**Issue by nemomaximus** [SChernykh/p2pool#290]
I have my P2Pool service up and running, but I have some questions to be able to fine tune my installation.

- I have the following option set "--data-api /p2pool/data". The problem is that the Linux service was unable to create the subdirectories "local, network and pool". I had to create them manually to get P2Pool to start. I assume that it is a permission issue, but what permission is missing? The user running the P2Pool service is the owner of the "/p2pool/data" directory.
- No files are created in the "local, network and pool" subdirectories. Do I need to do anything to get that to work?
- Is there any external web service out there to be used together with the JSON files that should be located here?

- Does P2Pool require access to the "unrestricted" rpc in moderod? Or can the "--rpc-port" point to the restricted monerod port?

- Should both monerod and P2Pool be configured with "vm.nr_hugepages=3072". What happens if that is not the case?

- I am sending console commands using "echo "status" > /run/p2pool/p2pool.control" and it works fine except for the fact that it all ends up in p2pool.log which is a busy file so finding the result even after a short time takes some effort. Is it possible to direct these results to another file? Or is it possible to do any kind of API call to get these results?

**Comment by SChernykh** [comment]
`--data-api /p2pool/data` Double check that you provide the correct absolute path to the folder. When you start P2Pool as a service, it's not guaranteed that it will be in the correct working folder. You have to run some web-server to display the contents of JSON files. You can check https://github.com/SChernykh/p2pool/tree/master/docs/html

P2Pool can run with restricted RPC.

**Comment by SChernykh** [comment]
Huge pages = 3072 should be enough to run both monerod and p2pool. If there are not enough huge pages, they will still run, but a bit slower.

`status` command only prints what's already available in JSON files, so you can use JSON files to get this information.

**Comment by nemomaximus** [comment]
- Yes, the absolut path is correct ("cd /p2pool/data" works fine). Any idea what the problem could be then? (I have created a user "p2pool" that runs the service with as little access right as possible).
- Is there any way to have the p2pool.log file in another directory the the p2pool binary?
- How much memory is recommended for the monerod and P2Pool Linux servers? (I have the service running on there own server with 4 GB each)

**Comment by SChernykh** [comment]
p2pool.log is created in the current directory. You can create a script that changes directory to what you want and then starts p2pool. Regarding /p2pool/data issues, it's something wrong with file permissions. You should run something like `chown -R p2pool:p2pool /p2pool` and then `chmod -R 0644 /p2pool`

**Comment by nemomaximus** [comment]
I finally got it to work and all files/directories created by the service for --data-api is now there as they should :)

These are the commands that made it all work:

```
mkdir /p2pool
mkdir /p2pool/bin
mkdir /p2pool/data
chown -R p2pool:p2pool /p2pool
chmod -R 0644 /p2pool
chmod 0744 /p2pool
chmod 0744 /p2pool/bin
chmod 0744 /p2pool/data 
chmod u+x /p2pool/bin/p2pool
```

Thanks for the help!

**Comment by nemomaximus** [comment]
Another question :) What is the difference between the log levels (0-6)? 

Is there any documentation what to expect in the log file depending on the setting?
