### ISSUE TITLE
 banned for 600 seconds

### ISSUE THREAD

**Issue by bzhubs** [SChernykh/p2pool#292]
Hi everyone, does anyone know the cause and how to deal with it?

After a week of observation, I discovered a problem. After a while, p2pool will disable the front-end xmrig-proxy for 10 minutes. What is the reason for this? After being disabled for 10 minutes, it will return to normal.

p2pool log:
WARNING 2023-11-17 09:09:25.3223 P2Pool submit_block (external blob): daemon returned error: Block not accepted
**WARNING 2023-11-17 09:09:56.3888 StratumServer peer MY_XMRIG_PROXY_IP_ADDRESS:50564 banned for 600 seconds**

**When p2pool disables xmrig-proxy, a large number of the following logs appear in the xmrig-proxy log:**
[2023-11-17 12:19:53.360]  proxy    0323 rejected (34940/7390+56) diff 36583 ip xxxxxxx "Banned" (43 ms)
[2023-11-17 12:19:53.503]  proxy    0433 rejected (34940/7391+56) diff 422525 ip xxxxxx "Banned" (43 ms)
[2023-11-17 12:19:53.514]  proxy    0279 rejected (34940/7392+56) diff 90353 ip xxxxxxxx "Banned" (49 ms)
[2023-11-17 12:19:53.527]  proxy    0038 rejected (34940/7393+56) diff 82049 ip xxxxxxxx "Banned" (43 ms)
[2023-11-17 12:19:53.595]  proxy    0417 rejected (34940/7394+56) diff 10833 ip xxxxxx "Banned" (44 ms)
[2023-11-17 12:19:53.663]  proxy    0243 rejected (34940/7395+56) diff 18446 ip xxxxx "Banned" (47 ms)
[2023-11-17 12:19:53.801]  proxy    0178 rejected (34940/7396+56) diff 44125 ip xxxxx "Banned" (47 ms)

**Comment by SChernykh** [comment]
Increase log level to 4 in P2Pool to see the reason why it bans your proxy.

**Comment by SChernykh** [comment]
Any updates on this? Are you running with log level 4, but there have been no bans yet?

**Comment by bzhubs** [comment]
Sorry, I haven’t replied to you because I have been testing. After two days of testing, the problem pattern was found。

NOTICE  2023-11-19 13:03:27.0470 StratumServer sent new job to 123/123 clients
WARNING 2023-11-19 13:03:31.1217 StratumServer client my_xmrig_proxy_ip:37564 invalid JSON request (parse error)
WARNING 2023-11-19 13:03:31.1218 StratumServer peer my_xmrig_proxy_ip:37564 banned for 600 seconds

or 

NOTICE  2023-11-18 12:03:51.2355 StratumServer sent new job to 123/123 clients
WARNING 2023-11-18 12:04:01.6438 StratumServer peer my_xmrig_proxy_ip:52274 banned for 600 seconds

Generally, these two situations occur, with the first situation accounting for the majority.

**Comment by SChernykh** [comment]
```
NOTICE 2023-11-18 12:03:51.2355 StratumServer sent new job to 123/123 clients
WARNING 2023-11-18 12:04:01.6438 StratumServer peer my_xmrig_proxy_ip:52274 banned for 600 seconds
```
Was this one also with log level 4? Because I can't find a place in the code that would ban a connected peer and not write something in the log at least on level 4.

**Comment by bzhubs** [comment]
nohup ./p2pool --host 127.0.0.1 --wallet xxxxxxxxxxxxxxxx --data-api /data/status --loglevel 4 &


This is the command I started with

**Comment by bzhubs** [comment]
I  using the official xmrig-proxy binary， 
I configured two independent VPS for xmrig-proxy testing, one with nicehash mode and one with simple mode. Same problem. And this problem will occur on both xmrig-proxy at the same time

xrmig-proxy log:
[2023-11-19 15:45:45.603]  proxy    5108 rejected (2895137/75908+5254) diff 18047 ip xxx "Banned" (52 ms)
[2023-11-19 15:45:45.620]  proxy    6615 rejected (2895137/75909+5254) diff 85792 ip xxx "Banned" (52 ms)
[2023-11-19 15:45:45.676]  proxy    7313 rejected (2895137/75910+5254) diff 3507 ip xxx "Banned" (55 ms)
....................

**Comment by bzhubs** [comment]
No manual intervention is required, both xmrig-proxy will return to normal at the same time. I was suspicious of the firewall, and then I turned off the firewall on all machines, but the problem still exists.

**Comment by SChernykh** [comment]
Are you able to compile your own p2pool binary? If so, can you change this code https://github.com/SChernykh/p2pool/blob/master/src/stratum_server.cpp#L1133 to this (note the added log line and uncommented `size` variable):
```
bool StratumServer::StratumClient::process_request(char* data, uint32_t size)
{
	rapidjson::Document doc;
	if (doc.ParseInsitu(data).HasParseError()) {
		LOGWARN(4, "client " << static_cast<char*>(m_addrString) << " invalid JSON request (parse error)");
		LOGWARN(0, log::const_buf(data, std::min<size_t>(size, 900)));
		return false;
	}
```
It will show what exactly the proxy is trying to send, then I'll know more.

**Comment by bzhubs** [comment]
Ok, I try

**Comment by bzhubs** [comment]
I'm afraid this will take some time. I'll get back to you when I have the data. Thank you.

**Comment by bzhubs** [comment]
bool StratumServer::StratumClient::process_request(char* data, uint32_t size)
{
        rapidjson::Document doc;
        if (doc.Parse(data).HasParseError()) {
                LOGWARN(4, "client " << static_cast<char*>(m_addrString) << " invalid JSON request (parse error)");
                LOGWARN(0, log::const_buf(data, std::min<size_t>(size, 900)));
                return false;
        }


It cannot be compiled normally after changes, but it can be compiled normally without changes.

root@vps:~/p2pool/build# make -j$(nproc)
[ 20%] Built target libminiupnpc-static
[ 56%] Built target randomx
Scanning dependencies of target p2pool
[ 59%] Built target upnp-listdevices-static
[ 62%] Built target randomx-tests
[ 63%] Building CXX object CMakeFiles/p2pool.dir/src/stratum_server.cpp.o
[ 65%] Linking CXX executable p2pool
/usr/include/uv.h:1746:9: note: type ‘union <anon>’ itself violates the C++ One Definition Rule
 1746 |   union {
      |         ^
/usr/local/include/uv.h:1812:9: note: the incompatible type is defined here
 1812 |   union {
      |         ^
/root/p2pool/src/tcp_server.h:25:7: error: type ‘struct TCPServer’ violates the C++ One Definition Rule [-Werror=odr]
   25 | class TCPServer : public nocopy_nomove
      |       ^
/root/p2pool/src/tcp_server.h:25:7: note: a different type is defined in another translation unit
   25 | class TCPServer : public nocopy_nomove
      |       ^
/root/p2pool/src/tcp_server.h:178:12: note: the first difference of corresponding definitions is field ‘m_loop’
  178 |  uv_loop_t m_loop;
      |            ^
/root/p2pool/src/tcp_server.h:178:12: note: a field of same name but different type is defined in another translation unit
  178 |  uv_loop_t m_loop;
      |            ^
/root/p2pool/src/tcp_server.h:25:7: note: type ‘struct uv_loop_t’ itself violates the C++ One Definition Rule
   25 | class TCPServer : public nocopy_nomove
      |       ^
/root/p2pool/src/stratum_server.h:31:7: error: type ‘struct StratumServer’ violates the C++ One Definition Rule [-Werror=odr]
   31 | class StratumServer : public TCPServer
      |       ^
/root/p2pool/src/stratum_server.h:31:7: note: a type with different bases is defined in another translation unit
   31 | class StratumServer : public TCPServer
      |       ^
/root/p2pool/src/p2p_server.h:159:7: error: ‘broadcast’ violates the C++ One Definition Rule [-Werror=odr]
  159 |  void broadcast(const PoolBlock& block, const PoolBlock* parent);
      |       ^
/root/p2pool/src/p2p_server.cpp:772:6: note: ‘broadcast’ was previously declared here
  772 | void P2PServer::broadcast(const PoolBlock& block, const PoolBlock* parent)
      |      ^
/root/p2pool/src/p2p_server.h:61:11: error: ‘__ct_comp ’ violates the C++ One Definition Rule [-Werror=odr]
   61 |  explicit P2PServer(p2pool *pool);
      |           ^
/root/p2pool/src/p2p_server.cpp:46:1: note: ‘__ct_comp ’ was previously declared here
   46 | P2PServer::P2PServer(p2pool* pool)
      | ^
/root/p2pool/src/p2p_server.h:65:7: error: ‘clear_cached_blocks’ violates the C++ One Definition Rule [-Werror=odr]
   65 |  void clear_cached_blocks();
      |       ^
/root/p2pool/src/p2p_server.cpp:181:6: note: ‘clear_cached_blocks’ was previously declared here
  181 | void P2PServer::clear_cached_blocks()
      |      ^
/root/p2pool/src/p2p_server.h:66:7: error: ‘store_in_cache’ violates the C++ One Definition Rule [-Werror=odr]
   66 |  void store_in_cache(const PoolBlock& block);
      |       ^
/root/p2pool/src/p2p_server.cpp:202:6: note: ‘store_in_cache’ was previously declared here
  202 | void P2PServer::store_in_cache(const PoolBlock& block)
      |      ^
/root/p2pool/src/p2p_server.h:68:7: error: ‘connect_to_peers_async’ violates the C++ One Definition Rule [-Werror=odr]
   68 |  void connect_to_peers_async(const char* peer_list);
      |       ^
/root/p2pool/src/p2p_server.cpp:209:6: note: ‘connect_to_peers_async’ was previously declared here
  209 | void P2PServer::connect_to_peers_async(const char* peer_list)
      |      ^
/root/p2pool/src/p2p_server.h:164:7: error: ‘show_peers_async’ violates the C++ One Definition Rule [-Werror=odr]
  164 |  void show_peers_async();
      |       ^
/root/p2pool/src/p2p_server.cpp:1005:6: note: ‘show_peers_async’ was previously declared here
 1005 | void P2PServer::show_peers_async()
      |      ^
/root/p2pool/src/p2p_server.h:180:7: error: ‘check_for_updates’ violates the C++ One Definition Rule [-Werror=odr]
  180 |  void check_for_updates(bool forced = false) const;
      |       ^
/root/p2pool/src/p2p_server.cpp:1271:6: note: ‘check_for_updates’ was previously declared here
 1271 | void P2PServer::check_for_updates(bool forced) const
      |      ^
/root/p2pool/src/p2p_server.h:64:7: error: ‘add_cached_block’ violates the C++ One Definition Rule [-Werror=odr]
   64 |  void add_cached_block(const PoolBlock& block);
      |       ^
/root/p2pool/src/p2p_server.cpp:164:6: note: ‘add_cached_block’ was previously declared here
  164 | void P2PServer::add_cached_block(const PoolBlock& block)
      |      ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/p2pool.dir/build.make:467: p2pool] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/p2pool.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by bzhubs** [comment]
I compiled is not a static binary file, but a dynamic binary file.

**Comment by SChernykh** [comment]
Dynamic binary file will work fine on the same machine. Is it running now?

**Comment by bzhubs** [comment]
WARNING 2023-11-20 03:20:11.5661 StratumServer client my_xmrig_proxy_ip:34027 invalid JSON request (parse error)
WARNING 2023-11-20 03:20:11.5662 StratumServer GET / HTTP/1.1^M
WARNING 2023-11-20 03:20:11.5662 StratumServer peer my_xmrig_proxy_ip:34027 banned for 600 seconds

**Comment by bzhubs** [comment]
There are only such errors in the log, which seem to have no substantial effect.

**Comment by SChernykh** [comment]
You get an HTTP request instead of a JSON data. And it's not even a valid HTTP request because of an `^M` in the end. Either something from that IP address is trying to HTTP probe your P2Pool's Stratum, or it's xmrig-proxy that is misconfigured.

**Comment by bzhubs** [comment]
{
    "access-log-file": "/data/logs/xmrig-proxy.log",
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "0.0.0.0",
        "port": 8080,
        "access-token": "12345678",
        "restricted": true
    },
    "background": true,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": true 
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 100000,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": "/data/logs/access.log",
    "mode": "simple",
    "pools": [
        {
            "algo": "rx/0",
            "coin": "Monero",
            "url": "p2pool_ip:3333",
            "user": "xxxxxxxxxxxxxxxxxxx.w1",
            "pass": "x",
            "rig-id": "w1"
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": "/data/xmrig-proxy/cert.pem",
        "cert_key": "/data/xmrig-proxy/cert_key.pem",
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": "XMRig/6.18.2 (Linux x86_64) libuv/1.42.1-dev gcc/7.2.0",
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true

}


If the configuration is wrong, it should always be wrong or unable to start, but it will automatically recover after a problem occurs.

**Comment by bzhubs** [comment]
There is no software or tool to configure detection

**Comment by SChernykh** [comment]
> I configured two independent VPS for xmrig-proxy testing

It might be the VPS provider probing your ports. The only way to check if it's an xmrig-proxy problem, is to run it on the same host and then look for `invalid JSON request (parse error)` warnings. If they don't appear anymore, it's something external interfering.

**Comment by SChernykh** [comment]
@bzhubs Did you figure it out?
