### ISSUE TITLE
Public p2pool pools

### ISSUE THREAD

**Issue by APT-ZERO** [SChernykh/p2pool#293]
Hi
I want to mine without running Monerod on my local machine
Is there any public p2pool that i can connect my xmrig to it?
Thank you

**Comment by MarcusNewman** [comment]
Do you want to keep the earnings from your mining? I know the way I have my p2pool setup is the mining address is at the p2pool level. You would just be helping someone else earn the rewards.

**Comment by SChernykh** [comment]
The intended way is to run your own monerod, p2pool and xmrig. Everything else is centralized mining in some way or form. Yes you connect to someone else's monerod but it will not be as reliable as your own node.

**Comment by SChernykh** [comment]
You need to run monerod+p2pool only on one machine. Everything else needs only xmrig.

**Comment by SChernykh** [comment]
No, wallet is only set at P2Pool node. XMRig's setting is ignored when it connects to a P2Pool node.
