### ISSUE TITLE
Zephyr support

### ISSUE THREAD

**Issue by DeMemeTree** [SChernykh/p2pool#296]
The curious case of Zephyr. 

Somebody smooshed together Djed logic and Monero codebase to create Zephyr. 
More info can be found out about the project here https://www.zephyrprotocol.com.

Currently all of the pool operators are gathering up any transaction fee that is associated with transfers (not swaps) for assets such as ZSD and ZRS. They are only keeping track and paying out Zeph to miners, even though blocks could have ZSD or ZRS transaction fees.

Since Zeph is a fork of XMR I would think its possible to natively implement support for payouts to all miners for Zeph, ZSD, ZRS through a p2pool like merge mining technology. 

Curious what are your thoughts on this and if its even possible?

**Comment by SChernykh** [comment]
I didn't look at the details of how ZSD and ZRS payouts are implemented, but if there can be multiple ZSD/ZRS outputs in the coinbase transaction, it's possible. Multiple ZEPH outputs in the coinbase transaction must be possible, unless they changed something when forking Monero.

But it's not a small task to implement all this, I estimate it to be 1-2 weeks of full time work (not counting the learning stage). I don't have time for it right now, maybe Zeph developers will fork P2Pool and try to implement it. I can answer their question in Discord.

**Comment by DeMemeTree** [comment]
I am decently versed with c++ and would like to take the task on myself as I have already studied some of what they changed and I think they are busy with other changes and research. 

Even if I dont get the ZRS/ZSD working I would think I should be able to get it up and running for Zeph at the very least.

I shouldnt have a lot of questions for you but I may have a few to start after I finish my analysis of the codebase, where in discord can I find you to chat?

**Comment by SChernykh** [comment]
My discord name is `sech1`, I'm in Zephyr discord too.
