### ISSUE TITLE
p2pool docker compose fail -Ubuntu focal repos not longer online

### ISSUE THREAD

**Issue by belba** [SChernykh/p2pool#298]
Hello,

I tried to run p2pool in docker but the docker compose failed (after the step docker compose build --no-cache):

```
40.65 Recommended packages:
40.65   fakeroot gnupg | gnupg2 libalgorithm-merge-perl less ssh-client manpages
40.65   manpages-dev libfile-fcntllock-perl liblocale-gettext-perl libglib2.0-data
40.65   shared-mime-info xdg-user-dirs krb5-locales publicsuffix libsasl2-modules
40.65   libltdl-dev netbase
40.73 The following NEW packages will be installed:
40.73   autoconf automake autotools-dev binutils binutils-common
40.73   binutils-x86-64-linux-gnu bsdmainutils build-essential ca-certificates
40.73   ccache cmake cmake-data cpp cpp-9 curl dpkg-dev file g++ g++-9 gcc gcc-9
40.73   gcc-9-base git git-man gperf libarchive13 libasan5 libasn1-8-heimdal
40.73   libatomic1 libbinutils libbrotli1 libbsd0 libc-dev-bin libc6-dev libcc1-0
40.73   libcrypt-dev libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4 libdpkg-perl
40.73   liberror-perl libexpat1 libgcc-9-dev libgdbm-compat4 libgdbm6 libglib2.0-0
40.73   libgomp1 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal
40.73   libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libicu66
40.73   libisl22 libitm1 libjsoncpp1 libk5crypto3 libkeyutils1 libkrb5-26-heimdal
40.73   libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblsan0 libmagic-mgc
40.73   libmagic1 libmpc3 libmpfr6 libnghttp2-14 libperl5.30 libpsl5 libquadmath0
40.73   librhash0 libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules-db
40.73   libsigsegv2 libsqlite3-0 libssh-4 libssl1.1 libstdc++-9-dev libtool libtsan0
40.73   libubsan1 libuv1 libwind0-heimdal libxml2 linux-libc-dev m4 make openssl
40.73   patch perl perl-modules-5.30 pkg-config tzdata xz-utils
45.00 0 upgraded, 100 newly installed, 0 to remove and 0 not upgraded.
45.00 Need to get 80.1 MB of archives.
45.00 After this operation, 388 MB of additional disk space will be used.
45.00 Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 perl-modules-5.30 all 5.30.0-9ubuntu0.5
45.01 Err:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libgdbm6 amd64 1.18.1-5
45.01   Unable to connect to archive.ubuntu.com:http:
45.01 Err:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libgdbm-compat4 amd64 1.18.1-5
45.01   Unable to connect to archive.ubuntu.com:http:
45.01 Ign:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libperl5.30 amd64 5.30.0-9ubuntu0.5
45.01 Ign:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 perl amd64 5.30.0-9ubuntu0.5
45.01 Ign:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssl1.1 amd64 1.1.1f-1ubuntu2.20
45.01 Ign:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 openssl amd64 1.1.1f-1ubuntu2.20
45.01 Ign:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 ca-certificates all 20230311ubuntu0.20.04.1
45.01 Err:9 http://archive.ubuntu.com/ubuntu focal/main amd64 libmagic-mgc amd64 1:5.38-4
45.01   Unable to connect to archive.ubuntu.com:http:

```

It seems that the repositories are not longer accesible in the new year.

**Comment by SChernykh** [comment]
Dockerfile uses Ubuntu 20.04 (focal) which is an LTS release, so it should be still available. But I see that it's at a different path now: http://archive.ubuntu.com/ubuntu/dists/focal/

Maybe your Docker install needs an update to know about the new path?

**Comment by SChernykh** [comment]
@belba do you still have this error?

**Comment by belba** [comment]
Sorry I was very busy the last days...

I tried again to get a running Docker container, without success!. As preparation I delete all containers and all images and cloned a new p2pool here from github, according your instructions.
Here are some cli outputs:

`guido@monero:~/Monero/p2pool/docker-compose$ sudo docker compose build --no-cache
[+] Building 80.9s (5/11)                                                                                                                                                                           docker:default
 => [monero internal] load build definition from Dockerfile                                                                                                                                                   0.3s
 => => transferring dockerfile: 1.66kB                                                                                                                                                                        0.0s
 => [monero internal] load .dockerignore                                                                                                                                                                      0.5s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [monero internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                        0.9s
 => CACHED [monero builder 1/4] FROM docker.io/library/ubuntu:20.04@sha256:f2034e7195f61334e6caff6ecf2e965f92d11e888309065da85ff50c617732b8                                                                   0.0s
 => ERROR [monero builder 2/4] RUN set -e &&     apt-get update -q -y --no-install-recommends &&     DEBIAN_FRONTEND="noninteractive" apt-get install -q -y --no-install-recommends         automake         79.1s
------                                                                                                                                                                                                             
 > [monero builder 2/4] RUN set -e &&     apt-get update -q -y --no-install-recommends &&     DEBIAN_FRONTEND="noninteractive" apt-get install -q -y --no-install-recommends         automake         autotools-dev         bsdmainutils         build-essential         ca-certificates         ccache         cmake         curl         git         libtool         pkg-config         gperf:                                      
0.604 Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]                                                                                                                                              
0.633 Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                                                                                                    
1.122 Get:3 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [29.7 kB]                                                                                                                   
1.142 Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
1.238 Get:5 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [3142 kB]
1.277 Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
1.432 Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
2.421 Get:8 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
`
...

`22.60 The following NEW packages will be installed:
22.60   autoconf automake autotools-dev binutils binutils-common
22.60   binutils-x86-64-linux-gnu bsdmainutils build-essential ca-certificates
22.60   ccache cmake cmake-data cpp cpp-9 curl dpkg-dev file g++ g++-9 gcc gcc-9
22.60   gcc-9-base git git-man gperf libarchive13 libasan5 libasn1-8-heimdal
22.60   libatomic1 libbinutils libbrotli1 libbsd0 libc-dev-bin libc6-dev libcc1-0
22.60   libcrypt-dev libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4 libdpkg-perl
22.60   liberror-perl libexpat1 libgcc-9-dev libgdbm-compat4 libgdbm6 libglib2.0-0
22.60   libgomp1 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal
22.60   libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libicu66
22.60   libisl22 libitm1 libjsoncpp1 libk5crypto3 libkeyutils1 libkrb5-26-heimdal
22.60   libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblsan0 libmagic-mgc
22.60   libmagic1 libmpc3 libmpfr6 libnghttp2-14 libperl5.30 libpsl5 libquadmath0
22.60   librhash0 libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules-db
22.60   libsigsegv2 libsqlite3-0 libssh-4 libssl1.1 libstdc++-9-dev libtool libtsan0
22.60   libubsan1 libuv1 libwind0-heimdal libxml2 linux-libc-dev m4 make openssl
22.60   patch perl perl-modules-5.30 pkg-config tzdata xz-utils
22.88 0 upgraded, 100 newly installed, 0 to remove and 0 not upgraded.
22.88 Need to get 80.1 MB of archives.
22.88 After this operation, 388 MB of additional disk space will be used.
22.88 Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 perl-modules-5.30 all 5.30.0-9ubuntu0.5 [2739 kB]
24.56 Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libgdbm6 amd64 1.18.1-5 [27.4 kB]
24.57 Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libgdbm-compat4 amd64 1.18.1-5 [6244 B]
`
...

`36.69 Get:41 http://archive.ubuntu.com/ubuntu focal/main amd64 libcrypt-dev amd64 1:4.4.10-10ubuntu4 [104 kB]
36.73 Get:42 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libc6-dev amd64 2.31-0ubuntu9.14 [2519 kB]
37.90 Get:43 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 gcc-9-base amd64 9.4.0-1ubuntu1~20.04.2 [18.9 kB]
37.91 Get:44 http://archive.ubuntu.com/ubuntu focal/main amd64 libisl22 amd64 0.22.1-1 [592 kB]
38.15 Get:45 http://archive.ubuntu.com/ubuntu focal/main amd64 libmpfr6 amd64 4.0.2-1 [240 kB]
38.24 Get:46 http://archive.ubuntu.com/ubuntu focal/main amd64 libmpc3 amd64 1.1.0-1 [40.8 kB]
38.26 Get:47 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 cpp-9 amd64 9.4.0-1ubuntu1~20.04.2 [7502 kB]
74.99 Ign:47 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 cpp-9 amd64 9.4.0-1ubuntu1~20.04.2
75.00 Err:48 http://archive.ubuntu.com/ubuntu focal/main amd64 cpp amd64 4:9.3.0-1ubuntu2
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Ign:49 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcc1-0 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:50 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgomp1 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:51 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libitm1 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:52 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libatomic1 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:53 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libasan5 amd64 9.4.0-1ubuntu1~20.04.2
75.00 Ign:54 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 liblsan0 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:55 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libtsan0 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:56 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libubsan1 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:57 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libquadmath0 amd64 10.5.0-1ubuntu1~20.04
75.00 Ign:58 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgcc-9-dev amd64 9.4.0-1ubuntu1~20.04.2
75.00 Ign:59 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 gcc-9 amd64 9.4.0-1ubuntu1~20.04.2
75.00 Err:60 http://archive.ubuntu.com/ubuntu focal/main amd64 gcc amd64 4:9.3.0-1ubuntu2
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Ign:61 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libstdc++-9-dev amd64 9.4.0-1ubuntu1~20.04.2
75.00 Ign:62 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 g++-9 amd64 9.4.0-1ubuntu1~20.04.2
75.00 Err:63 http://archive.ubuntu.com/ubuntu focal/main amd64 g++ amd64 4:9.3.0-1ubuntu2
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Err:64 http://archive.ubuntu.com/ubuntu focal/main amd64 make amd64 4.2.1-1.2
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Ign:65 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdpkg-perl all 1.19.7ubuntu3.2
75.00 Err:66 http://archive.ubuntu.com/ubuntu focal/main amd64 patch amd64 2.7.6-6
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Ign:67 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 dpkg-dev all 1.19.7ubuntu3.2
75.00 Err:68 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 build-essential amd64 12.8ubuntu1.1
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Err:69 http://archive.ubuntu.com/ubuntu focal/main amd64 ccache amd64 3.7.7-1
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Err:70 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 cmake-data all 3.16.3-1ubuntu1.20.04.1
75.00   Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
75.00 Ign:71 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libarchive13 amd64 3.4.0-2ubuntu1.2
75.00 Ign:72 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libbrotli1 amd64 1.0.7-6ubuntu0.1
`
...

`79.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libs/libssh/libssh-4_0.9.3-2ubuntu2.4_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.68.0-1ubuntu2.21_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libj/libjsoncpp/libjsoncpp1_1.7.4-3.1ubuntu2_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/r/rhash/librhash0_1.3.9-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cmake/cmake_3.16.3-1ubuntu1.20.04.1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 EFetched 29.9 MB in 57s (530 kB/s)
79.12 : Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.68.0-1ubuntu2.21_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl3-gnutls_7.68.0-1ubuntu2.21_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libe/liberror-perl/liberror-perl_0.17029-1_all.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/git/git-man_2.25.1-1ubuntu3.11_all.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/git/git_2.25.1-1ubuntu3.11_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/gperf/gperf_3.1-1build1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libt/libtool/libtool_2.4.6-14_all.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/pkg-config/pkg-config_0.29.1-0ubuntu4_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.91.82 80]
79.12 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve: process "/bin/sh -c set -e &&     apt-get update -q -y --no-install-recommends &&     DEBIAN_FRONTEND=\"noninteractive\" apt-get install -q -y --no-install-recommends         automake         autotools-dev         bsdmainutils         build-essential         ca-certificates         ccache         cmake         curl         git         libtool         pkg-config         gperf" did not complete successfully: exit code: 100
guido@monero:~/Monero/p2pool/docker-compose$ 
`

**Comment by SChernykh** [comment]
Does it still happen? Did you try another internet connection?

**Comment by bladedoyle** [comment]
The "ubuntu:20.04" image gets updated so one thing to try is to pull the latest version with:
```
docker pull ubuntu:20.04
```
Then re-run the p2pool docker compose build
