### ISSUE TITLE
Very BAD raffle raunds' rules

### ISSUE THREAD

**Issue by elstak80** [SChernykh/p2pool#299]
Hi, i think the way you are assigning the rounds are very very very very bad, 5 of the last 10 rounds was win by the same wallet, with ~100kh/s. Plus the whale round is not 1000kh/s as we have just 1 wallet with 100k/h and is always there (of course).

In that way most of the round can be win by the same ppl so is better to add some rules... maybe if a wallet win a round, will not partecipate to the next donor-vip-whale... idk put i'll stop donating because now with have 3 wallets (i'm sure is the same user) with 90-90-100 khs that is winning all the fucking rounds, vip-vip donor-whale donor-top donor and is not fair.

As i said, as soon as you change the rules on 12th those 3 wallets appear... with around 300khs they are taking 2-3 mh/s 1 hour boost... please fix

**Comment by paulfarrowuk** [comment]
The xmrvsbeast raffle isn't directly part of p2pool - it is run by a third party. Fortunately, they are very open to suggestions for improvements. You can discuss these here: [](https://matrix.to/#/#xmrvsbeast:matrix.org)
The aim of the raffle is to bring as many people over to mining on p2pool as possible by having a little incentive to do so. Yes, the top 5 donors are winning a lot of the raffles, but they're also adding around 400Kh/s to the donation wins - essentially its like buying up a lot of the lottery tickets.

The Whale round was added to try and entice some larger hashrate donations into the raffle. I'd say its working, but we wouldn't want to see this happen at the detriment of the smaller donors leaving as they feel they never have a chance to win.

**Comment by SChernykh** [comment]
You should probably ask on IRC #p2pool-log on libera.chat
I don't run this raffle.

**Comment by elstak80** [comment]
> The xmrvsbeast raffle isn't directly part of p2pool - it is run by a third party. Fortunately, they are very open to suggestions for improvements. You can discuss these here: The aim of the raffle is to bring as many people over to mining on p2pool as possible by having a little incentive to do so. Yes, the top 5 donors are winning a lot of the raffles, but they're also adding around 400Kh/s to the donation wins - essentially its like buying up a lot of the lottery tickets.
> 
> The Whale round was added to try and entice some larger hashrate donations into the raffle. I'd say its working, but we wouldn't want to see this happen at the detriment of the smaller donors leaving as they feel they never have a chance to win.

Well, 400kh is nothing compared to the 2-3 mh/s, if i move all my 200kh rig to the donation i'll win more hashpower compared to what i can do without. The cycle is vip-dono vip- donor top- donor whale, for each is enough to remove a winning wallet from the running cycle... i can't see the same wallet 5 times on 10...

**Comment by paulfarrowuk** [comment]
Which is likely the reason they're donating so much as they'll win more often.
Hell, even my tiny 20Kh/s gets enough wins in a week to make up for not mining solo into the mini side chain.
The new rules are listed on the website. You need to be actively donating and have a share in either the main or mini PPLNS window to be eligible to win. This way there is still plenty of hashrate going into the p2pool side chains as well as the donations for the raffle. xmrvsbeast certainly doesn't have to give away 2MH/s+ of their own hash rate, they do so out of a longing to see p2pool grow. It's a very nice to have thing, but not something that should be abused or taken for granted.
