### ISSUE TITLE
StratumServer client: invalid JSON request ('id' field not found)

### ISSUE THREAD

**Issue by xmrvsbeast** [SChernykh/p2pool#3]
When trying to add p2pool to a rig on miningrigrentals.com I am getting:
"StratumServer client: invalid JSON request ('id' field not found)"

When going through xmrig-proxy it connects but jobs are issued with a very high diff ~ 390976 for a 12kh/s worker but on the miner side share diff is being reported as < 14 diff and hash rate stays < 500h/s

Trying it on a higher hash miner rig with multiple workers the rig reports "Invalid job parameters" and never starts with share diff reported on the miner side as 1.

I have tried --light-mode with same result.  Are these incompatibilities with the p2pool stratum server?  

It works OK with other pools.  thanks.

**Comment by SChernykh** [comment]
What software reports `Invalid job parameters`?

**Comment by xmrvsbeast** [comment]
The new code worked when adding the p2pool to one of the rigs but then when I tried on another I got:

StratumServer client: invalid JSON request (parse error)

I cannot determine the miner software of the high hash rigs, they appear to be running something custom because the worker label just says "unknown" where on the low hash rigs < 100kh/s it says something like "XMRig/6.13.1 (Windows NT 10.0; Win64; x64)"

**Comment by SChernykh** [comment]
> If I send it to p2pool through xmrig-proxy with a fixed diff set in the proxy config then the MRR web ui shows the diff I set and proper hash rate on the lower hash rigs, < 100kh/s, the high hash rigs still show wrong diff even with this workaround.

I think it's because MRR proxy doesn't know how to handle 8-byte target in a job, so it just takes first 4 bytes and shows wrong diff.

**Comment by SChernykh** [comment]
@xmrvsbeast can you try again with fixed diff using the latest code (p2pool only, no proxy)? It should work fine as long as you set fixed diff to less than 2 million.

**Comment by xmrvsbeast** [comment]
Thank you for your work on this.  Here are the results of your fix.

**Low hash** rigs appear to work properly now when connecting directly to p2pool

Using x+100000 to set fixed diff works and now shows proper diff in web UI and hash rate looks OK

Using no fixed diff argument also works and diff is being dynamically adjusted and displayed correctly, but the diff appears to be a bit high, getting ~ 1,600,000 diff for a 28kh/s worker

**High hash** rigs

It looks like it is working when going through xmrig-proxy with a fixed custom diff

When connecting directly to p2pool with x+ it looks like the diff is coming through but hashing never starts and workers pop in and out as if they are being engaged and disengaged again

![high_hash_p2pool](https://user-images.githubusercontent.com/79782960/131235278-64fe069b-db30-4b48-8788-783c4eea7be8.png)

Would it be possible to add a compatability mode to p2pool as a start up parameter which would change from 8-byte target for all diffs, that way it would work with MRR and nicehash?

thanks you

**Comment by SChernykh** [comment]
> Using no fixed diff argument also works and diff is being dynamically adjusted and displayed correctly, but the diff appears to be a bit high, getting ~ 1,600,000 diff for a 28kh/s worker (might be OK, but it is on the high end)

Without fixed diff you get p2pool side-chain difficulty which adjust to 10 seconds/block for combined hashrate of p2pool, so this is correct.

> Would it be possible to add a compatibility mode to p2pool as a start up parameter, or better yet on a per miner basis, which would change from 8-byte target for all diffs, that way it would work with MRR, nicehash and all miners where diff might need to be very high, dynamically adjusted and have no 8-byte target support?

Yes, but difficulties above 2 million have low precision with 4-byte format and you start losing a noticeable amount of hashrate because of that. It's better to fix even high hashrate rigs at 2 million. Stratum server can handle a lot of submitted shares per second and it will check and process shares that are good enough to mine a block.

**Comment by SChernykh** [comment]
Actually diff up to 4 million should be fine, but if you go above that, you'll be losing > 0.1% of the hashrate. I changed the limit to 4 million.

**Comment by SChernykh** [comment]
The optimal solution would be for MRR to support 8-byte format. I see 200 MH/s rig there that says optimal difficulty up to 12G. It's impossible with 4-byte format. I think it's more of a display problem there, rigs will still be mining at their speed.

**Comment by xmrvsbeast** [comment]
> The optimal solution would be for MRR to support 8-byte format. I see 200 MH/s rig there that says optimal difficulty up to 12G. It's impossible with 4-byte format. I think it's more of a display problem there, rigs will still be mining at their speed.
> 
> Edit: Even with this 200 MH/s rig, difficulty 4000000 means ~50 shares per second. p2pool will handle it easy.

Yes, you are most likely correct but the rig owners there will not like to see MRR crediting them for a fraction of the hash rate ;)

So once they upgrade their proxies you will have to change the code back?  It might be better to have a compatibility mode so you do not have to modify code again later on?  

anyway, thanks for working on it so quickly

**Comment by SChernykh** [comment]
Just set fixed diff for miners to 4000000 if it's the problem with high hashrate miners there. MRR should really fix it on their side.

**Comment by xmrvsbeast** [comment]
> Just set fixed diff for miners to 4000000 if it's the problem with high hashrate miners there. MRR should really fix it on their side.

OK, works for me.
