### ISSUE TITLE
How xmrig connects multiple ports

### ISSUE THREAD

**Issue by JieSinTime** [SChernykh/p2pool#30]
Apart from the 3333 connection port, how to open multiple ports

**Comment by QuickBASIC** [comment]
This may be something you need to do independent of p2pool. 

For example on Windows you could use (not tested):
`netsh interface portproxy add v4tov4 listenaddress=127.0. 0.1 listenport=7777 connectaddress=127.0.0.1 connectport=3333`

Or on Gnu/Linux this would probably be done with ufw or iptables.

**Comment by JieSinTime** [comment]
Is it possible to add a config.json file for related configuration

**Comment by trasherdk** [comment]
Having a hard time imagine why, but I'd probably go with multiple instances of p2pool listening on a port each.
Or
Setting up a stratum proxy for multiple xmrig to a single p2pool.
