### ISSUE TITLE
Host 127.0.0.1:18081:ZMQ:18083 seems to be stuck

### ISSUE THREAD

**Issue by wxysystem32** [SChernykh/p2pool#302]
how to fix this issue?
p2pool ver:v3.10,Windows 64,run command:e:\monero-gui-v0.18.0.0\p2pool-v2.2.1-windows-x64\p2pool.exe --host 127.0.0.1 --no-cache --mini --wallet xxxx

Host 127.0.0.1:18081:ZMQ:18083 seems to be stuck, reconnecting�[0m
mstopping�[0m
mmonitor thread stopped�[0m
mworker thread stopped�[0m
mstopped�[0m
mconnected to tcp://127.0.0.1:59865�[0m
mconnected to tcp://127.0.0.1:18083�[0m
mworker thread ready�[0m
mmonitor thread ready�[0m
;31mHost 127.0.0.1:18081:ZMQ:18083 seems to be stuck, reconnecting�[0m
mstopping�[0m
mmonitor thread stopped�[0m
mworker thread stopped�[0m
mstopped�[0m
mconnected to tcp://127.0.0.1:65258�[0m
mconnected to tcp://127.0.0.1:18083�[0m
mworker thread ready�[0m
mmonitor thread ready�[0m
;31mHost 127.0.0.1:18081:ZMQ:18083 seems to be stuck, reconnecting�[0m
mstopping�[0m
mmonitor thread stopped�[0m
mworker thread stopped�[0m
mstopped�[0m
mconnected to tcp://127.0.0.1:58662�[0m
mconnected to tcp://127.0.0.1:18083�[0m
mworker thread ready�[0m
mmonitor thread ready�[0m
;31mHost 127.0.0.1:18081:ZMQ:18083 seems to be stuck, reconnecting�[0m
mstopping�[0m
mmonitor thread stopped�[0m
mworker thread stopped�[0m
mstopped�[0m
mconnected to tcp://127.0.0.1:56627�[0m
mconnected to tcp://127.0.0.1:18083�[0m
mworker thread ready�[0m
mmonitor thread ready�[0m
;31mHost 127.0.0.1:18081:ZMQ:18083 seems to be stuck, reconnecting�[0m
mstopping�[0m
mmonitor thread stopped�[0m
mworker thread stopped�[0m
mstopped�[0m
mconnected to tcp://127.0.0.1:49353�[0m
mconnected to tcp://127.0.0.1:18083�[0m
mworker thread ready�[0m
mmonitor thread ready�[0m
;31mHost 127.0.0.1:18081:ZMQ:18083 seems to be stuck, reconnecting�[0m
mstopping�[0m
mmonitor thread stopped�[0m
mworker thread stopped�[0m
mstopped�[0m
mconnected to tcp://127.0.0.1:62910�[0m
mconnected to tcp://127.0.0.1:18083�[0m
mworker thread ready�[0m

**Comment by SChernykh** [comment]
I already answered this on IRC:
> It means your Monero node can't keep up with the network. What you can do is update to the latest version (v0.18.3.2, it has some performance fixes) and probably reduce the max number of peers (--out-peers and --in-peers command line parameters)
