### ISSUE TITLE
Instead of YOUR_P2POOL_NODE_IP, can I use my domain?

### ISSUE THREAD

**Issue by PYU224** [SChernykh/p2pool#305]
Hello.
I have a question.

> To connect another mining rig to your P2Pool node, run ./xmrig -o YOUR_P2POOL_NODE_IP:3333 on that mining rig

Can my domain be used as P2POOL_NODE_IP?

**Comment by PYU224** [comment]
As a side note, can the domain of p2pool node be used with cloudflare proxy?

**Comment by SChernykh** [comment]
Yes, you can use domain names instead of IP addresses. P2Pool will use your default DNS server to resolve the domain name.

**Comment by PYU224** [comment]
Thanks.
I want to build and manage monero pool like these services.
https://xmr.nanopool.org/
https://supportxmr.com/

**Comment by PYU224** [comment]
This is addtional question.
If the domain is onion domain, can it be used as P2POOL_NODE_IP too?

**Comment by SChernykh** [comment]
XMRig can connect to onion domains: https://xmrig.com/docs/miner/tor - you have to use it with a SOCKS5 proxy.

**Comment by PYU224** [comment]
in DNS A record, "mydomain":3333.
And in xmrig setting, "./xmrig -o mydomain:3333".

Is this setting available?

**Comment by SChernykh** [comment]
Yes, XMRig can resolve domains, assuming that your DNS server or SOCKS5 proxy can resolve them. Closing it as it's not a P2Pool issue.
