### ISSUE TITLE
Correction in instructions

### ISSUE THREAD

**Issue by 48-mq** [SChernykh/p2pool#307]
The options in the readme instructions should be corrected.

From:
--add-priority-node=p2pmd.xmrvsbeast.com:18080 --add-priority-node=nodes.hashvault.pro:18080

To:
--add-priority-node=p2pmd.xmrvsbeast.com:18081 --add-priority-node=nodes.hashvault.pro:18081

**Comment by 48-mq** [comment]
And Windows batch file instructions should be corrected.

From:
%~dp0\xmrig.exe -o 127.0.0.1
To:
%~dp0\xmrig.exe -o 127.0.0.1:3333

**Comment by SChernykh** [comment]
1) No, 18080 is the correct port number for monerod to connect to
2) No need, XMRig will use port 3333 by default.
