### ISSUE TITLE
SSL-RPC

### ISSUE THREAD

**Issue by jogii2p** [SChernykh/p2pool#308]
Hey, 

is there a way to connect the P2Pool to a SSL-secured-RPC Node?
Because since my change to SSL-RPC-Node i got this Problem:

2024-06-12 14:11:14.5694 P2Pool get_info RPC request to host 127.0.0.1:18081:ZMQ:18083 failed: error Error (empty response), trying again in 1 second

I guess that happend after the SSL Change, I didn't find a command to integrate the SSL.
Is my guess right with the SSL or did i another stuff wrong?

Thanks for all, and your great tool.

**Comment by SChernykh** [comment]
P2Pool doesn't support SSL. It might be added in the future versions, but the best you can do right now is running XMRig-proxy in front of P2Pool to enable miners connecting using SSL.

I don't know if any proxy exists that supports connecting to a Monero node with SSL.

**Comment by SChernykh** [comment]
Also, since Monero node can enable SSL only on the RPC port, and not ZMQ, it makes little sense to use it with P2Pool.
