### ISSUE TITLE
Get error "segmentation fault  ./p2pool" when run on macOS Big Sur(MacBook Pro(13-inch, Late 2013))

### ISSUE THREAD

**Issue by shoguncao** [SChernykh/p2pool#309]
I download latest p2pool-v4.0-macos-x64.tar.gz from https://github.com/SChernykh/p2pool/releases/download/v4.0/p2pool-v4.0-macos-x64.tar.gz.
When I run p2pool, I receive error "segmentation fault".
My Mac and system is old(macOS Big Sur(MacBook Pro(13-inch, Late 2013))).
But MacBook Pro Late 2013 can't install lastest system.
<img width="1632" alt="企业微信截图_77c405f4-d6c5-4152-87bd-bbfc03034e58" src="https://github.com/SChernykh/p2pool/assets/1991364/7f7b7150-e031-43a0-92fb-66e48a915f0f">

**Comment by SChernykh** [comment]
Can you add `--loglevel 6` to the command line and see what P2Pool prints? The binary was compiled for macOS 10.13 or newer, so it should work on your system. I suspect that it can be some bug with LTO (Link time optimization) in the compiler that I used, I'll build a binary without it.

**Comment by SChernykh** [comment]
Can you try [this binary](https://github.com/SChernykh/p2pool/actions/runs/9745471132/artifacts/1655745882)? Don't pay attention for "macos-13" in the name - it was built on macOS 13, but built for macOS 10.13+

**Comment by shoguncao** [comment]
> Can you try [this binary](https://github.com/SChernykh/p2pool/actions/runs/9745471132/artifacts/1655745882)? Don't pay attention for "macos-13" in the name - it was built on macOS 13, but built for macOS 10.13+
I try this binary, and add --loglevel 6, but still get the same error. And the prints ars same, no details log.
<img width="1722" alt="企业微信截图_b406d867-2f59-4637-86b1-3ace127edbc2" src="https://github.com/SChernykh/p2pool/assets/1991364/aaaea90d-3ea2-47b7-afa9-c3df438d4b0e">

**Comment by SChernykh** [comment]
Hmm, what is the exact model of CPU in your Mac?

**Comment by shoguncao** [comment]
> Hmm, what is the exact model of CPU in your Mac?

Here is the output of `uname -a`
`Darwin 192.168.0.150 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64`

**Comment by SChernykh** [comment]
And what's the output of `sysctl -a | grep machdep.cpu`?

**Comment by shoguncao** [comment]
> sysctl -a | grep machdep.cpu

Here is the output of `sysctl -a | grep machdep.cpu`
```
machdep.cpu.address_bits.physical: 39
machdep.cpu.address_bits.virtual: 48
machdep.cpu.arch_perf.events: 0
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.fixed_width: 48
machdep.cpu.arch_perf.number: 4
machdep.cpu.arch_perf.version: 3
machdep.cpu.arch_perf.width: 48
machdep.cpu.cache.L2_associativity: 8
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.size: 256
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.mwait.sub_Cstates: 286531872
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.core_power_limits: 1
machdep.cpu.thermal.dynamic_acceleration: 1
machdep.cpu.thermal.energy_policy: 1
machdep.cpu.thermal.fine_grain_clock_mod: 1
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.package_thermal_intr: 1
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.data.small_level1: 64
machdep.cpu.tlb.inst.large: 8
machdep.cpu.tlb.shared: 1024
machdep.cpu.tsc_ccc.denominator: 0
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.xsave.extended_state: 7 832 832 0
machdep.cpu.xsave.extended_state1: 1 0 0 0
machdep.cpu.brand: 0
machdep.cpu.brand_string: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
machdep.cpu.core_count: 2
machdep.cpu.cores_per_package: 8
machdep.cpu.extfamily: 0
machdep.cpu.extfeature_bits: 142473169152
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT RDTSCP TSCI
machdep.cpu.extmodel: 4
machdep.cpu.family: 6
machdep.cpu.feature_bits: 9221959987971750911
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_feature_bits: 10155 0
machdep.cpu.leaf7_feature_bits_edx: 2617247232
machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 SMEP BMI2 ERMS INVPCID FPU_CSDS MDCLEAR IBRS STIBP L1DF SSBD
machdep.cpu.logical_per_package: 16
machdep.cpu.max_basic: 13
machdep.cpu.max_ext: 2147483656
machdep.cpu.microcode_version: 38
machdep.cpu.model: 69
machdep.cpu.processor_flag: 6
machdep.cpu.signature: 263761
machdep.cpu.stepping: 1
machdep.cpu.thread_count: 4
machdep.cpu.vendor: GenuineIntel
```

**Comment by SChernykh** [comment]
I thought it crashed because it didn't support BMI1, but it is a Haswell CPU with BMI1 support. Not LOT, not BMI1 that v4.0 started using, so it must be something else.

You'll have to build your own binary and run it under debugger to get a crash callstack...
https://github.com/SChernykh/p2pool?tab=readme-ov-file#macos

**Comment by shoguncao** [comment]
> I thought it crashed because it didn't support BMI1, but it is a Haswell CPU with BMI1 support. Not LTO, not BMI1 that v4.0 started using, so it must be something else.
> 
> You'll have to build your own binary and run it under debugger to get a crash callstack... https://github.com/SChernykh/p2pool?tab=readme-ov-file#macos

Yeah, my mac is too old. After half a day, I build from source follow [https://github.com/SChernykh/p2pool?tab=readme-ov-file#macos](https://github.com/SChernykh/p2pool?tab=readme-ov-file#macos), I was able to run p2pool now. Thanks.

**Comment by richardk80** [comment]
@SChernykh Let's say someone has a Mac that doesn't support BMI1 and it's using an older version of MacOS (Catalina)...what should they do to get p2pool 4.0 to work on it where it is not saying "Segmentation Fault: 11"?

**Comment by SChernykh** [comment]
P2Pool uses CPUID x86 instruction to detect BMI1 support, it will not use BMI1 on older CPUs.

**Comment by richardk80** [comment]
@SChernykh Ok...Will I be able to build p2pool 4.0 from source to work with MacOS 10.15 running on a 2013 Mac Pro? If I can then how?

**Comment by SChernykh** [comment]
Release binaries are built for macOS 10.13 and newer versions. If they don't work, then it's a bug. You can build your own binary using instructions from README.MD

**Comment by richardk80** [comment]
@SChernykh I have tried many times to build from source but I keep getting the same errors:

/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libgrpc++_error_details.a(error_details.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libgrpc++_error_details.a(error_details.cc.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: libgrpc++_error_details.a the table of contents is empty (no object file members in the library define global symbols)
[ 99%] Built target grpc++_error_details
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/stratum_server.cpp.o
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/tcp_server.cpp.o
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/util.cpp.o
In file included from /Users/ryanx30x/Desktop/p2pool/src/merge_mining_client.cpp:23:
In file included from /Users/ryanx30x/Desktop/p2pool/src/merge_mining_client_tari.h:21:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/Tari/proto.h:8:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/Tari/proto/gRPC/base_node.pb.h:20:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/protobuf/src/google/protobuf/io/coded_stream.h:108:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/protobuf/src/google/protobuf/stubs/common.h:21:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/strings/string_view.h:40:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/nullability.h:154:
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:44:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<T *>' [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<T*> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:44:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<T*> = true;
          ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:47:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<T U::*>' [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<T U::*> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:47:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<T U::*> = true;
          ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:50:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<std::unique_ptr<T, Deleter...> >'
      [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<std::unique_ptr<T, Deleter...>> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:50:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<std::unique_ptr<T, Deleter...>> = true;
          ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:53:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<std::shared_ptr<T> >'
      [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<std::shared_ptr<T>> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:53:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<std::shared_ptr<T>> = true;
          ^
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/wallet.cpp.o
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/zmq_reader.cpp.o
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/keccak_bmi.cpp.o
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/miner.cpp.o
[ 99%] Building CXX object CMakeFiles/p2pool.dir/src/merge_mining_client_tari.cpp.o
In file included from /Users/ryanx30x/Desktop/p2pool/src/merge_mining_client_tari.cpp:20:
In file included from /Users/ryanx30x/Desktop/p2pool/src/merge_mining_client_tari.h:21:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/Tari/proto.h:8:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/Tari/proto/gRPC/base_node.pb.h:20:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/protobuf/src/google/protobuf/io/coded_stream.h:108:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/protobuf/src/google/protobuf/stubs/common.h:21:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/strings/string_view.h:40:
In file included from /Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/nullability.h:154:
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:44:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<T *>' [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<T*> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:44:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<T*> = true;
          ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:47:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<T U::*>' [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<T U::*> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:47:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<T U::*> = true;
          ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:50:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<std::unique_ptr<T, Deleter...> >'
      [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<std::unique_ptr<T, Deleter...>> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:50:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<std::unique_ptr<T, Deleter...>> = true;
          ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:53:16: error: 
      no previous extern declaration for non-static variable
      'IsSupportedType<std::shared_ptr<T> >'
      [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<std::shared_ptr<T>> = true;
               ^
/Users/ryanx30x/Desktop/p2pool/external/src/grpc/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:53:11: note: 
      declare 'static' if the variable is not intended to be used outside of
      this translation unit
constexpr bool IsSupportedType<std::shared_ptr<T>> = true;
          ^
[ 99%] Linking CXX static library libgrpc++_alts.a
[ 99%] Built target grpc++_alts
4 errors generated.
make[2]: *** [CMakeFiles/p2pool.dir/src/merge_mining_client.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
4 errors generated.
make[2]: *** [CMakeFiles/p2pool.dir/src/merge_mining_client_tari.cpp.o] Error 1
make[1]: *** [CMakeFiles/p2pool.dir/all] Error 2
make: *** [all] Error 2

What can I do to fix this?

**Comment by SChernykh** [comment]
You can add `-DWITH_GRPC=OFF` to cmake command line (clean build folder first), or use a newer compiler version.

**Comment by richardk80** [comment]
@SChernykh That fixed it and I have p2pool 4.0 on my system. Thanks!

**Comment by SChernykh** [comment]
What is your compiler version? p2pool binary should show this information in the first few lines of the log when you start it. Or you can run `clang --version` in command line. If I know the version I can try to fix it.

**Comment by richardk80** [comment]
@SChernykh 

Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by SChernykh** [comment]
@richardk80 Ah, see https://github.com/SChernykh/p2pool?tab=readme-ov-file#prerequisites
I doubt that an older macOS knows about C++17.

**Comment by richardk80** [comment]
@SChernykh Ok...What should I do about that then? Would removing MacOS from the Mac Pro and replacing it with the latest Ubuntu fix that issue? Also...the thing I disabled in the build yesterday...GRPC...Is that absolutely necessary for p2pool 4.0 to function?

**Comment by SChernykh** [comment]
You can try to install newer clang version (don't ask me how, I'm not a Mac user). GRPC is required for merge mining with Tari, it's not used otherwise.

**Comment by richardk80** [comment]
@SChernykh Do I have to have GRPC working with p2pool to be able to mine after October? I tried upgrading clang and I couldn't get it to work at all. Maybe I should just get rid of MacOS on my Mac Pro and install Ubuntu 24.04 on it instead

**Comment by SChernykh** [comment]
Yes it will work after October. GRPC is required for Tari specifically.

**Comment by richardk80** [comment]
@SChernykh I'm only mining XMR so I won't be needing merge mining, which means I won't need GRPC either, so I am good to go now. Thank you again for your help
