### ISSUE TITLE
Mechanism for filtering suspicious peers

### ISSUE THREAD

**Issue by DnorthR** [SChernykh/p2pool#310]
Is it possible to provide a mechanism for forced filtering (blacklist/whitelist?) for connected peers?

For example, the peers list currently includes a suspicious instance identifying itself as "GoObserver v4.1"

**Comment by SChernykh** [comment]
That peer is p2pool.observer - it's legit.

**Comment by SChernykh** [comment]
As for banning misbehaving peers - p2pool already does that, but bans are temporary (10 minutes). If you want to ban some IP permanently, it's better to use a firewall for this. Or to set up fail2ban to parse p2pool's log for specific messages.
