### ISSUE TITLE
p2pool continues sending jobs to clients when internet is down

### ISSUE THREAD

**Issue by 2mac** [SChernykh/p2pool#319]
My ISP is pretty reliable, but I have noticed during occasional outages that my rigs keep running even when there's no way monerod or p2pool are connected to the internet. This is of course a waste of electricity as the rigs churn away at a job that is long out of date.

I know p2pool can detect when the network is down, because it won't be able to reach any peers on the sidechain. In such a condition, we should stop sending jobs to stratum clients to save energy until the net comes back up. This is sort of halfway done already, because if you start p2pool during an outage, it doesn't send any jobs until it establishes a connection to the sidechain. We just need to go back into that loop when the connection is lost later.

**Comment by SChernykh** [comment]
As long as P2Pool Stratum port is up and running and there are miners connected to it, they will get jobs from it. If P2Pool doesn't send new jobs during outages, miners will just keep mining old jobs. Stratum protocol doesn't have an option for the server to send "stop" command to miners, except for simply disconnecting them.

P2Pool does send jobs before syncing the sidechain, but these jobs will mine an alternative sidechain.

**Comment by SChernykh** [comment]
So what you actually want if for p2pool to disconnect all Stratum connections and refuse new Stratum connections until it reconnects to the sidechain?

**Comment by viktor4096** [comment]
For example, whenever you're solo mining, XMRig shows the message "the core us busy syncing" and sends no job. Similar feature would be much appreciated with P2Pool.

**Comment by SChernykh** [comment]
I will make P2Pool send an error message to XMRig and then disconnect in case P2Pool loses connection to its Monero node, or to all P2Pool peers.

**Comment by SChernykh** [comment]
Added it in https://github.com/SChernykh/p2pool/commit/02006e1b50c32b418029aa30e8513e8ad5e6e50b - this will be available in v4.2
