### ISSUE TITLE
monerod sync Error

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#32]
Hi,
I am syncing monerod through powershell command and completed about 85% then it starts giving below error. 
"Failed to get top block hash to check for new block's parent: MDB_NOTFOUND: No matching key/data pair found" as well as its blocking all peers one by one.
Please advise to solve it. 
![Sc-1](https://user-images.githubusercontent.com/84818069/134406641-3a360095-6326-4b74-8f68-93f601e3d2d7.jpg)

**Comment by lalanza808** [comment]
This is not an issue with p2pool, it's an issue with Monerod. Issues exist for this. On first glance I'd say your monerod DB is corrupted. Best to just wipe it and start fresh. Check the monero project issues for other responses to see what else you can do: https://github.com/monero-project/monero/issues/1598

**Comment by syedalihashmi2016** [comment]
Thanks for the reply. I was thinking the same and I did same steps you told. Now I am downloading the pruned node and its almost completed.
