### ISSUE TITLE
Error: "P2PServer failed to save peer list" when the amount of xmrig minners is over than almost 900 

### ISSUE THREAD

**Issue by shoguncao** [SChernykh/p2pool#320]
I am runing p2pool on my own server, and run xmrig minners on other mechines with the 3333 port of my p2pool server.
I found that when the amount of my xmrig minners exceed 900, my p2pool server output an error "P2PServer failed to save peer list"
How to fix this?
![p2poolerror](https://github.com/user-attachments/assets/713d6c90-209e-471c-aa03-9f48a43754d1)

**Comment by shoguncao** [comment]
I am pretty sure that when the amount of xmrig minner is lower than 900, my p2pool server won't output this error.

**Comment by SChernykh** [comment]
P2Pool couldn't open a file. Taking into account that everything is a file in Linux, and you have over 900 connections, you're likely hitting the default open files limit in (1024). See https://www.tecmint.com/increase-set-open-file-limits-in-linux/

**Comment by shoguncao** [comment]
> P2Pool couldn't open a file. Taking into account that everything is a file in Linux, and you have over 900 connections ("files"), you're likely hitting the default open files limit in Linux (1024 files). See https://www.tecmint.com/increase-set-open-file-limits-in-linux/

Yes! You are right. Thanks for your help!
When I use ulimit -Sn 25000 to set Soft Limits to a large number, and rerun p2pool, all is ok, no error occur.

**Comment by SChernykh** [comment]
This will also help you to have more than 900-1000 miners connected at the same time.
