### ISSUE TITLE
Mining Rigs Rental Config

### ISSUE THREAD

**Issue by thealidev** [SChernykh/p2pool#322]
I like to ask if i can set somehow mining rigs rental with it
For node i can self host it
But i don't have a pc to mine greatly
So i like to use rented hash to mine
I am currently looking for a method myself using ngrok 
The problem is now complete pathemeters
I will create a pr if found any solution
If devs have any solution i would appreciate it

**Comment by SChernykh** [comment]
You can use MRR, it works with P2Pool. Point it at your Stratum IP:port. You might need to set a fixed difficulty for the miner - `-u x+1000000` in XMRig command line to set difficulty at 1,000,000 (for example). Don't set difficulty higher than 4,000,000 because it's incompatible with MRR.

**Comment by thealidev** [comment]
What should i write in username and password

**Comment by thealidev** [comment]
@SChernykh

**Comment by SChernykh** [comment]
User name `x+1000000` (where 1000000 is the difficulty for mining rigs), password can be empty.

**Comment by thealidev** [comment]
![Screenshot_20241027_233906](https://github.com/user-attachments/assets/7a43053a-6ae8-4129-977d-f34bae9fb656)
Like this ????

**Comment by SChernykh** [comment]
Yes, like this. But P2Pool Stratum port is 3333 by default, not 8080.

**Comment by thealidev** [comment]
Ok
Let it suppose ip:3333
Is it ok now

**Comment by thealidev** [comment]
Ok
Let it suppose ip:3333
Is it ok now

**Comment by thealidev** [comment]
And is it NiceHash complible
And can i make it's documentary on `RadMe.md` file so who are curious about this also get help

**Comment by thealidev** [comment]
@SChernykh

**Comment by SChernykh** [comment]
Of course it's compatible with everything because it implements the standard Monero Stratum protocol.
