### ISSUE TITLE
Issues with config and data files

### ISSUE THREAD

**Issue by toxicroadkill** [SChernykh/p2pool#323]
when launching p2pool, it creates the log file, cache, and peers file from whatever directory you start it from

there should be a option to specify where it places it's "data" files, as well as the log file

also the option for --config (file), what is the format of the config file? json, text/?? ive tried both with no luck

it would be nice to start a service with a simple command line with p2pool specifying the config file and in the config hold all the needed info wallet address, log file, data file/etc 

thanks

**Comment by SChernykh** [comment]
config.json is only used if you want to mine on your own P2Pool chain (not `main` or `mini` chains). See https://github.com/SChernykh/p2pool/blob/master/config.json for an example.

You can run p2pool as a service and you can pass all parameters in the command line: https://github.com/SChernykh/p2pool/blob/master/docs/SYSTEMD.MD

You can run it as a service on Windows too, but you'll have to set it up manually.

As for the working directory for all P2Pool files, you can set it up in service parameters (Windows) or set it within the launch script (Linux). Having it as a command line parameter can be another option, but it's not implemented yet.

**Comment by toxicroadkill** [comment]
how about setting up a config file, so that you can put all the config in it, and not have to use long command lines to start it..for example, just passing a config file path, so you can have all the config info there
makes editing and dealign with things so much easier..parsing a json file with config in it would be super easy

just a thought..with numerous options available having to put them all in a command line, is error prone, nad results in just a massive long cli entry

it would be very appreciated..

**Comment by toxicroadkill** [comment]
Also, a config option to put the log file and data files where you wish would be great also

Log-file-location /var/log/p2pool.log
Data-file-location /whatever/daa_file.txt

^ you get the idea..just makes a much cleaner and easier to setup system

thanks

**Comment by viktor4096** [comment]
A workaround of this problem is to `cd` into the directory of your choice, then run the P2Pool binary.

But yes, having the option similar to `monerod` 's `data-dir` and `log-file` would be a great QoL improvment.

**Comment by toxicroadkill** [comment]
hopefully this can be added, that would be great..as well as having a config file, so you dont have a command line that could end up super long

a typical json config file would also be a huge huge improvement

**Comment by SChernykh** [comment]
v4.3 added `--data-dir` parameter, and renamed the confusing `--config` parameter.

**Comment by toxicroadkill** [comment]
thank you ..thank you..thank you..
