### ISSUE TITLE
Do I have to use the newly applied wallet address every time I mine

### ISSUE THREAD

**Issue by luckytalk** [SChernykh/p2pool#324]
After I reinstall my server, do I need to use the new wallet address to mine

**Comment by luckytalk** [comment]
I use p2pool v4.11 to mine successfully, and v4.2 has never been successful

**Comment by Kellytimmins** [comment]
Hello @luckytalk 
If you reinstall your server, you generally don't need a new wallet address to continue mining. Your existing wallet address should still be valid. Just make sure to reconfigure your mining software to point to the correct address and server settings.

**Comment by luckytalk** [comment]
I have been mining in the following ways for another month without any progress:
./monerod --zmq-pub tcp://127.0.0.1:18083 --out-peers 32 --in-peers 64 --add-priority-node=p2pmd.xmrvsbeast.com:18080 --add-priority-node=nodes.hashvault.pro:18080 --disable-dns-checkpoints --enable-dns-blocklist
./p2pool --host 127.0.0.1 --wallet MY_WALLET_ADDRESS
./xmrig -o YOUR_P2POOL_NODE_IP:3333
What could be the reason?

**Comment by SChernykh** [comment]
You need to check what does `status` command output in p2pool. Also check for warnings/errors in p2pool log.

**Comment by luckytalk** [comment]
My last profit was 39 days ago,Since the P2POOL version was upgraded to V4.2, my mining has never benefited.Is this related to the version of P2POOL?

**Comment by SChernykh** [comment]
Did you check what I asked for? You can also check your wallet address at https://p2pool.observer/
What's your hashrate?

**Comment by luckytalk** [comment]
Checked, no abnormal alarm

**Comment by luckytalk** [comment]
https://p2pool.observer/Just told me that I got the share 39 days ago, and there was no more detailed information

**Comment by SChernykh** [comment]
What does `status` command show? What is your hashrate? I'm tired of repeating these questions. Maybe your hashrate is so low and luck is so bad that you haven't found a share in 39 days on p2pool-main, or maybe you have some misconfiguration. I can't tell.
