### ISSUE TITLE
TLS does not work with RSA larger than 1024

### ISSUE THREAD

**Issue by DyJohnnY** [SChernykh/p2pool#327]
I learned kind of the hard way, after some hours of troubleshooting that if you generate a certificate with a key size over 1024, p2pool will not work with it, it will start ok, but any connection is reset.
The error that shows  is:
`OpenSSL: error:0A000126:SSL routines::unexpected eof while reading`

The certificate that is generated by default with p2pool is  RSA:512, but 1024 also seems to work. Nothing more beyond that.

Is this something that can be improved in the future?

**Comment by SChernykh** [comment]
Default certificate generated by p2pool uses EC cryptography, not RSA. EC has shorter keys than RSA.

**Comment by SChernykh** [comment]
@DyJohnnY Can you try to build the latest P2Pool code? A similar bug was fixed recently https://github.com/SChernykh/p2pool/commit/86962eb7aa90665cbf7d6f993264129c81ec52ef

**Comment by SChernykh** [comment]
It should be fixed in v4.3

**Comment by shortwavesurfer2009** [comment]
So p2pool works with ssl rpc now?

**Comment by SChernykh** [comment]
> So p2pool works with ssl rpc now?

No, it's only Stratum SSL for now. SSL RPC is in my to-do list.

**Comment by shortwavesurfer2009** [comment]
> > So p2pool works with ssl rpc now?
> 
> No, it's only Stratum SSL for now. SSL RPC is in my to-do list.

Looking forward to it as I want to force my wallet RPC connections to be over SSL always

**Comment by SChernykh** [comment]
@shortwavesurfer2009 RPC-SSL support added, you can try to build the latest code to test it.
