### ISSUE TITLE
[feature request]: Status of synchronization in data API

### ISSUE THREAD

**Issue by Cyrix126** [SChernykh/p2pool#328]
In the case you have no access to the terminal output but only through the data API, you have no way to know if the p2pool node is synchronized

The data API could provide an additional json field "status" that could provide the following possible values: 
"disconnected"
"synchronizing"
"synchronized"

**Comment by SChernykh** [comment]
"disconnected" is the same as `"connections":0` in the `local/p2p` json
Synchronized can be deduced from `api/pool/stats` json - check `sidechainHeight` there.

**Comment by Cyrix126** [comment]
Thanks. That is solving the problem indeed (if sidechainHeight is 0, it's still syncing right ?).

If the monero node became offline, is there a field that can inform me about this ?

**Comment by SChernykh** [comment]
No, there is no direct field for this. You can only check the last network height and timestamp received by p2pool from monerod in `api/network/stats`, and compare it with other sources. I will add a field that shows time passed since the last message from monerod (any block or transaction notification) - if it's more than 1-2 minutes ago, the node is stuck/disconnected.

**Comment by SChernykh** [comment]
Added in https://github.com/SChernykh/p2pool/commit/fb0dc586b2c1f5b8ef650121069324c5fe806cf6

**Comment by SChernykh** [comment]
```
if sidechainHeight is 0, it's still syncing right ?
```
When synced, sidechain height is around ~10 million. While still syncing, it can be 0, 1, 2, ... (some small number) - depending on how fast you connected miners can mine blocks with 100k difficulty.

**Comment by SChernykh** [comment]
> Added in [fb0dc58](https://github.com/SChernykh/p2pool/commit/fb0dc586b2c1f5b8ef650121069324c5fe806cf6)

Replaced it with https://github.com/SChernykh/p2pool/commit/00b6dabc782ccd64acdc699d56bf842b96a35aad because this JSON file is updated more often.
