### ISSUE TITLE
Custom difficulty setting? low hashrate

### ISSUE THREAD

**Issue by westz36** [SChernykh/p2pool#35]
2021-09-26 07:23:11.9384 SideChain status                                          Main chain height         = 2457685
Main chain hashrate       = 2.696 GH/s                                             Side chain height         = 218674                                                 Side chain hashrate       = 73.259 MH/s
**### Your hashrate (pool-side) = 32.440 KH/s**                                            PPLNS window              = 2160 blocks (+75 uncles, 0 orphans)                    
Your shares               = 1 blocks (+0 uncles, 0 orphans)                        Your shares position      = [.........................1....]                       
Block reward share        = 0.044% (0.000377939906 XMR)  

Hello,

Im moving from monero pool to p2pool, the instructions for setup works good. Thanks!

Ran into a problem with low hashrate.

- My hashrate on monero pool is around 43-44kh, very stable. (14.5kh per miner)
- Ran p2pool on my node for about 24hours non stop, only getting around 32.44KH (shown above)

The current difficulty setting is left default :
[2021-09-26 00:26:53.881]  net      new job from 192.168.1.121:3333 diff 748M algo rx/0 height 2457686  

Is the low hashrate a result of low difficulty target? 

Any tips on calculating what difficulty to set?

thanks!

**Comment by SChernykh** [comment]
Your pool-side hashrate depends on how many pool shares you find and it depends highly on luck. Check stratum server statistics instead. Also set lower difficulty for your rigs (add `-u x+400000` to the command line or `"user": "x+400000",` in config.json)

**Comment by westz36** [comment]
> 
> 
> Your pool-side hashrate depends on how many pool shares you find and it depends highly on luck. Check stratum server statistics instead. Also set lower difficulty for your rigs (add `-u x+400000` to the xmrig's command line or `"user": "x+400000",` in config.json for xmrig)

Thanks for the quick reply!

I made the difficulty change, and my hashrate seems to be more realistic now.

2021-09-26 08:19:48.7827 StratumServer status                                      
Hashrate (15m est) = 47.439 KH/s                                                   Hashrate (1h  est) = 9.655 KH/s                                                    Hashrate (24h est) = 29.188 KH/s         
Total hashes       = 2356040822                                                    Shares found       = 3                                                             Average effort     = 100.000%         
Current effort     = 4.352%                                                        Connections        = 3 (3 incoming)

**Comment by paperkut1** [comment]
> > Your pool-side hashrate depends on how many pool shares you find and it depends highly on luck. Check stratum server statistics instead. Also set lower difficulty for your rigs (add `-u x+400000` to the xmrig's command line or `"user": "x+400000",` in config.json for xmrig)
> 
> Thanks for the quick reply!
> 
> I made the difficulty change, and my hashrate seems to be more realistic now.
> 
> 2021-09-26 08:19:48.7827 StratumServer status
> Hashrate (15m est) = 47.439 KH/s Hashrate (1h est) = 9.655 KH/s Hashrate (24h est) = 29.188 KH/s
> Total hashes = 2356040822 Shares found = 3 Average effort = 100.000%
> Current effort = 4.352% Connections = 3 (3 incoming)

What command do you use to check the stratum server status? Thanks

**Comment by paperkut1** [comment]
> Your pool-side hashrate depends on how many pool shares you find and it depends highly on luck. Check stratum server statistics instead. Also set lower difficulty for your rigs (add `-u x+400000` to the xmrig's command line or `"user": "x+400000",` in config.json for xmrig)

Does changing difficulty impact the luck on finding a share or is it just for optics so you see a realistic hash rate?
Also does this seem like a fair assumption for finding difficulty target for each rig?
28K difficulty per 1 KH/s

**Comment by syedalihashmi2016** [comment]
> > Your pool-side hashrate depends on how many pool shares you find and it depends highly on luck. Check stratum server statistics instead. Also set lower difficulty for your rigs (add `-u x+400000` to the xmrig's command line or `"user": "x+400000",` in config.json for xmrig)
> 
> Does changing difficulty impact the luck on finding a share or is it just for optics so you see a realistic hash rate?
> Also does this seem like a fair assumption for finding difficulty target for each rig?
> 28K difficulty per 1 KH/s

Can Anybody please answer it as it seems serious question?

**Comment by QuickBASIC** [comment]
> Can Anybody please answer it as it seems serious question?

Please consider the fact that this is an open source project that is mostly the labor of love of a single person. Other people (like me) that want to support the project may answer, but please be patient or ask questions in #monero-pow or #p2pool-log on Libera.chat.

> Does changing difficulty impact the luck on finding a share or is it just for optics so you see a realistic hash rate?

Changing your diff in xmrig has no impact on your actual shares in p2pool or impact your payout. It just makes xmrig show "share accepted" at regular intervals and makes your 'StratumServer' output from 'status' in p2pool more accurate.

> What command do you use to check the stratum server status? Thanks

In the p2pool window type 'status' and press enter (no quotes).
