### ISSUE TITLE
Not getting any reward share with 14k speed

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#39]
Hi,
i am Mining like solo because not found any reward share since 20 Hrs with 14k speed. I restarted all binaries but nothing happened since 2 hours. Please advise. 
![Screenshot (2)](https://user-images.githubusercontent.com/84818069/134818989-f10afaee-7d87-4c6d-ace8-7426e85d8f25.png)
![Screenshot (3)](https://user-images.githubusercontent.com/84818069/134818991-0a6acfc1-d709-432b-b400-ebf506d3fcf8.png)

**Comment by SChernykh** [comment]
It takes 17 hours on average to find a pool share with your hashrate. If your luck is bad, it can take 3-4 times more. You'll get a payout when you find at least 1 share and pool finds a block with your shares in PPLNS window.

**Comment by syedalihashmi2016** [comment]
Thanks. I will wait to see if my luck getting better.
