### ISSUE TITLE
How a noob will know that p2pool features mentioned are available

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#42]
Hi,
Thanks for your efforts to make this pool open for all who dont want to pay pool fee in other pools but This is important to satisfy all. Everyone need to know who is getting what from this pool?

 As mentioned I am noob and 
![Screenshot (4)](https://user-images.githubusercontent.com/84818069/134956752-e777f8b9-abab-4bc3-9432-537d94db66d5.png)
![Screenshot (5)](https://user-images.githubusercontent.com/84818069/134956758-87eb963a-e78a-423e-990a-b0c9926b75f6.png)
wonder that all other pools specially 2miners.com shows detailed miner stats but I dont see anything about reward distribution and miner statics on p2pool website. Why should I check p2pool logs to find details if stats are available on pool website. P2pool should include below in pool website.

1- All Miners with their Incomplete Wallet Address like 2miners.com
2- All miners with their hashrate and shares they got from the mined blocks.

**Comment by QuickBASIC** [comment]
Hi, there's an effort by another developer to make some of this data available [here](https://p2pool.observer/). Keep in mind that p2pool it's not centralized and therefore there's no data being kept by a pool somewhere that can be displayed in this manner.

**Comment by syedalihashmi2016** [comment]
Hi Boss!

Yah. That's what I was talking about. Thanks for sharing it. Now I can check the stats easily.
