### ISSUE TITLE
Pool Observer Shows no share since 8 Hours and hashrate big variations

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#43]
![Screenshot (6)](https://user-images.githubusercontent.com/84818069/135003113-ec0dc85b-96d3-41f1-98b7-848afba1e6c8.png)

**Comment by QuickBASIC** [comment]
The p2pool.observer site is not written by or run by the dev of p2pool. If you feel there is some issue you should open the ticket on the appropriate repo. https://github.com/WeebDataHoarder/p2pool-log or reach out to the dev in #p2pool-log on Libera.chat.

The reason you're seeing hashrate variations for your address is that it only considers only your actual p2pool shares, meaning if you're lucky and find a few shares in a short period of time, it's going to seem really high and if you're unlucky and only find a few shares in a long period of time. 

When you're running xmrig with a lower diff set, you're seeing an average over a lot of "fake" shares which makes it more accurate in a way, but less accurate in another.

**Comment by syedalihashmi2016** [comment]
I understand and pool observer also not showing my hash rate but I observed  in P2Pool Status check which is showing 32 shares whereas I got 3 or 4 since 3 days. Moreover, still no block share since 15 hours
