### ISSUE TITLE
I have same issue Custom difficulty setting? low hashrate

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#44]
Hi, I need to know what is an ideal difficulty setting for 1Kh/S ?

**Comment by QuickBASIC** [comment]
Hi, for simple questions like this  in the future try to ask in #monero-pow or #p2pool-log on Libera.chat.

> Hi, I need to know what is an ideal difficulty setting for 1Kh/S ?

Your diff has no impact on your actual shares found, but if you want your stats to be accurate, many will suggest (30 x your expected hashrate), so 30x1000 = 30000.

**Comment by syedalihashmi2016** [comment]
Thank You.
