### ISSUE TITLE
If it is Decentralized?

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#45]
Then why all rewards are going to one wallet? 
![Screenshot (7)](https://user-images.githubusercontent.com/84818069/135003660-b8f1c7ae-4921-4913-a34f-46886a77a6ca.png)

**Comment by QuickBASIC** [comment]
Hi for simple questions like this in the future you can ask in #monero-pow or #p2pool-log on Libera.chat.

> If it is Decentralized? Then why all rewards are going to one wallet?

Because one person is contributing a substantial amount of hashrate to p2pool and therefore has many shares in the PPLN window when a block is found. This is no different than a centralized pool using the same payout scheme with the same distribution of hashrate amongst it's miners. In that case the miner with a larger contribution would get a larger portion of the payout.

It's decentralized because people mining to p2pool need to mine block templates that contain payouts for everyone with a share in the PPLNS window otherwise their shares will be rejected by other p2pool nodes.

**Comment by syedalihashmi2016** [comment]
Hi, 
I will refrain as you advise but still I am unable to understand it, see I am mining in P2Pool since three days with avg 12kh/s and all I get are three or four block shares instead all pool blocks share in this period. If it is PPLNS then all miners should get the share with each block mined?

Before I was mining on MINEXMR and 2Miners and I observed we get PPLN share on each block. And BTW what I got reward here is less then I would get in minexmr.  So I am confused like I am mining half of the time solo with no reward and half of the time with reward.

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool#how-pplns-works-in-p2pool
Also, don't spam github - leave your question in 1 issue. Your hashrate will give you 1 pool shares every 15 hours on average. Average means it's not guaranteed. You can get several shares in a few hours, or you can get 1 share after 48 hours. It's random, but it averages out. In the long run, your payout will be the same as on other pools. Long run = at least a month.

**Comment by syedalihashmi2016** [comment]
Thanks for the information. I already apologize for opening more than one issue which will not repeat I promises. But still I am not satisfied with your answer. you are telling me that the rewards will be less or equal then other pools means what?  
is it mean this all is useless because I stopped mining on my PC for 3 days to create a new wallet, setup and sync the specific monerod even I had a full node on another PC then I passionately wait further 3 days to see what are the results which are not as mentioned in pool features, and then when I open these issues, instead getting some resolution, I am being called as spammer so shall I consider this pool is not for noobs like me and only beneficial for its contributors?

**Comment by syedalihashmi2016** [comment]
> > Hi,
> > I will refrain as you advise but still I am unable to understand it, see I am mining in P2Pool since three days with avg 12kh/s and all I get are three or four block shares instead all pool blocks share in this period. If it is PPLNS then all miners should get the share with each block mined?
> > Before I was mining on MINEXMR and 2Miners and I observed we get PPLN share on each block. And BTW what I got reward here is less then I would get in minexmr. So I am confused like I am mining half of the time solo with no reward and half of the time with reward.
> 
> what is ur difficulty setting? i had similar problem before

its about 14K and I am getting frequent block found messages but no share?
![Screenshot (9)](https://user-images.githubusercontent.com/84818069/135036931-edcf011a-00b5-4100-8614-924e78689325.png)

**Comment by SChernykh** [comment]
> you are telling me that the rewards will be less or equal then other pools means what?

This is not what I told. I told the rewards will be the same. You will get a share eventually. I myself mine there with 8 kh/s and I get payouts almost every day.

**Comment by syedalihashmi2016** [comment]
> > you are telling me that the rewards will be less or equal then other pools means what?
> 
> This is not what I told. I told the rewards will be the same. You will get a share eventually. I myself mine there with 8 kh/s and I get payouts almost every day.

I really respect your great work and efforts for the community and I am not a critic, I am just not getting the point what is beneficial for me in this pool? because still my status showing no share since 20 hrs But I am closing this issue now and will wait further as advised by you.
