### ISSUE TITLE
Please provide a Detailed Guide for Noobs 

### ISSUE THREAD

**Issue by syedalihashmi2016** [SChernykh/p2pool#46]
Hi, 
It would be better if you post a detailed guide setting up P2Pool on Windows from download binaries to setting up and then monitor. We don't know how to build and set up. Moreover, will appreciate if provide hints on setting up custom diff on xmrig and xmrig proxy. Thanks

**Comment by QuickBASIC** [comment]
Hi syed. You've opened 4 issues in the last hour for simple questions. Github issues are not a discussion board or forum. Please refrain from opening any more issues.

If you need more help setting up p2pool than provided in the readme, then you should reach out on IRC #monero-pow or #p2pool-log and maybe someone there can help you with your specific issues/questions/errors.

I suggest you re-read the detailed instructions [here](https://github.com/SChernykh/p2pool#windows-1). You literally just have to run 3 executables with the parameters supplied. There's even an example batch script to launch them that you can put directly in the folder from the release.

**Comment by syedalihashmi2016** [comment]
Hi, 
Apology for not knowing the right way to discuss and open issues here. I will now take care of it and close.
