### ISSUE TITLE
Can't be compiled. 

### ISSUE THREAD

**Issue by balsaboskovic** [SChernykh/p2pool#47]
Hi, I've tried to compile monerod on multiple Linux distros but no success.
I got this:
<img width="977" alt="Screenshot 2021-09-29 at 11 16 30" src="https://user-images.githubusercontent.com/91014346/135240639-203db1b1-54ee-454b-855f-dc166f7dbc4e.png">

**Comment by SChernykh** [comment]
Scroll up to the actual error message that says `error: ...` in compilation log. I don't see any specific error here.

**Comment by balsaboskovic** [comment]
<img width="1235" alt="Screenshot 2021-09-30 at 09 51 57" src="https://user-images.githubusercontent.com/91014346/135410823-01b1787e-12a8-4b22-8060-9da8252ba2c1.png">

**Comment by SChernykh** [comment]
You just run out of memory when compiling. Try to compile with 1 thread (add `-j1` to make command for monerod).

**Comment by balsaboskovic** [comment]
That fixed the problem, can I use --prune-blockchain with p2pool?

**Comment by SChernykh** [comment]
> can I use --prune-blockchain with p2pool?

Yes

**Comment by balsaboskovic** [comment]
Thank you. One more question, is there a web panel for monitoring hash rate or something like that?

**Comment by SChernykh** [comment]
There's https://p2pool.io/ and https://p2pool.observer/

**Comment by balsaboskovic** [comment]
Thank you very much.
