### ISSUE TITLE
Ubuntu Compile Errors

### ISSUE THREAD

**Issue by gaga9999** [SChernykh/p2pool#50]
Please help !
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
UV_LIBRARY
    linked by target "p2pool" in directory /home/f/a/monero/p2pool
UV_LIBRARY_DEBUG
    linked by target "p2pool" in directory /home/f/a/monero/p2pool
ZMQ_LIBRARY
    linked by target "p2pool" in directory /home/f/a/monero/p2pool
ZMQ_LIBRARY_DEBUG
    linked by target "p2pool" in directory /home/f/a/monero/p2pool

-- Configuring incomplete, errors occurred!
`

**Comment by SChernykh** [comment]
Did you run
```
sudo apt update && sudo apt install git build-essential cmake libuv1-dev libzmq3-dev libsodium-dev libpgm-dev libnorm-dev libgss-dev
```
before compiling?

**Comment by gaga9999** [comment]
but thats for the monero compile, i have a problem with the p2pool compile.

btw solved the  binariy problem, its a special monerod version needed (is described)

**Comment by bladedoyle** [comment]
I believe this issue can be closed.
