### ISSUE TITLE
Buil for old OSX

### ISSUE THREAD

**Issue by erdnaxela02** [SChernykh/p2pool#52]
The last Release is built for OSX 10.15 and cannot be used on 10.13.
when I build it myself from the source I have an error "couldn't allocate RandomX cache, aborting. Abort trap: 6"
what does it correspond to?

**Comment by SChernykh** [comment]
> couldn't allocate RandomX cache, aborting

You don't have enough free memory on your computer. Try to add `--light-mode` to p2pool command line.
