### ISSUE TITLE
how to set payout threshold, how to view reached payout amount?

### ISSUE THREAD

**Issue by gaga9999** [SChernykh/p2pool#53]
thanks!

**Comment by SChernykh** [comment]
There's no payout threshold. Read https://p2pool.io/#faq please before asking more questions.

**Comment by gaga9999** [comment]
1) yes thanks, but you write: "threshold as low as"

2) how do i check progress on my own? https://p2pool.observer/ provides a possibility but it must be possible locally?

**Comment by gaga9999** [comment]
yes thanks, but not my progress

**Comment by SChernykh** [comment]
https://p2pool.observer/ shows your progress - all shares and payouts to your address. As long as you didn't find any share, there's 0 progress and it can take time. Before you find a share, you can only watch stratum server hashrates and your personal effort % for a pool share in the "status" command.

**Comment by SChernykh** [comment]
Shares found is kind of progress, but you can also see it on p2pool.observer. Effort % is not progress, but effort % and hashrates over 15m/1h/24h is what you can check before you find shares. You're not guaranteed to find a share when it reaches 100%. You can find a share at 20% if you're lucky or at 500% if you're unlucky.
