### ISSUE TITLE
miner statistics showing 0 hash rate at p2pool.observer

### ISSUE THREAD

**Issue by ricardoalonso** [SChernykh/p2pool#54]
Several times when I look at the p2pool.observer, my hash rate is showing zero, but then I check my monerod, p2pool and workers, and all are working fine. I can see on the logs the jobs been allocated and the hash rate of the workers. 

Also I checked and my IP isn't banned. Any ideas?

**Comment by Qu4ndo** [comment]
https://github.com/SChernykh/p2pool/issues/53#issuecomment-939255633

As long as there is no share (active), no hashrate is shown.
Also i think the hashrate is calculated with the difficulty and not your actual hashrate data.
