### ISSUE TITLE
Connect to p2pool on the same network but not on the same computer.

### ISSUE THREAD

**Issue by nmateo** [SChernykh/p2pool#60]
Hey, just a little issue here, i have correctly setup p2pool and monero daemon on my laptop and now i want to mine from another computer on the same network, but when i do:

> sudo ./xmrig -o 127.0.0.1:3333

It works on the laptop i'm running the node/p2pool but it doesn't work from my other computers on the same network, could you help me?

**Comment by iGetSchwifty** [comment]
You need to change 127.0.0.1 to the IP address of the computer you want to connect to. It will look like 192.168.X.X

**Comment by nmateo** [comment]
Thanks.
