### ISSUE TITLE
P2pool server requirements? And separating P2pool + node to different VMs

### ISSUE THREAD

**Issue by westz36** [SChernykh/p2pool#65]
Hello SChernykh, 

im back. 2 Questions

1. What is the recommended specification to run a p2pool + server.
  CPU cores ? RAM size? 

2. I read somewhere you said its possible to run p2pool and monerod node on different systems, how would this work?
  Would the miners point to the p2pool IP or the monerod node IP?

Thanks

**Comment by SChernykh** [comment]
p2pool uses ~3 GB memory in default configuration, ~1 GB with `--light-mode` and ~0.6 GB with `--light-mode --no-cache` command line parameters. You could theoretically run p2pool on 1 GB RAM, 1 core VPS, but I recommend 2 GB RAM, 2 cores. If you add monerod, I recommend minimum 4 GB, 4 cores, but 6 GB RAM is better and more stable.

Yes, you can run p2pool and monerod on different machines, just use `--host YOUR_SERVER_IP` in p2pool command line and make sure ports 18081 and 18083 are open on the machine where you run monerod. Also you'll probably want to limit connections to ports 18081, 18083 to only your own IPs and use restricted RPC.

**Comment by tywkah** [comment]
> --light-mode
What's the real difference (except less ram usage) between normal mode and light one? What would be side effects if try? I couldn't find any info on this in readme, nor any info on using extra cmd options like '--no-color' which was found only  in the issues topic.  The 'help' cmd lists out only a few cmds. Seems like mysterious :D
By now I only noticed it takes the same time to sync after immediate p2pool restart with '--no-cache'.
And how to pass the config.json path or set custom min_diff param upon p2pool start? I'd like to experiment with it. 
Thanks

**Comment by SChernykh** [comment]
All console commands including `--no-color` are described in `--help`. You can change p2pool settings by putting config.json in the same folder as p2pool binary, see example: https://github.com/SChernykh/p2pool/blob/master/config.json

**Comment by tywkah** [comment]
Ah, of course how could i forget ``--help``! But we can't see all cmds if 'help' would be sent right to console window.
Placing config.json with modified diff and restarting p2pool.exe din't work, the client diff was the same 100k.
And what about running without randomx dataset (``----light-mode``)? What does this mode impact on?

**Comment by SChernykh** [comment]
You need to add `--config config.json` to the command line to use your custom config.

**Comment by Thorgrlm** [comment]
Hi, I have two computers, one at my house and I have monero + p2pool + xmrig on the same computer and work fine,  in another house on another line I have another computer, how can I connect my remote computer to my home computer?

**Comment by bladedoyle** [comment]
@Thorgrlm - you will need to have the p2pool listen on 0.0.0.0:3333, and open port 3333 in your router and forward it to the host running p2pool.

**Comment by Thorgrlm** [comment]
I have it setup as you indicate and it doesn't work, what else can it be?

**Comment by Thorgrlm** [comment]
> @Thorgrlm - you will need to have the p2pool listen on 0.0.0.0:3333, and open port 3333 in your router and forward it to the host running p2pool.
I have it setup as you indicate and it doesn't work, what else can it be?
I have my PC of my house at the address 192.168.1.20
port
service ------- internal port ------- external port ----- - protocol --- device
monero -----------3333 ---------------- 3333 --------------- TCP -----192.168.1.20

I'm use ubuntu 20.04

**Comment by Thorgrlm** [comment]
> @Thorgrlm - you will need to have the p2pool listen on 0.0.0.0:3333, and open port 3333 in your router and forward it to the host running p2pool.

I have it setup as you indicate and it doesn't work, what else can it be?
I have my PC of my house at the address 192.168.1.20
port
service ------- internal port ------- external port ----- - protocol --- device
monero -----------3333 ---------------- 3333 --------------- TCP -----192.168.1.20

I'm use ubuntu 20.04

**Comment by Thorgrlm** [comment]
@bladedoyle - I have it setup as you indicate and it doesn't work, what else can it be?
I have my PC of my house at the address 192.168.1.20
port
service ------- internal port ------- external port ----- - protocol --- device
monero -----------3333 ---------------- 3333 --------------- TCP -----192.168.1.20

I'm use ubuntu 20.04

**Comment by tywkah** [comment]
@SChernykh What does the light-mode actually affect? There are some consequences after using it, right? Otherwise, why give extra gigabytes of memory to a p2pool process if it could be run without it (random-x dataset)? 
I've to run a full node at intel atom/nm10 with 4GB RAM which cannot be increased due to the chipset limitation), and I will try to install p2pool there. So does it worth?
Thanks

**Comment by SChernykh** [comment]
It switches RandomX to the light mode (less memory used, slower block verification).

**Comment by darmax40** [comment]
> 

Hola amigo debes usar la ip publica y el puerto p2pool.
usa el comando curl ifconfig.me para saber tu ip publica y usarla para conectarte remotamente.
