### ISSUE TITLE
Include shares in JSON API

### ISSUE THREAD

**Issue by janderedev** [SChernykh/p2pool#66]
Hi,

I am trying to write a script that notifies me whenever my node finds a new share, but it appears that the JSON API enabled with `--data-api` does not expose information about shares.
Specifically, I would like the values of the "Your shares", "Your shares position" and "Block reward share" lines in the `status` output to be accessible in some way.

Since I run p2pool in docker, this would also allow me to access that info without first attaching to the container (and sometimes accidentally killing it instead of detaching).

Thanks!

**Comment by SChernykh** [comment]
`--stratum-api` has found shares counter and some other data.
