### ISSUE TITLE
P2Pool set up 

### ISSUE THREAD

**Issue by vpts1202** [SChernykh/p2pool#68]
Hi there
As I understood from README  of this repo the setup structure of P2Pool is Monero node + P2Pool node + miner.
- Can I use any public remote node with open port 18081 to P2Pool connecting?
- For multiply workers with the same wallet address would it be better to split in few remote nodes or it does not matter since pool is decentralized?
Thank you

**Comment by SChernykh** [comment]
- No, the remote node must be running p2pool-compatible binary and have port 18083 (ZMQ) open).
- You can ran as many nodes as you want, and connect any amount of workers to a node. It doesn't matter in the end, only overall hashrate and network latencies between miners and nodes matter.

**Comment by vpts1202** [comment]
> 
> 
>     * No, the remote node must be running p2pool-compatible binary and have port 18083 (ZMQ) open.
> 
>     * You can ran as many nodes as you want, and connect any amount of workers to a node. Single p2pool node with many workers will work fine. It doesn't matter in the end, only overall hashrate and network latencies between miners and nodes matter.

OK. Got it with thanks.
Do you know any Monero nodes providers except of GetBlock and NOWNodes?

PS: Your idea with such decentralized pool is really great. In proper management you are going to be in the TOP very quick.

**Comment by SChernykh** [comment]
> Do you know any Monero nodes providers except of GetBlock and NOWNodes?

I just run nodes on my own servers.

**Comment by baetensc** [comment]
Hello 

how to run it with a proxy ?

**Comment by UnrealValentin** [comment]
@baetensc open a own issue.

I think this issue could be closed.
