### ISSUE TITLE
Does not yet build on M1 Mac

### ISSUE THREAD

**Issue by wwinter86** [SChernykh/p2pool#7]
Cmake says "-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZMQ_LIBRARY
    linked by target "p2pool" in directory /Users/williamwinter/Downloads/p2pool
ZMQ_LIBRARY_DEBUG
    linked by target "p2pool" in directory /Users/williamwinter/Downloads/p2pool

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly."

**Comment by xmrvsbeast** [comment]
Try

cmake .. -DZMQ_LIBRARY=/path/to/lib.so -DZMQ_LIBRARY_DEBUG=/path/to/lib.so

**Comment by SChernykh** [comment]
Can you try https://github.com/SChernykh/p2pool#macos ?

**Comment by wwinter86** [comment]
> Can you try https://github.com/SChernykh/p2pool#macos ?

That generated two errors.
“[ 98%] Building CXX object CMakeFiles/p2pool.dir/src/zmq_reader.cpp.o
In file included from /Users/williamwinter/Downloads/p2pool/src/side_chain.cpp:27:
/Users/williamwinter/Downloads/p2pool/external/src/RandomX/src/intrin_portable.h:422:26: error: variable 'temp' is uninitialized when used here [-Werror,-Wuninitialized]
        temp = vcopyq_laneq_f64(temp, 1, a, 1);
                                ^~~~
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/arm_neon.h:66614:26: note: expanded from macro 'vcopyq_laneq_f64'
  float64x2_t __s0_841 = __p0_841; \
                         ^~~~~~~~
/Users/williamwinter/Downloads/p2pool/external/src/RandomX/src/intrin_portable.h:421:2: note: variable 'temp' is declared here
        float64x2_t temp;
        ^
/Users/williamwinter/Downloads/p2pool/external/src/RandomX/src/intrin_portable.h:513:25: error: variable 'x' is uninitialized when used here [-Werror,-Wuninitialized]
        x = vsetq_lane_f64(lo, x, 0);
                               ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/arm_neon.h:59825:22: note: expanded from macro 'vsetq_lane_f64'
  float64x2_t __s1 = __p1; \
                     ^~~~
/Users/williamwinter/Downloads/p2pool/external/src/RandomX/src/intrin_portable.h:512:2: note: variable 'x' is declared here
        rx_vec_f128 x;
        ^
2 errors generated.
make[2]: *** [CMakeFiles/p2pool.dir/src/side_chain.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/p2pool.dir/all] Error 2
make: *** [all] Error 2”

**Comment by SChernykh** [comment]
I've fixed these 2 warnings in the latest code? Can you try it? Delete p2pool folder and do all build steps (except `brew`) again to be sure you're compiling the latest code.

**Comment by wwinter86** [comment]
Thank you p2pool built now, but on Monero I get 
“ [ 15%] Building C object src/crypto/CMakeFiles/obj_cncrypto.dir/tree-hash.c.o
[ 15%] Linking CXX static library librandomx.a
[ 15%] Built target randomx
[ 15%] Built target obj_cncrypto
[ 15%] Built target obj_ringct
make[1]: *** [all] Error 2
make: *** [release-all] Error 2”

**Comment by mxcl** [comment]
“Worksforme” now. Thanks @SChernykh

**Comment by mxcl** [comment]
VERBOSE=1 make

```
cd /build/Darwin/p2pool-api-v0.17/release/external/easylogging++ && /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DAUTO_INITIALIZE_EASYLOGGINGPP -DBLOCKCHAIN_DB=DB_LMDB -DDEFAULT_DB_TYPE=\"lmdb\" -DHAVE_MEMSET_S -DHAVE_STRPTIME -DPER_BLOCK_CHECKPOINT -I/Users/mxcl/crypto/monero/external/rapidjson/include -I/Users/mxcl/crypto/monero/external/easylogging++ -I/Users/mxcl/crypto/monero/src -I/Users/mxcl/crypto/monero/contrib/epee/include -I/Users/mxcl/crypto/monero/external -I/Users/mxcl/crypto/monero/external/supercop/include -I/opt/homebrew/opt/openssl@1.1/include -I/build/Darwin/p2pool-api-v0.17/release/generated_include -I/build/Darwin/p2pool-api-v0.17/release/translations -I/build/Darwin/p2pool-api-v0.17/release/external/easylogging++ -isystem /usr/include/malloc -march=x86-64 -fvisibility=default -std=c++11 -std=c++11 -DNDEBUG -O2 -arch arm64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -fPIC -MD -MT external/easylogging++/CMakeFiles/easylogging.dir/easylogging++.cc.o -MF CMakeFiles/easylogging.dir/easylogging++.cc.o.d -o CMakeFiles/easylogging.dir/easylogging++.cc.o -c /Users/mxcl/crypto/monero/external/easylogging++/easylogging++.cc
clang: error: the clang compiler does not support '-march=x86-64'
```

**Comment by wwinter86** [comment]
Thanks changing 
```
if (APPLE AND NOT IOS)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=x86-64 -fvisibility=default -std=c++11")
  if (NOT OPENSSL_ROOT_DIR)
```

to 
```
if (APPLE AND NOT IOS)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a -fvisibility=default -std=c++11")
  if (NOT OPENSSL_ROOT_DIR)
```

WORKED! :)

**Comment by SChernykh** [comment]
Closing it since p2pool builds on Mac now

**Comment by frindle** [comment]
Getting this right now after having the above issues and following steps to resolve.  Let me know if I need to open a new ticket or if its just me being dumb:
`make[2]: *** No rule to make target `../lib.so', needed by `p2pool'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 98%] Building CXX object CMakeFiles/p2pool.dir/src/zmq_reader.cpp.o
make[1]: *** [CMakeFiles/p2pool.dir/all] Error 2
make: *** [all] Error 2
`
