### ISSUE TITLE
Todo?

### ISSUE THREAD

**Issue by UnrealValentin** [SChernykh/p2pool#70]
I would appreciate if there would be a list of things to do for people who would be willing to contribute :)
I think there would be much more contributions, if people would know what the Creator wants to be done. ^^

**Comment by UnrealValentin** [comment]
@SChernykh would be nice if you could answer this. ^^'

**Comment by SChernykh** [comment]
I don't have a list of things to do. Usually if something important comes, I just do it rather quickly, for example https://github.com/SChernykh/p2pool/pull/78
Github issues list is the closest thing to a "TODO" list.
