### ISSUE TITLE
> `--light-mode`

### ISSUE THREAD

**Issue by m-github-org** [SChernykh/p2pool#76]
> `--light-mode`
What's the real difference (except less ram usage) between normal mode and light one? What would be side effects if try? I couldn't find any info on this in readme, nor any info on using extra cmd options like '--no-color' which was found only  in the issues topic.  The 'help' cmd lists out only a few cmds. Seems like mysterious :D
By now I only noticed it takes same time to sync after immediate p2pool restart with '--no-cache'.
And how to pass the config.json path or set custom min_diff param upon p2pool start? I'd like to experiment with it. 
Thanks

_Originally posted by @tywkah in https://github.com/SChernykh/p2pool/issues/65#issuecomment-962681462_

**Comment by m-github-org** [comment]
#75 #65 #50

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool/issues/65#issuecomment-955569944
