### ISSUE TITLE
What's the configuration file format?

### ISSUE THREAD

**Issue by ratsclub** [SChernykh/p2pool#77]
I see that there's a `--config` flag but I can't find the file format nor the values that it supports. Where can I find it? Is this a file that I can use instead of the command-line flags?

**Comment by SChernykh** [comment]
https://github.com/SChernykh/p2pool/blob/master/config.json

**Comment by ratsclub** [comment]
Oh, I see. I thought there were a configuration file to use instead of the command-line arguments.

I'm trying to write a NixOS service for p2pool and it would make it a lot easier to setup!

https://github.com/NixOS/nixpkgs/pull/146623/files#diff-91d3d667f1ef82f6ee112b8e405ac20d4f7b5aa0430e94ae450d1de2acd00de2R149-R177
