### ISSUE TITLE
SideChain status does not reflect shares found

### ISSUE THREAD

**Issue by sjug** [SChernykh/p2pool#79]
Hi there,

Testing out p2pool and I'm not sure that it's actually.. working correctly?
Typically I see others with `Your hashrate (pool-side)` under `SideChain status`, and my shares according to the Side chain are still 0, but according to the StratumServer I have found a share.

How is there this disconnect?

```
2021-11-22 13:19:24.0859 SideChain status
Main chain height         = 2498867
Main chain hashrate       = 2.879 GH/s
Side chain height         = 695682
Side chain hashrate       = 218.241 MH/s
PPLNS window              = 2160 blocks (+174 uncles, 0 orphans)
Your shares               = 0 blocks (+0 uncles, 0 orphans)
Block reward share        = 0.000% (0.000000000000 XMR)
2021-11-22 13:19:24.0859 StratumServer status
Hashrate (15m est) = X KH/s
Hashrate (1h  est) = X KH/s
Hashrate (24h est) = X KH/s
Total hashes       = 2259134057
**Shares found       = 1**
Average effort     = 68.632%
Current effort     = 61.793%
Connections        = 2 (2 incoming)
2021-11-22 13:19:24.0859 P2PServer status
Connections    = 10 (0 incoming)
Peer list size = 220
Uptime         = 1d 13h 54m 18s
```

**Comment by SChernykh** [comment]
Two possibilities:
- Your found share is already out of the PPLNS window. Shares typically stay in the window for ~6 hours
- You were mining while p2pool was syncing, the found share was on an alternative chain (not the actual p2pool chain).

**Comment by sjug** [comment]
Thanks for your quick reply @SChernykh, so it's some feasible edge cases rather than connectivity issues. Cheers.
