### ISSUE TITLE
p2pool does not bind any specified p2p or stratum ports

### ISSUE THREAD

**Issue by sethsimmons** [SChernykh/p2pool#8]
Hey there,

Trying to get p2pool spun up, but for some reason it does not bind any p2p or stratum ports, despite me clearly specifying them.

Attempted command line options:

```
./p2pool --wallet MoneroAddress --rpc-port 18085 --stratum 0.0.0.0:3333 --p2p 0.0.0.0:37889

./p2pool --wallet MoneroAddress --rpc-port 18085 --stratum "0.0.0.0:3333" --p2p "0.0.0.0:37889"
```

Netstat shows no p2p or stratum ports bound:

```
netstat -tulpn | grep p2pool
tcp        0      0 127.0.0.1:37891         0.0.0.0:*               LISTEN      3268027/./p2pool
```

XMRig cannot connect:

```
[2021-09-03 18:53:38.868]  net      node.sethforprivacy.com:3333 connect error: "connection refused"
```

Connection is refused when tested via telnet:

```
telnet 5.9.120.18 3333
Trying 5.9.120.18...
telnet: Unable to connect to remote host: Connection refused
```

Firewall is allowing both ports:

```
ufw status
Status: active

To                         Action      From
--                         ------      ----
3333/tcp                   ALLOW       Anywhere
3333/tcp (v6)              ALLOW       Anywhere (v6)
```

Version info:

OS -- Ubuntu 20.04.3 LTS
p2pool -- 661d5961076b26cc26aa5edc82841f2e7c9a16ab
monerod -- v0.17.1.9-30bc57550

**Comment by SChernykh** [comment]
monerod is a wrong version, it should be v0.17.2.3-1c9c3b770 built from https://github.com/SChernykh/monero/commits/p2pool-api-v0.17
Try to add `--loglevel 5` to p2pool command line and check for warnings/errors at startup.

**Comment by sethsimmons** [comment]
Ah, had an old folder that didn't get updated when I ran the commands.

Rebuilt and got `v0.17.2.3-1c9c3b770`.

Re-testing.

**Comment by sethsimmons** [comment]
Yup, that fixed it.

Sorry for the trouble, didn't catch that :)
