### ISSUE TITLE
Launch of p2pool get an error on MacOS

### ISSUE THREAD

**Issue by footcow** [SChernykh/p2pool#82]
I have downloaded the p2poll 1.3.1 bin release for MacOS.

When I launch the command : 
```
./p2pool --host 127.0.0.1 --wallet WITH_MY_WALLET_ID
dyld[32703]: Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/footcow/p2pool-v1.3.1-macos-x64/p2pool
  Reason: tried: '/usr/local/opt/zeromq/lib/libzmq.5.dylib' (no such file), '/usr/local/lib/libzmq.5.dylib' (no such file), '/usr/lib/libzmq.5.dylib' (no such file)
zsh: abort      ./p2pool --host 127.0.0.1 --wallet
```
I'm using the Monterey MacOS version 12.0.1 ... but don' know how to install this missing lib.

Help will be welcome.

**Comment by footcow** [comment]
Solved by myself ...

So to be able to make functional p2pool on MacOS you need to install : 
- brew install zeromq
- brew install libuv
- brew install libpgm

Then it's functional ...

**Comment by EDad-v2** [comment]
@footcow sech1 pointed IRC Mac experts to this issue to assist. It's good that you were able to sort it yourself.
