### ISSUE TITLE
Pool Side Hashrate seems to drop after a little while after starting?

### ISSUE THREAD

**Issue by Codename-11** [SChernykh/p2pool#84]
Reaching out as I'm not positive that what I'm experiencing is normal, and after crawling through Google and Reddit for answers, I can't find anything that gives me confirmation. 

I've got Monerod and P2Pool both running as docker containers following Seth's guide for setting it up via docker-compose. I've opened ports `18080`, `18089`, `37889`, and `3333`. All verified using open-port-checker. This is running inside a Ubuntu-20.04 VM on Proxmox with 6 threads and 6gb of RAM allocated. It is on an HDD (which took forever to sync) but that doesn't seem to be an issue for running after the initial sync of Monerod. 

What I'm experiencing is when I start P2Pool with miners running and pointed towards my instance (4 of them, each with custom difficulty. 30x avg hash rate), upon running I get about ~10KH/s. For some reason, after about an hour, I notice that the Stratum Server `status` command reports my hash rate for the last 15 minutes starts to drop, of course followed by the other two averages. I let this continue overnight and throughout most of today, which resulted in no change to my p2pool.observer wallet page. 

Here's an example of what I see in the beginning:
[https://imgur.com/gallery/WH9uFKA](https://imgur.com/gallery/WH9uFKA)
An example of what I see after some uptime:
[https://imgur.com/gallery/jD5WBRr](https://imgur.com/gallery/jD5WBRr)

What's confusing is I did manage to recieve 3 small paypouts from my first ~8 hours of mining over night, the night before last. So I know that I've gotten it to the point of working, however the drop in hash rate via the "status" command makes me think something is wrong, as from what I understand, that's supposed to be somewhat accurate if I set custom difficulties for my miners, and not drop to 0.... 

As well I notice that in the second screenshot it shows that the PPLNS window is 2160 blocks, in which I had found 0 shares, but that seems not to change..? Am I waiting for a new block to arrive to change that back to 0 and on as in the first screenshot?

The only thing that seems to reset this, is to restart P2Pool, in which I start again from the point of the first screenshot, only to shortly see it drop to 0.... I'm not sure if this is normal behavior, or if I'm doing something wrong?

Please let me know if anyone has any input or advice! I really appreciate it! 

edit: fixed links

**Comment by SChernykh** [comment]
Did you set custom difficulty on your mining rigs? If you don't set it, hashrate accounting won't work properly p2pool-side.

**Comment by Codename-11** [comment]
I appreciate the response! Yes I have set a custom difficulty for each mining rig. 

I'm under the impression its 30 x (hasrate)? i.e 2500 H/S x 30 = 75000. So ./xmrig -u x+75000? I base that on the lowest average hashrate. I have noticed however that in XMRIG I on each miner I get plenty of jobs, but none ever say "CPU Accepted" which when I used to pool mine I recall seeing that. Not sure if that's a red flag or not. Otherwise as soon as P2Pool syncs it seems, my hasrate via Stratum Server status drops to zero, and remains as such.

Is it possible for me to confirm that xmrig is taking my custom difficulty setting? Otherwise I'm not quite sure where to go from here... Perhaps just nix setting a difficulty at least knowing that things are working?

Miner Screenshots:
![image](https://user-images.githubusercontent.com/10284999/144263857-32329341-eaa0-4df6-9d69-43f4bf9af29f.png)
![image](https://user-images.githubusercontent.com/10284999/144263919-d7e524c0-6fc9-4fe2-8b32-d6530c7459c2.png)

P2Pool Screenshot after 11 hours uptime:
![image](https://user-images.githubusercontent.com/10284999/144264072-7e1fee6e-b7a4-4df6-912d-bf138610d014.png)

**Comment by SChernykh** [comment]
Your command line for xmrig is wrong. It should be
```
xmrig -o 172.16.24.245:3333 -u x+75000
```

**Comment by Codename-11** [comment]
Ah, I gotcha. I can definitely update that. I had thought setting it under pool in config.json was doing the equivalent. Here's that for reference.
![image](https://user-images.githubusercontent.com/10284999/144273825-7d97c7b7-c7ef-4736-b31f-61faad5d0b26.png)

**Comment by SChernykh** [comment]
Don't mix config.json and command line, because xmrig will ignore something.

**Comment by Codename-11** [comment]
Nice, I updated it on my desktop xmrig instance and it started working immediately! I really appreciate the help. I've been searching hard to find someone that had similar issues but seemed to me I had just missed something. Is it your recommendation then to prefer command line over config.json? or vice versa? Thanks again!
