### ISSUE TITLE
command history

### ISSUE THREAD

**Issue by Masterbob79** [SChernykh/p2pool#86]
great work on p2pool! I really like it and have ran a node for years. I think it would be good to use up and down arrow to show past commands in p2pool screen. thanks.

**Comment by ar-** [comment]
This would indeed be very useful. I have to type in `status` so many times. Perhaps `status` can be replaced by `s` ? :-)

**Comment by The0ffle** [comment]
Bye-bye =)

19 Oca 2022 Çar 16:48 tarihinde Andreas ***@***.***> şunu
yazdı:

**Comment by kusky3** [comment]
if you  run p2pool in tmux, 
`while :; do tmux send-keys -t "$pane" C-z 'status' Enter` && sleep 3; done

**Comment by honobo** [comment]
FYI: On some consoles, if the previous command is `status`, Up Arrow + Enter already works too, which is indeed convenient.
