### ISSUE TITLE
limit incoming connections for p2p

### ISSUE THREAD

**Issue by tywkah** [SChernykh/p2pool#87]
how to? there's such an option for monerod `--in-peers`

**Comment by trasherdk** [comment]
How about `monerod --help | less` To get available options.

This thing could use a `-c|--config` thing, to make ps stuff less telling.

**Comment by tywkah** [comment]
![image](https://user-images.githubusercontent.com/93492811/147372083-74925e5a-f473-49e9-8523-0041f83ae311.png)
I mentioned about the similar monerod option and it was interesting whether there was a similar parameter for p2pool.

**Comment by SChernykh** [comment]
Added in https://github.com/SChernykh/p2pool/commit/f1b6212c82ce55c148c43073044e3983bb79a82f and https://github.com/SChernykh/p2pool/commit/2b01350add995de285e04b7c7d4ddcf74a2ec99a
