### ISSUE TITLE
Newbie Setup 

### ISSUE THREAD

**Issue by ASTMINERONE** [SChernykh/p2pool#90]
Just started the p2pool yesterday. xmrig has been running for 24 hours thus far. I ran a p2pool status cmd today and the result showed no hashrate for any time period. no total hashes,no shares shares, no effort. 

is this normal? 

thanks in advance.

**Comment by SChernykh** [comment]
https://p2pool.io/#faq
- P2Pool status shows 0 kh/s but I'm mining?
  - Default P2Pool difficulty is very high. You need to set custom fixed difficulty on your miner rigs to get more accurate stats on P2Pool (this will not change your mining rewards in any way). To set custom fixed difficulty for your miner (for example, 75000), run `./xmrig -o 127.0.0.1:3333 -u x+75000`

**Comment by ASTMINERONE** [comment]
Thanks a lot! Problem solved. All the best.
