### ISSUE TITLE
P2Pool On Multiple Machines IP Addresses

### ISSUE THREAD

**Issue by JussM3** [SChernykh/p2pool#91]
Using 3 different machines, how should they be addressed during setup? For example, is this correct? 127.0.0.1, 127.0.0.2, 127.0.0.3, etc?

**Comment by SChernykh** [comment]
https://support.microsoft.com/en-us/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9

**Comment by JussM3** [comment]
Thank you for the response. I'm using Linux so I'm assuming I use the IP address that my router assigns each machine?

**Comment by SChernykh** [comment]
You don't need xmrig-proxy, just connect all miners directly to your p2pool stratums IP:port. Yes, use IP addresses assigned by the router if all machines are on the same local network.
