### ISSUE TITLE
Great start then nothing

### ISSUE THREAD

**Issue by ASTMINERONE** [SChernykh/p2pool#92]
I moved several rigs to this Monero p2pool 72 hours ago. The pool performed fantastically for the first 24 hours. 

The p2pool status screen showed my stats and I had found blocks and shares and I was even paid Monero. All good. 

After 24 hours of mining my stats went to zero. No  blocks, no shares, no Monero payouts. What happened? 

Could you reply back with some suggested issues I can check or troubleshoot? 

Thanks,

**Comment by SChernykh** [comment]
Can you paste here the output of p2pool `status` console command?
I suggest to go to https://p2pool.observer/calculate-share-time and check how often you should find pool shares. Maybe you had incredible luck in the first 24 hours.

**Comment by ASTMINERONE** [comment]
![88E5547A-B26F-49A1-9922-F90B12114058](https://user-images.githubusercontent.com/78703906/147777802-64ba6295-9ced-4a4b-804b-d44aff1f1138.jpeg)

**Comment by SChernykh** [comment]
Are you mining on p2pool mini? All looks good on the screenshot, but not every share you find will result in payout because mini has only ~20 MH/s hashrate. It will average out in the end, you can watch your progress at https://mini.p2pool.observer/ - enter your wallet address there.

**Comment by ASTMINERONE** [comment]
I’m not using mini. Not familiar with what that is???

**Comment by ASTMINERONE** [comment]
I am using Linux Mint as OS.

**Comment by SChernykh** [comment]
Mini is the second p2pool: https://xmrvsbeast.com/p2pool/sidechains.html
If you're on the main pool, it will take you ~16 hours to find a share on average. If you have bad luck, it can be up several times longer so 3 days without shares is possible. You probably just found 1 share on the first day.
