### ISSUE TITLE
Version 1.4: Trojan Warning On Windows Defender

### ISSUE THREAD

**Issue by Sinjir** [SChernykh/p2pool#93]
Windows Defender alter this file has a "Trojan: Script/Oneeva.A!ml" and can executes commands from an attacker.

**Comment by SChernykh** [comment]
p2pool has RandomX hashing code embedded, this triggers false alarams in antiviruses. Check that you downloaded the official Github release from https://github.com/SChernykh/p2pool/releases/latest and check the SHA256 sum of the .zip archive. You can use [this guide](https://www.getmonero.org/resources/user-guides/verification-windows-beginner.html) to check it.
