### ISSUE TITLE
Does the p2pool support tls?

### ISSUE THREAD

**Issue by Acytoo** [SChernykh/p2pool#94]
Thank you for the great job. 

I have some servers(with public ip and located in dirrerent places), one is running monerod + p2pool + xmrig. I'd like to make rest of the servers with xmrig connect to the p2pool running on the first server. It's working fine now, but the connection is not encryptd.

Is there a way to encrypt the traffic?

**Comment by trasherdk** [comment]
How about [How to tunnel SSH over SSL/TLS](https://gist.github.com/bwann/82ed679e94972666808d97587d276677)

Is there anything in the `xmrig` <=> `p2pool` protocol that need encryption?

**Comment by SChernykh** [comment]
p2pool doesn't support TLS, but you can use `xmrig` -> `xmrig-proxy` -> `p2pool` setup where xmrig-proxy and p2pool run on the same machine and xmrig connects to the proxy via TLS.

**Comment by Acytoo** [comment]
> 

Yes, some ISP blocks monero minning.

**Comment by Acytoo** [comment]
> p2pool doesn't support TLS, but you can use `xmrig` -> `xmrig-proxy` -> `p2pool` setup where xmrig-proxy and p2pool run on the same machine and xmrig connects to the proxy via TLS.

Great idea, thank you.
