### ISSUE TITLE
Ran shasum on macOS download. does not match

### ISSUE THREAD

**Issue by GibHub420** [SChernykh/p2pool#95]
Ran shasum on macOS download. does not match

**Comment by GibHub420** [comment]
Does not start with 88

**Comment by SChernykh** [comment]
You need to check SHA-256 hash of `p2pool-v1.4-macos-x64.tar.gz` (not the p2pool binary inside it). I've just checked and it matches.

**Comment by GibHub420** [comment]
Okay. Will do. Thank you
